[package]
name = "singe-curand-sys"
description = "Raw FFI bindings for Nvidia cuRAND."
version = "0.1.0-alpha.1"
edition.workspace = true
repository.workspace = true
license-file = "../LICENSE"
readme = "README.md"
keywords = ["cuda", "curand", "bindings", "ffi"]
include.workspace = true

[package.metadata.docs.rs]
rustdoc-args = ["--html-in-header", "dist/katex_header.html"]

[features]
default = ["curand_13_2"]

curand_13_2 = ["singe-cuda-sys/runtime_13_2"]

[dependencies]
singe-cuda-sys.workspace = true
num_enum.workspace = true

[build-dependencies]
singe-cuda-find.workspace = true
anyhow.workspace = true
