[package]
name = "singe-onnx"
description = "ONNX model utilities."
version = "0.1.0-alpha.6"
edition.workspace = true
repository.workspace = true
keywords = ["singe", "onnx", "model"]
license-file = "../LICENSE"
readme = "README.md"

[dependencies]
thiserror.workspace = true
prost.workspace = true
bomboni_proto.workspace = true
bomboni_request.workspace = true
num_enum.workspace = true

[build-dependencies]
prost-build.workspace = true
bomboni_prost.workspace = true
