use crate::{
    context::StreamContext,
    error::Result,
    image::{
        color,
        view::{C1, C3, ImageView, ImageViewMut, PlanarImageView},
    },
    pipeline::image::ImagePipeline,
};

impl<'a> ImagePipeline<'a, u8, C3> {
    impl_color_convert_batch_same_layout_image!(
        yuv_to_rgb_batch,
        yuv_to_rgb_batch_advanced,
        color::yuv_to_rgb_batch_u8_c3,
        color::yuv_to_rgb_batch_u8_c3_advanced
    );
    impl_color_convert_batch_same_layout_image!(
        ycbcr_to_rgb_batch,
        ycbcr_to_rgb_batch_advanced,
        color::ycbcr_to_rgb_batch_u8_c3,
        color::ycbcr_to_rgb_batch_u8_c3_advanced
    );
    impl_color_convert_batch_same_layout_image!(
        ycbcr_to_bgr_batch,
        ycbcr_to_bgr_batch_advanced,
        color::ycbcr_to_bgr_batch_u8_c3,
        color::ycbcr_to_bgr_batch_u8_c3_advanced
    );
    impl_color_convert_batch_same_layout_image!(
        yuv_to_bgr_batch,
        yuv_to_bgr_batch_advanced,
        color::yuv_to_bgr_batch_u8_c3,
        color::yuv_to_bgr_batch_u8_c3_advanced
    );

    impl_color_convert_batch_planar_to_packed_image!(
        yuv_planar_to_rgb_batch,
        yuv_planar_to_rgb_batch_advanced,
        color::yuv_to_rgb_batch_u8_p3_to_c3,
        color::yuv_to_rgb_batch_u8_p3_to_c3_advanced
    );
    impl_color_convert_batch_planar_to_packed_image!(
        ycbcr_planar_to_rgb_batch,
        ycbcr_planar_to_rgb_batch_advanced,
        color::ycbcr_to_rgb_batch_u8_p3_to_c3,
        color::ycbcr_to_rgb_batch_u8_p3_to_c3_advanced
    );
    impl_color_convert_batch_planar_to_packed_image!(
        ycbcr_planar_to_bgr_batch,
        ycbcr_planar_to_bgr_batch_advanced,
        color::ycbcr_to_bgr_batch_u8_p3_to_c3,
        color::ycbcr_to_bgr_batch_u8_p3_to_c3_advanced
    );
    impl_color_convert_batch_planar_to_packed_image!(
        yuv_planar_to_bgr_batch,
        yuv_planar_to_bgr_batch_advanced,
        color::yuv_to_bgr_batch_u8_p3_to_c3,
        color::yuv_to_bgr_batch_u8_p3_to_c3_advanced
    );

    impl_subsampled_color_convert_batch_planar_to_packed_image!(
        yuv422_planar_to_rgb_batch,
        yuv422_planar_to_rgb_batch_advanced,
        color::yuv422_to_rgb_batch_u8_p3_to_c3,
        color::yuv422_to_rgb_batch_u8_p3_to_c3_advanced
    );
    impl_subsampled_color_convert_batch_planar_to_packed_image!(
        yuv420_planar_to_rgb_batch,
        yuv420_planar_to_rgb_batch_advanced,
        color::yuv420_to_rgb_batch_u8_p3_to_c3,
        color::yuv420_to_rgb_batch_u8_p3_to_c3_advanced
    );
    impl_subsampled_color_convert_batch_planar_to_packed_image!(
        ycbcr422_planar_to_rgb_batch,
        ycbcr422_planar_to_rgb_batch_advanced,
        color::ycbcr422_to_rgb_batch_u8_p3_to_c3,
        color::ycbcr422_to_rgb_batch_u8_p3_to_c3_advanced
    );
    impl_subsampled_color_convert_batch_planar_to_packed_image!(
        ycbcr420_planar_to_rgb_batch,
        ycbcr420_planar_to_rgb_batch_advanced,
        color::ycbcr420_to_rgb_batch_u8_p3_to_c3,
        color::ycbcr420_to_rgb_batch_u8_p3_to_c3_advanced
    );
    impl_subsampled_color_convert_batch_planar_to_packed_image!(
        ycbcr422_planar_to_bgr_batch,
        ycbcr422_planar_to_bgr_batch_advanced,
        color::ycbcr422_to_bgr_batch_u8_p3_to_c3,
        color::ycbcr422_to_bgr_batch_u8_p3_to_c3_advanced
    );
    impl_subsampled_color_convert_batch_planar_to_packed_image!(
        ycbcr420_planar_to_bgr_batch,
        ycbcr420_planar_to_bgr_batch_advanced,
        color::ycbcr420_to_bgr_batch_u8_p3_to_c3,
        color::ycbcr420_to_bgr_batch_u8_p3_to_c3_advanced
    );
    impl_subsampled_color_convert_batch_planar_to_packed_image!(
        yuv422_planar_to_bgr_batch,
        yuv422_planar_to_bgr_batch_advanced,
        color::yuv422_to_bgr_batch_u8_p3_to_c3,
        color::yuv422_to_bgr_batch_u8_p3_to_c3_advanced
    );
    impl_subsampled_color_convert_batch_planar_to_packed_image!(
        yuv420_planar_to_bgr_batch,
        yuv420_planar_to_bgr_batch_advanced,
        color::yuv420_to_bgr_batch_u8_p3_to_c3,
        color::yuv420_to_bgr_batch_u8_p3_to_c3_advanced
    );
}
