use crate::{
    context::StreamContext,
    error::Result,
    image::{
        filtering,
        view::{AC4, C1, C3, C4, ImageView, ImageViewMut},
    },
};

use super::{ImagePipeline, IntegerSeparableFilterImage};

impl_integer_separable_filter_image!(
    u8,
    C1,
    filtering::filter_column_u8_c1,
    filtering::filter_row_u8_c1
);
impl_integer_separable_filter_image!(
    u8,
    C3,
    filtering::filter_column_u8_c3,
    filtering::filter_row_u8_c3
);
impl_integer_separable_filter_image!(
    u8,
    C4,
    filtering::filter_column_u8_c4,
    filtering::filter_row_u8_c4
);
impl_integer_separable_filter_image!(
    u8,
    AC4,
    filtering::filter_column_u8_ac4,
    filtering::filter_row_u8_ac4
);
impl_integer_separable_filter_image!(
    u16,
    C1,
    filtering::filter_column_u16_c1,
    filtering::filter_row_u16_c1
);
impl_integer_separable_filter_image!(
    u16,
    C3,
    filtering::filter_column_u16_c3,
    filtering::filter_row_u16_c3
);
impl_integer_separable_filter_image!(
    u16,
    C4,
    filtering::filter_column_u16_c4,
    filtering::filter_row_u16_c4
);
impl_integer_separable_filter_image!(
    u16,
    AC4,
    filtering::filter_column_u16_ac4,
    filtering::filter_row_u16_ac4
);
impl_integer_separable_filter_image!(
    i16,
    C1,
    filtering::filter_column_i16_c1,
    filtering::filter_row_i16_c1
);
impl_integer_separable_filter_image!(
    i16,
    C3,
    filtering::filter_column_i16_c3,
    filtering::filter_row_i16_c3
);
impl_integer_separable_filter_image!(
    i16,
    C4,
    filtering::filter_column_i16_c4,
    filtering::filter_row_i16_c4
);
impl_integer_separable_filter_image!(
    i16,
    AC4,
    filtering::filter_column_i16_ac4,
    filtering::filter_row_i16_ac4
);
