use crate::{
    context::StreamContext,
    error::Result,
    image::{
        filtering,
        view::{AC4, C1, C3, C4, ImageView, ImageViewMut},
    },
};

use super::super::filtering_traits::*;
use super::ImagePipeline;

impl_edge_directional_border_filter_image!(
    u8,
    C1,
    filtering::filter_prewitt_horizontal_border_u8_c1,
    filtering::filter_prewitt_vertical_border_u8_c1,
    filtering::filter_roberts_down_border_u8_c1,
    filtering::filter_roberts_up_border_u8_c1,
    filtering::filter_sobel_horizontal_border_u8_c1,
    filtering::filter_sobel_vertical_border_u8_c1
);
impl_edge_directional_border_filter_image!(
    u8,
    C3,
    filtering::filter_prewitt_horizontal_border_u8_c3,
    filtering::filter_prewitt_vertical_border_u8_c3,
    filtering::filter_roberts_down_border_u8_c3,
    filtering::filter_roberts_up_border_u8_c3,
    filtering::filter_sobel_horizontal_border_u8_c3,
    filtering::filter_sobel_vertical_border_u8_c3
);
impl_edge_directional_border_filter_image!(
    u8,
    C4,
    filtering::filter_prewitt_horizontal_border_u8_c4,
    filtering::filter_prewitt_vertical_border_u8_c4,
    filtering::filter_roberts_down_border_u8_c4,
    filtering::filter_roberts_up_border_u8_c4,
    filtering::filter_sobel_horizontal_border_u8_c4,
    filtering::filter_sobel_vertical_border_u8_c4
);
impl_edge_directional_border_filter_image!(
    u8,
    AC4,
    filtering::filter_prewitt_horizontal_border_u8_ac4,
    filtering::filter_prewitt_vertical_border_u8_ac4,
    filtering::filter_roberts_down_border_u8_ac4,
    filtering::filter_roberts_up_border_u8_ac4,
    filtering::filter_sobel_horizontal_border_u8_ac4,
    filtering::filter_sobel_vertical_border_u8_ac4
);
impl_edge_directional_border_filter_image!(
    i16,
    C1,
    filtering::filter_prewitt_horizontal_border_i16_c1,
    filtering::filter_prewitt_vertical_border_i16_c1,
    filtering::filter_roberts_down_border_i16_c1,
    filtering::filter_roberts_up_border_i16_c1,
    filtering::filter_sobel_horizontal_border_i16_c1,
    filtering::filter_sobel_vertical_border_i16_c1
);
impl_edge_directional_border_filter_image!(
    i16,
    C3,
    filtering::filter_prewitt_horizontal_border_i16_c3,
    filtering::filter_prewitt_vertical_border_i16_c3,
    filtering::filter_roberts_down_border_i16_c3,
    filtering::filter_roberts_up_border_i16_c3,
    filtering::filter_sobel_horizontal_border_i16_c3,
    filtering::filter_sobel_vertical_border_i16_c3
);
impl_edge_directional_border_filter_image!(
    i16,
    C4,
    filtering::filter_prewitt_horizontal_border_i16_c4,
    filtering::filter_prewitt_vertical_border_i16_c4,
    filtering::filter_roberts_down_border_i16_c4,
    filtering::filter_roberts_up_border_i16_c4,
    filtering::filter_sobel_horizontal_border_i16_c4,
    filtering::filter_sobel_vertical_border_i16_c4
);
impl_edge_directional_border_filter_image!(
    i16,
    AC4,
    filtering::filter_prewitt_horizontal_border_i16_ac4,
    filtering::filter_prewitt_vertical_border_i16_ac4,
    filtering::filter_roberts_down_border_i16_ac4,
    filtering::filter_roberts_up_border_i16_ac4,
    filtering::filter_sobel_horizontal_border_i16_ac4,
    filtering::filter_sobel_vertical_border_i16_ac4
);
impl_edge_directional_border_filter_image!(
    f32,
    C1,
    filtering::filter_prewitt_horizontal_border_f32_c1,
    filtering::filter_prewitt_vertical_border_f32_c1,
    filtering::filter_roberts_down_border_f32_c1,
    filtering::filter_roberts_up_border_f32_c1,
    filtering::filter_sobel_horizontal_border_f32_c1,
    filtering::filter_sobel_vertical_border_f32_c1
);
impl_edge_directional_border_filter_image!(
    f32,
    C3,
    filtering::filter_prewitt_horizontal_border_f32_c3,
    filtering::filter_prewitt_vertical_border_f32_c3,
    filtering::filter_roberts_down_border_f32_c3,
    filtering::filter_roberts_up_border_f32_c3,
    filtering::filter_sobel_horizontal_border_f32_c3,
    filtering::filter_sobel_vertical_border_f32_c3
);
impl_edge_directional_border_filter_image!(
    f32,
    C4,
    filtering::filter_prewitt_horizontal_border_f32_c4,
    filtering::filter_prewitt_vertical_border_f32_c4,
    filtering::filter_roberts_down_border_f32_c4,
    filtering::filter_roberts_up_border_f32_c4,
    filtering::filter_sobel_horizontal_border_f32_c4,
    filtering::filter_sobel_vertical_border_f32_c4
);
impl_edge_directional_border_filter_image!(
    f32,
    AC4,
    filtering::filter_prewitt_horizontal_border_f32_ac4,
    filtering::filter_prewitt_vertical_border_f32_ac4,
    filtering::filter_roberts_down_border_f32_ac4,
    filtering::filter_roberts_up_border_f32_ac4,
    filtering::filter_sobel_horizontal_border_f32_ac4,
    filtering::filter_sobel_vertical_border_f32_ac4
);
