use crate::{
    context::StreamContext,
    error::Result,
    image::{
        morphology,
        view::{AC4, C1, C3, C4, ImageView, ImageViewMut},
    },
    types::{BorderType, Point, Size},
};

use super::super::super::{ImagePipeline, morphology_traits::MaskMorphologyBorderImage};

impl_mask_morphology_border_image!(
    u8,
    C1,
    morphology::dilate_border_u8_c1,
    morphology::erode_border_u8_c1
);
impl_mask_morphology_border_image!(
    u8,
    C3,
    morphology::dilate_border_u8_c3,
    morphology::erode_border_u8_c3
);
impl_mask_morphology_border_image!(
    u8,
    C4,
    morphology::dilate_border_u8_c4,
    morphology::erode_border_u8_c4
);
impl_mask_morphology_border_image!(
    u8,
    AC4,
    morphology::dilate_border_u8_ac4,
    morphology::erode_border_u8_ac4
);
impl_mask_morphology_border_image!(
    u16,
    C1,
    morphology::dilate_border_u16_c1,
    morphology::erode_border_u16_c1
);
impl_mask_morphology_border_image!(
    u16,
    C3,
    morphology::dilate_border_u16_c3,
    morphology::erode_border_u16_c3
);
impl_mask_morphology_border_image!(
    u16,
    C4,
    morphology::dilate_border_u16_c4,
    morphology::erode_border_u16_c4
);
impl_mask_morphology_border_image!(
    u16,
    AC4,
    morphology::dilate_border_u16_ac4,
    morphology::erode_border_u16_ac4
);
impl_mask_morphology_border_image!(
    f32,
    C1,
    morphology::dilate_border_f32_c1,
    morphology::erode_border_f32_c1
);
impl_mask_morphology_border_image!(
    f32,
    C3,
    morphology::dilate_border_f32_c3,
    morphology::erode_border_f32_c3
);
impl_mask_morphology_border_image!(
    f32,
    C4,
    morphology::dilate_border_f32_c4,
    morphology::erode_border_f32_c4
);
impl_mask_morphology_border_image!(
    f32,
    AC4,
    morphology::dilate_border_f32_ac4,
    morphology::erode_border_f32_ac4
);
