use crate::{
    context::StreamContext,
    error::Result,
    image::{
        statistics,
        view::{AC4, C1, C3, C4, ImageView, ImageViewMut},
    },
    pipeline::image::ImagePipeline,
};

use super::super::traits::*;

impl_cross_correlation_norm_to_image!(
    u8,
    f32,
    C1,
    statistics::cross_correlation_full_norm_u8_to_f32_c1,
    statistics::cross_correlation_same_norm_u8_to_f32_c1,
    statistics::cross_correlation_valid_norm_u8_to_f32_c1
);
impl_cross_correlation_norm_to_image!(
    u8,
    f32,
    C3,
    statistics::cross_correlation_full_norm_u8_to_f32_c3,
    statistics::cross_correlation_same_norm_u8_to_f32_c3,
    statistics::cross_correlation_valid_norm_u8_to_f32_c3
);
impl_cross_correlation_norm_to_image!(
    u8,
    f32,
    C4,
    statistics::cross_correlation_full_norm_u8_to_f32_c4,
    statistics::cross_correlation_same_norm_u8_to_f32_c4,
    statistics::cross_correlation_valid_norm_u8_to_f32_c4
);
impl_cross_correlation_norm_to_image!(
    u8,
    f32,
    AC4,
    statistics::cross_correlation_full_norm_u8_to_f32_ac4,
    statistics::cross_correlation_same_norm_u8_to_f32_ac4,
    statistics::cross_correlation_valid_norm_u8_to_f32_ac4
);
impl_cross_correlation_norm_to_image!(
    i8,
    f32,
    C1,
    statistics::cross_correlation_full_norm_i8_to_f32_c1,
    statistics::cross_correlation_same_norm_i8_to_f32_c1,
    statistics::cross_correlation_valid_norm_i8_to_f32_c1
);
impl_cross_correlation_norm_to_image!(
    i8,
    f32,
    C3,
    statistics::cross_correlation_full_norm_i8_to_f32_c3,
    statistics::cross_correlation_same_norm_i8_to_f32_c3,
    statistics::cross_correlation_valid_norm_i8_to_f32_c3
);
impl_cross_correlation_norm_to_image!(
    i8,
    f32,
    C4,
    statistics::cross_correlation_full_norm_i8_to_f32_c4,
    statistics::cross_correlation_same_norm_i8_to_f32_c4,
    statistics::cross_correlation_valid_norm_i8_to_f32_c4
);
impl_cross_correlation_norm_to_image!(
    i8,
    f32,
    AC4,
    statistics::cross_correlation_full_norm_i8_to_f32_ac4,
    statistics::cross_correlation_same_norm_i8_to_f32_ac4,
    statistics::cross_correlation_valid_norm_i8_to_f32_ac4
);
impl_cross_correlation_norm_to_image!(
    u16,
    f32,
    C1,
    statistics::cross_correlation_full_norm_u16_to_f32_c1,
    statistics::cross_correlation_same_norm_u16_to_f32_c1,
    statistics::cross_correlation_valid_norm_u16_to_f32_c1
);
impl_cross_correlation_norm_to_image!(
    u16,
    f32,
    C3,
    statistics::cross_correlation_full_norm_u16_to_f32_c3,
    statistics::cross_correlation_same_norm_u16_to_f32_c3,
    statistics::cross_correlation_valid_norm_u16_to_f32_c3
);
impl_cross_correlation_norm_to_image!(
    u16,
    f32,
    C4,
    statistics::cross_correlation_full_norm_u16_to_f32_c4,
    statistics::cross_correlation_same_norm_u16_to_f32_c4,
    statistics::cross_correlation_valid_norm_u16_to_f32_c4
);
impl_cross_correlation_norm_to_image!(
    u16,
    f32,
    AC4,
    statistics::cross_correlation_full_norm_u16_to_f32_ac4,
    statistics::cross_correlation_same_norm_u16_to_f32_ac4,
    statistics::cross_correlation_valid_norm_u16_to_f32_ac4
);
