use crate::{
    context::StreamContext,
    error::Result,
    image::{
        statistics,
        view::{C1, C3, C4, ImageView, ImageViewMut},
    },
    pipeline::image::ImagePipeline,
};

use super::super::traits::*;

impl_cross_correlation_norm_level_advanced_image!(
    f32,
    C1,
    statistics::cross_correlation_full_norm_level_advanced_f32_c1,
    statistics::cross_correlation_same_norm_level_advanced_f32_c1,
    statistics::cross_correlation_valid_norm_level_advanced_f32_c1
);
impl_cross_correlation_norm_level_advanced_image!(
    f32,
    C3,
    statistics::cross_correlation_full_norm_level_advanced_f32_c3,
    statistics::cross_correlation_same_norm_level_advanced_f32_c3,
    statistics::cross_correlation_valid_norm_level_advanced_f32_c3
);
impl_cross_correlation_norm_level_advanced_image!(
    f32,
    C4,
    statistics::cross_correlation_full_norm_level_advanced_f32_c4,
    statistics::cross_correlation_same_norm_level_advanced_f32_c4,
    statistics::cross_correlation_valid_norm_level_advanced_f32_c4
);
impl_cross_correlation_norm_level_advanced_image!(
    f64,
    C1,
    statistics::cross_correlation_full_norm_level_advanced_f64_c1,
    statistics::cross_correlation_same_norm_level_advanced_f64_c1,
    statistics::cross_correlation_valid_norm_level_advanced_f64_c1
);
impl_cross_correlation_norm_level_advanced_image!(
    f64,
    C3,
    statistics::cross_correlation_full_norm_level_advanced_f64_c3,
    statistics::cross_correlation_same_norm_level_advanced_f64_c3,
    statistics::cross_correlation_valid_norm_level_advanced_f64_c3
);
impl_cross_correlation_norm_level_advanced_image!(
    f64,
    C4,
    statistics::cross_correlation_full_norm_level_advanced_f64_c4,
    statistics::cross_correlation_same_norm_level_advanced_f64_c4,
    statistics::cross_correlation_valid_norm_level_advanced_f64_c4
);

impl_cross_correlation_norm_level_advanced_to_image!(
    u8,
    f32,
    C1,
    statistics::cross_correlation_full_norm_level_advanced_u8_to_f32_c1,
    statistics::cross_correlation_same_norm_level_advanced_u8_to_f32_c1,
    statistics::cross_correlation_valid_norm_level_advanced_u8_to_f32_c1
);
impl_cross_correlation_norm_level_advanced_to_image!(
    u8,
    f32,
    C3,
    statistics::cross_correlation_full_norm_level_advanced_u8_to_f32_c3,
    statistics::cross_correlation_same_norm_level_advanced_u8_to_f32_c3,
    statistics::cross_correlation_valid_norm_level_advanced_u8_to_f32_c3
);
impl_cross_correlation_norm_level_advanced_to_image!(
    u8,
    f32,
    C4,
    statistics::cross_correlation_full_norm_level_advanced_u8_to_f32_c4,
    statistics::cross_correlation_same_norm_level_advanced_u8_to_f32_c4,
    statistics::cross_correlation_valid_norm_level_advanced_u8_to_f32_c4
);
impl_cross_correlation_norm_level_advanced_to_image!(
    i8,
    f32,
    C1,
    statistics::cross_correlation_full_norm_level_advanced_i8_to_f32_c1,
    statistics::cross_correlation_same_norm_level_advanced_i8_to_f32_c1,
    statistics::cross_correlation_valid_norm_level_advanced_i8_to_f32_c1
);
impl_cross_correlation_norm_level_advanced_to_image!(
    i8,
    f32,
    C3,
    statistics::cross_correlation_full_norm_level_advanced_i8_to_f32_c3,
    statistics::cross_correlation_same_norm_level_advanced_i8_to_f32_c3,
    statistics::cross_correlation_valid_norm_level_advanced_i8_to_f32_c3
);
impl_cross_correlation_norm_level_advanced_to_image!(
    i8,
    f32,
    C4,
    statistics::cross_correlation_full_norm_level_advanced_i8_to_f32_c4,
    statistics::cross_correlation_same_norm_level_advanced_i8_to_f32_c4,
    statistics::cross_correlation_valid_norm_level_advanced_i8_to_f32_c4
);
impl_cross_correlation_norm_level_advanced_to_image!(
    u16,
    f32,
    C1,
    statistics::cross_correlation_full_norm_level_advanced_u16_to_f32_c1,
    statistics::cross_correlation_same_norm_level_advanced_u16_to_f32_c1,
    statistics::cross_correlation_valid_norm_level_advanced_u16_to_f32_c1
);
impl_cross_correlation_norm_level_advanced_to_image!(
    u16,
    f32,
    C3,
    statistics::cross_correlation_full_norm_level_advanced_u16_to_f32_c3,
    statistics::cross_correlation_same_norm_level_advanced_u16_to_f32_c3,
    statistics::cross_correlation_valid_norm_level_advanced_u16_to_f32_c3
);
impl_cross_correlation_norm_level_advanced_to_image!(
    u16,
    f32,
    C4,
    statistics::cross_correlation_full_norm_level_advanced_u16_to_f32_c4,
    statistics::cross_correlation_same_norm_level_advanced_u16_to_f32_c4,
    statistics::cross_correlation_valid_norm_level_advanced_u16_to_f32_c4
);
