[package]
name = "xtask"
version = "0.0.0"
edition.workspace = true
repository.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
serde = { version = "1", features = ["derive"] }
serde_json = "1"
proc-macro2.workspace = true
quote.workspace = true
syn = { workspace = true, features = ["full", "visit-mut"] }
prettyplease.workspace = true
bomboni_core.workspace = true
