[package]
name = "singe-cudss-sys"
description = "Low-level FFI bindings for the NVIDIA Direct Sparse Solvers (cuDSS) library."
version = "0.1.0-alpha.2"
edition.workspace = true
repository.workspace = true
license-file = "../LICENSE"
readme = "README.md"
keywords = ["cuda", "cudss", "bindings", "ffi"]
include.workspace = true

[package.metadata.docs.rs]
rustdoc-args = ["--html-in-header", "dist/katex_header.html"]

[features]
default = ["cudss_0_8"]

cudss_0_8 = ["singe-cuda-sys/runtime_13_3"]

[dependencies]
singe-cuda-sys.workspace = true
num_enum.workspace = true

[build-dependencies]
singe-cuda-find.workspace = true
anyhow.workspace = true
