[package]
name = "singe-nvml-sys"
description = "Low-level FFI bindings for the NVIDIA Management Library (NVML)."
version = "0.1.0-alpha.6"
edition.workspace = true
repository.workspace = true
license-file = "../LICENSE"
readme = "README.md"
keywords = ["nvidia", "nvml", "bindings", "ffi"]
include.workspace = true

[package.metadata.docs.rs]
rustdoc-args = ["--html-in-header", "dist/katex_header.html"]

[features]
default = ["nvml_13_2"]

nvml_13_2 = []

[dependencies]
num_enum.workspace = true

[build-dependencies]
singe-cuda-find.workspace = true
