/* automatically generated by rust-bindgen 0.72.1 */

pub const NCCL_MAJOR: u32 = 2;
pub const NCCL_MINOR: u32 = 28;
pub const NCCL_PATCH: u32 = 7;
pub const NCCL_SUFFIX: &[u8; 1] = b"\0";
pub const NCCL_VERSION_CODE: u32 = 22807;
pub const NCCL_UNIQUE_ID_BYTES: u32 = 128;
pub const NCCL_SPLIT_NOCOLOR: i32 = -1;
pub const NCCL_UNDEF_FLOAT: f64 = -1.0;
pub const NCCL_WIN_DEFAULT: u32 = 0;
pub const NCCL_WIN_COLL_SYMMETRIC: u32 = 1;
pub const NCCL_WIN_REQUIRED_ALIGNMENT: u32 = 4096;
pub const NCCL_CTA_POLICY_DEFAULT: u32 = 0;
pub const NCCL_CTA_POLICY_EFFICIENCY: u32 = 1;
pub const NCCL_CTA_POLICY_ZERO: u32 = 2;
pub const NCCL_SHRINK_DEFAULT: u32 = 0;
pub const NCCL_SHRINK_ABORT: u32 = 1;
pub const NCCL_REVOKE_DEFAULT: u32 = 0;
pub type size_t = ::core::ffi::c_ulong;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ncclComm {
    _unused: [u8; 0],
}
pub type ncclComm_t = *mut ncclComm;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ncclWindow_vidmem {
    _unused: [u8; 0],
}
pub type ncclWindow_t = *mut ncclWindow_vidmem;
#[repr(C)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct ncclUniqueId {
    pub internal: [::core::ffi::c_char; 128usize],
}
impl Default for ncclUniqueId {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(u32)]
#[derive(
    Debug,
    Copy,
    Clone,
    Hash,
    PartialOrd,
    Ord,
    PartialEq,
    Eq,
    TryFromPrimitive,
    IntoPrimitive,
)]
pub enum ncclResult_t {
    ncclSuccess = 0,
    ncclUnhandledCudaError = 1,
    ncclSystemError = 2,
    ncclInternalError = 3,
    ncclInvalidArgument = 4,
    ncclInvalidUsage = 5,
    ncclRemoteError = 6,
    ncclInProgress = 7,
    ncclNumResults = 8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct ncclConfig_v22800 {
    pub size: size_t,
    pub magic: ::core::ffi::c_uint,
    pub version: ::core::ffi::c_uint,
    pub blocking: ::core::ffi::c_int,
    pub cgaClusterSize: ::core::ffi::c_int,
    pub minCTAs: ::core::ffi::c_int,
    pub maxCTAs: ::core::ffi::c_int,
    pub netName: *const ::core::ffi::c_char,
    pub splitShare: ::core::ffi::c_int,
    pub trafficClass: ::core::ffi::c_int,
    pub commName: *const ::core::ffi::c_char,
    pub collnetEnable: ::core::ffi::c_int,
    pub CTAPolicy: ::core::ffi::c_int,
    pub shrinkShare: ::core::ffi::c_int,
    pub nvlsCTAs: ::core::ffi::c_int,
    pub nChannelsPerNetPeer: ::core::ffi::c_int,
    pub nvlinkCentricSched: ::core::ffi::c_int,
}
impl Default for ncclConfig_v22800 {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type ncclConfig_t = ncclConfig_v22800;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone, PartialOrd, PartialEq)]
pub struct ncclSimInfo_v22200 {
    pub size: size_t,
    pub magic: ::core::ffi::c_uint,
    pub version: ::core::ffi::c_uint,
    pub estimatedTime: f32,
}
pub type ncclSimInfo_t = ncclSimInfo_v22200;
unsafe extern "C" {
    pub fn ncclMemAlloc(
        ptr: *mut *mut ::core::ffi::c_void,
        size: size_t,
    ) -> ncclResult_t;
}
unsafe extern "C" {
    pub fn ncclMemFree(ptr: *mut ::core::ffi::c_void) -> ncclResult_t;
}
unsafe extern "C" {
    pub fn ncclGetVersion(version: *mut ::core::ffi::c_int) -> ncclResult_t;
}
unsafe extern "C" {
    pub fn ncclGetUniqueId(uniqueId: *mut ncclUniqueId) -> ncclResult_t;
}
unsafe extern "C" {
    pub fn ncclCommInitRankConfig(
        comm: *mut ncclComm_t,
        nranks: ::core::ffi::c_int,
        commId: ncclUniqueId,
        rank: ::core::ffi::c_int,
        config: *mut ncclConfig_t,
    ) -> ncclResult_t;
}
unsafe extern "C" {
    pub fn ncclCommInitRank(
        comm: *mut ncclComm_t,
        nranks: ::core::ffi::c_int,
        commId: ncclUniqueId,
        rank: ::core::ffi::c_int,
    ) -> ncclResult_t;
}
unsafe extern "C" {
    pub fn ncclCommInitAll(
        comm: *mut ncclComm_t,
        ndev: ::core::ffi::c_int,
        devlist: *const ::core::ffi::c_int,
    ) -> ncclResult_t;
}
unsafe extern "C" {
    pub fn ncclCommFinalize(comm: ncclComm_t) -> ncclResult_t;
}
unsafe extern "C" {
    pub fn ncclCommDestroy(comm: ncclComm_t) -> ncclResult_t;
}
unsafe extern "C" {
    pub fn ncclCommAbort(comm: ncclComm_t) -> ncclResult_t;
}
unsafe extern "C" {
    pub fn ncclCommRevoke(
        comm: ncclComm_t,
        revokeFlags: ::core::ffi::c_int,
    ) -> ncclResult_t;
}
unsafe extern "C" {
    pub fn ncclCommSplit(
        comm: ncclComm_t,
        color: ::core::ffi::c_int,
        key: ::core::ffi::c_int,
        newcomm: *mut ncclComm_t,
        config: *mut ncclConfig_t,
    ) -> ncclResult_t;
}
unsafe extern "C" {
    pub fn ncclCommShrink(
        comm: ncclComm_t,
        excludeRanksList: *mut ::core::ffi::c_int,
        excludeRanksCount: ::core::ffi::c_int,
        newcomm: *mut ncclComm_t,
        config: *mut ncclConfig_t,
        shrinkFlags: ::core::ffi::c_int,
    ) -> ncclResult_t;
}
unsafe extern "C" {
    pub fn ncclCommInitRankScalable(
        newcomm: *mut ncclComm_t,
        nranks: ::core::ffi::c_int,
        myrank: ::core::ffi::c_int,
        nId: ::core::ffi::c_int,
        commIds: *mut ncclUniqueId,
        config: *mut ncclConfig_t,
    ) -> ncclResult_t;
}
unsafe extern "C" {
    pub fn ncclGetErrorString(result: ncclResult_t) -> *const ::core::ffi::c_char;
}
unsafe extern "C" {
    pub fn ncclGetLastError(comm: ncclComm_t) -> *const ::core::ffi::c_char;
}
unsafe extern "C" {
    pub fn ncclResetDebugInit();
}
unsafe extern "C" {
    pub fn ncclCommGetAsyncError(
        comm: ncclComm_t,
        asyncError: *mut ncclResult_t,
    ) -> ncclResult_t;
}
unsafe extern "C" {
    pub fn ncclCommCount(
        comm: ncclComm_t,
        count: *mut ::core::ffi::c_int,
    ) -> ncclResult_t;
}
unsafe extern "C" {
    pub fn ncclCommCuDevice(
        comm: ncclComm_t,
        device: *mut ::core::ffi::c_int,
    ) -> ncclResult_t;
}
unsafe extern "C" {
    pub fn ncclCommUserRank(
        comm: ncclComm_t,
        rank: *mut ::core::ffi::c_int,
    ) -> ncclResult_t;
}
unsafe extern "C" {
    pub fn ncclCommRegister(
        comm: ncclComm_t,
        buff: *mut ::core::ffi::c_void,
        size: size_t,
        handle: *mut *mut ::core::ffi::c_void,
    ) -> ncclResult_t;
}
unsafe extern "C" {
    pub fn ncclCommDeregister(
        comm: ncclComm_t,
        handle: *mut ::core::ffi::c_void,
    ) -> ncclResult_t;
}
unsafe extern "C" {
    pub fn ncclCommWindowRegister(
        comm: ncclComm_t,
        buff: *mut ::core::ffi::c_void,
        size: size_t,
        win: *mut ncclWindow_t,
        winFlags: ::core::ffi::c_int,
    ) -> ncclResult_t;
}
unsafe extern "C" {
    pub fn ncclCommWindowDeregister(comm: ncclComm_t, win: ncclWindow_t) -> ncclResult_t;
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub enum ncclRedOp_dummy_t {
    ncclNumOps_dummy = 5,
}
#[repr(u32)]
#[derive(
    Debug,
    Copy,
    Clone,
    Hash,
    PartialOrd,
    Ord,
    PartialEq,
    Eq,
    TryFromPrimitive,
    IntoPrimitive,
)]
pub enum ncclRedOp_t {
    ncclSum = 0,
    ncclProd = 1,
    ncclMax = 2,
    ncclMin = 3,
    ncclAvg = 4,
    ncclNumOps = 5,
    ncclMaxRedOp = 2147483647,
}
impl ncclDataType_t {
    pub const ncclChar: ncclDataType_t = ncclDataType_t::ncclInt8;
}
impl ncclDataType_t {
    pub const ncclInt: ncclDataType_t = ncclDataType_t::ncclInt32;
}
impl ncclDataType_t {
    pub const ncclHalf: ncclDataType_t = ncclDataType_t::ncclFloat16;
}
impl ncclDataType_t {
    pub const ncclFloat: ncclDataType_t = ncclDataType_t::ncclFloat32;
}
impl ncclDataType_t {
    pub const ncclDouble: ncclDataType_t = ncclDataType_t::ncclFloat64;
}
#[repr(u32)]
#[derive(
    Debug,
    Copy,
    Clone,
    Hash,
    PartialOrd,
    Ord,
    PartialEq,
    Eq,
    TryFromPrimitive,
    IntoPrimitive,
)]
pub enum ncclDataType_t {
    ncclInt8 = 0,
    ncclUint8 = 1,
    ncclInt32 = 2,
    ncclUint32 = 3,
    ncclInt64 = 4,
    ncclUint64 = 5,
    ncclFloat16 = 6,
    ncclFloat32 = 7,
    ncclFloat64 = 8,
    ncclBfloat16 = 9,
    ncclFloat8e4m3 = 10,
    ncclFloat8e5m2 = 11,
    ncclNumTypes = 12,
}
#[repr(u32)]
#[derive(
    Debug,
    Copy,
    Clone,
    Hash,
    PartialOrd,
    Ord,
    PartialEq,
    Eq,
    TryFromPrimitive,
    IntoPrimitive,
)]
pub enum ncclScalarResidence_t {
    ncclScalarDevice = 0,
    ncclScalarHostImmediate = 1,
}
unsafe extern "C" {
    pub fn ncclRedOpCreatePreMulSum(
        op: *mut ncclRedOp_t,
        scalar: *mut ::core::ffi::c_void,
        datatype: ncclDataType_t,
        residence: ncclScalarResidence_t,
        comm: ncclComm_t,
    ) -> ncclResult_t;
}
unsafe extern "C" {
    pub fn ncclRedOpDestroy(op: ncclRedOp_t, comm: ncclComm_t) -> ncclResult_t;
}
unsafe extern "C" {
    pub fn ncclReduce(
        sendbuff: *const ::core::ffi::c_void,
        recvbuff: *mut ::core::ffi::c_void,
        count: size_t,
        datatype: ncclDataType_t,
        op: ncclRedOp_t,
        root: ::core::ffi::c_int,
        comm: ncclComm_t,
        stream: cudaStream_t,
    ) -> ncclResult_t;
}
unsafe extern "C" {
    pub fn ncclBcast(
        buff: *mut ::core::ffi::c_void,
        count: size_t,
        datatype: ncclDataType_t,
        root: ::core::ffi::c_int,
        comm: ncclComm_t,
        stream: cudaStream_t,
    ) -> ncclResult_t;
}
unsafe extern "C" {
    pub fn ncclBroadcast(
        sendbuff: *const ::core::ffi::c_void,
        recvbuff: *mut ::core::ffi::c_void,
        count: size_t,
        datatype: ncclDataType_t,
        root: ::core::ffi::c_int,
        comm: ncclComm_t,
        stream: cudaStream_t,
    ) -> ncclResult_t;
}
unsafe extern "C" {
    pub fn ncclAllReduce(
        sendbuff: *const ::core::ffi::c_void,
        recvbuff: *mut ::core::ffi::c_void,
        count: size_t,
        datatype: ncclDataType_t,
        op: ncclRedOp_t,
        comm: ncclComm_t,
        stream: cudaStream_t,
    ) -> ncclResult_t;
}
unsafe extern "C" {
    pub fn ncclReduceScatter(
        sendbuff: *const ::core::ffi::c_void,
        recvbuff: *mut ::core::ffi::c_void,
        recvcount: size_t,
        datatype: ncclDataType_t,
        op: ncclRedOp_t,
        comm: ncclComm_t,
        stream: cudaStream_t,
    ) -> ncclResult_t;
}
unsafe extern "C" {
    pub fn ncclAllGather(
        sendbuff: *const ::core::ffi::c_void,
        recvbuff: *mut ::core::ffi::c_void,
        sendcount: size_t,
        datatype: ncclDataType_t,
        comm: ncclComm_t,
        stream: cudaStream_t,
    ) -> ncclResult_t;
}
unsafe extern "C" {
    pub fn ncclAlltoAll(
        sendbuff: *const ::core::ffi::c_void,
        recvbuff: *mut ::core::ffi::c_void,
        count: size_t,
        datatype: ncclDataType_t,
        comm: ncclComm_t,
        stream: cudaStream_t,
    ) -> ncclResult_t;
}
unsafe extern "C" {
    pub fn ncclGather(
        sendbuff: *const ::core::ffi::c_void,
        recvbuff: *mut ::core::ffi::c_void,
        count: size_t,
        datatype: ncclDataType_t,
        root: ::core::ffi::c_int,
        comm: ncclComm_t,
        stream: cudaStream_t,
    ) -> ncclResult_t;
}
unsafe extern "C" {
    pub fn ncclScatter(
        sendbuff: *const ::core::ffi::c_void,
        recvbuff: *mut ::core::ffi::c_void,
        count: size_t,
        datatype: ncclDataType_t,
        root: ::core::ffi::c_int,
        comm: ncclComm_t,
        stream: cudaStream_t,
    ) -> ncclResult_t;
}
unsafe extern "C" {
    pub fn ncclSend(
        sendbuff: *const ::core::ffi::c_void,
        count: size_t,
        datatype: ncclDataType_t,
        peer: ::core::ffi::c_int,
        comm: ncclComm_t,
        stream: cudaStream_t,
    ) -> ncclResult_t;
}
unsafe extern "C" {
    pub fn ncclRecv(
        recvbuff: *mut ::core::ffi::c_void,
        count: size_t,
        datatype: ncclDataType_t,
        peer: ::core::ffi::c_int,
        comm: ncclComm_t,
        stream: cudaStream_t,
    ) -> ncclResult_t;
}
unsafe extern "C" {
    pub fn ncclGroupStart() -> ncclResult_t;
}
unsafe extern "C" {
    pub fn ncclGroupEnd() -> ncclResult_t;
}
unsafe extern "C" {
    pub fn ncclGroupSimulateEnd(simInfo: *mut ncclSimInfo_t) -> ncclResult_t;
}
