/* automatically generated by rust-bindgen 0.72.1 */

use crate::driver::CUresult;

unsafe extern "C" {
    pub fn cuProfilerStart() -> CUresult;
}
unsafe extern "C" {
    pub fn cuProfilerStop() -> CUresult;
}
