[package]
name = "singe-cublas-sys"
description = "Low-level FFI bindings for the NVIDIA cuBLAS dense linear algebra library."
version = "0.1.0-alpha.6"
edition.workspace = true
repository.workspace = true
license-file = "../LICENSE"
readme = "README.md"
keywords = ["cuda", "cublas", "bindings", "ffi"]
include.workspace = true

[package.metadata.docs.rs]
rustdoc-args = ["--html-in-header", "dist/katex_header.html"]

[features]
default = ["cublas_13_4"]

cublas_13_4 = ["singe-cuda-sys/runtime_13_2"]

[dependencies]
singe-cuda-sys.workspace = true
num_enum.workspace = true

[build-dependencies]
singe-cuda-find.workspace = true
anyhow.workspace = true
