[package]
name = "singe-cusolver"
description = "Safe Rust wrappers for the NVIDIA cuSOLVER dense and sparse solver library."
version = "0.1.0-alpha.7"
edition.workspace = true
repository.workspace = true
license-file = "../LICENSE"
readme = "README.md"
keywords = ["cuda", "nvidia", "cusolver", "solver"]
include.workspace = true

[package.metadata.docs.rs]
rustdoc-args = ["--html-in-header", "dist/katex_header.html"]

[features]
default = ["cusolver_12_2"]

cusolver_12_2 = [
    "singe-cuda/runtime_13_3",
    "singe-cuda-sys/runtime_13_3",
    "singe-cusolver-sys/cusolver_12_2",
]

testing = ["singe-cuda/testing"]

[dependencies]
singe-core.workspace = true
singe-cuda.workspace = true
singe-cuda-sys.workspace = true
singe-cusolver-sys.workspace = true
thiserror.workspace = true
num_enum.workspace = true
bitflags.workspace = true
