use std::{collections::BTreeSet, fs, path::Path};

use anyhow::{Context, Result, bail};
use proc_macro2::{Ident, TokenStream};
use quote::{format_ident, quote};
use syn::{BinOp, Expr, ExprBinary, ExprCall, ExprPath, UnOp};
use toml_edit::{DocumentMut, Item, Value};

use crate::utility::{workspace_root, write_generated_file};

pub fn generate_cutile_fused() -> Result<()> {
    let root = workspace_root()?;
    let recipe_path = root.join("singe-kernel/config/fused.toml");
    let output_path = root.join("singe-kernel/src/-generated/cutile/fused.rs");
    let recipes = parse_recipes(&recipe_path)?;
    let contents = render_module(&recipes)?;
    write_generated_file(&output_path, &contents)?;
    Ok(())
}

#[derive(Clone, Debug)]
struct Recipe {
    name: String,
    category: String,
    dtypes: Vec<String>,
    ranks: Vec<String>,
    inputs: Vec<String>,
    expr: String,
}

#[derive(Clone, Copy)]
struct DtypeConfig {
    rust: &'static str,
    compute: &'static str,
    zero: &'static str,
    one: &'static str,
    half: &'static str,
    third: &'static str,
    three: &'static str,
    six: &'static str,
    ln_10: &'static str,
    pi: &'static str,
    one_eighty: &'static str,
    sqrt_2_over_pi: &'static str,
    cubic_coeff: &'static str,
    selu_alpha: &'static str,
    selu_scale: &'static str,
}

#[derive(Clone, Copy)]
struct Shape {
    rust: &'static str,
}

fn parse_recipes(path: &Path) -> Result<Vec<Recipe>> {
    let contents =
        fs::read_to_string(path).with_context(|| format!("failed to read {}", path.display()))?;
    let document = contents
        .parse::<DocumentMut>()
        .with_context(|| format!("failed to parse {}", path.display()))?;
    let kernels = document
        .get("kernel")
        .and_then(Item::as_array_of_tables)
        .context("fused.toml is missing [[kernel]] tables")?;

    kernels
        .iter()
        .enumerate()
        .map(|(index, table)| {
            let name = required_str(table.get("name"), index, "name")?;
            let category = required_str(table.get("category"), index, "category")?;
            let dtypes = required_str_array(table.get("dtypes"), index, "dtypes")?;
            let ranks = required_str_array(table.get("ranks"), index, "ranks")?;
            let inputs = required_str_array(table.get("inputs"), index, "inputs")?;
            let expr = required_str(table.get("expr"), index, "expr")?;
            Ok(Recipe {
                name,
                category,
                dtypes,
                ranks,
                inputs,
                expr,
            })
        })
        .collect()
}

fn required_str(item: Option<&Item>, index: usize, key: &str) -> Result<String> {
    item.and_then(Item::as_value)
        .and_then(Value::as_str)
        .map(str::to_string)
        .with_context(|| format!("kernel[{index}] is missing string field `{key}`"))
}

fn required_str_array(item: Option<&Item>, index: usize, key: &str) -> Result<Vec<String>> {
    let array = item
        .and_then(Item::as_value)
        .and_then(Value::as_array)
        .with_context(|| format!("kernel[{index}] is missing array field `{key}`"))?;
    array
        .iter()
        .map(|value| {
            value
                .as_str()
                .map(str::to_string)
                .with_context(|| format!("kernel[{index}].{key} contains a non-string value"))
        })
        .collect()
}

fn render_module(recipes: &[Recipe]) -> Result<String> {
    let mut entries = Vec::new();
    for recipe in recipes {
        if recipe.category != "pointwise" {
            bail!("unsupported fused category: {}", recipe.category);
        }
        for dtype in &recipe.dtypes {
            for rank in &recipe.ranks {
                entries.push(emit_entry(recipe, dtype, rank)?);
            }
        }
    }

    let tokens = quote! {
        #![allow(unused_parens)]
        #![allow(unused_variables)]

        #[cutile::module]
        mod kernels {
            use cutile::core::*;

            #(#entries)*
        }

        pub use kernels::*;
    };
    let parsed =
        syn::parse2::<syn::File>(tokens).context("generated cutile fused module did not parse")?;
    let mut formatted = prettyplease::unparse(&parsed);
    let marker = "\n#[cutile::module]";
    let generated = "\n// @generated by `cargo xtask gen-cutile-fused`\n// Do not edit generated entries manually.\n";
    if let Some(index) = formatted.find(marker) {
        formatted.insert_str(index, generated);
    } else {
        bail!("generated cutile fused module is missing cutile module marker");
    }
    Ok(formatted)
}

fn emit_entry(recipe: &Recipe, dtype: &str, rank: &str) -> Result<TokenStream> {
    let shape = shape(rank)?;
    let cfg = dtype_config(dtype)?;
    let dtype_feature = format!("dtype-{dtype}");
    let expr = parse_expr(&recipe.expr, &recipe.inputs)?;
    let suffix = if matches!(rank, "1d" | "2d_bias" | "2d_affine" | "2d_columns2") {
        ""
    } else {
        "_2d"
    };
    let name = format_ident!("{}{}_{}", recipe.name, suffix, dtype);

    let args = entry_args(&recipe.inputs, cfg.rust, rank)?;
    let prelude = entry_prelude(rank)?;
    let loads = recipe
        .inputs
        .iter()
        .map(|input| load_input(input, cfg, shape, rank))
        .collect::<Result<Vec<_>>>()?;
    let value = emit_expr(&expr, cfg, shape)?;
    let rust_ty = ty(cfg.rust)?;
    let compute_ty = ty(cfg.compute)?;
    let shape = tokens(shape.rust)?;
    let store = if cfg.rust == cfg.compute {
        quote! {
            let value: Tile<#rust_ty, #shape> = #value;
            out.store(value);
        }
    } else {
        quote! {
            let value: Tile<#compute_ty, #shape> = #value;
            let value: Tile<#rust_ty, #shape> = convert_tile(value);
            out.store(value);
        }
    };

    Ok(quote! {
        #[cfg(feature = #dtype_feature)]
        #[cutile::entry()]
        pub fn #name<const B: i32>(
            #(#args),*
        ) {
            #prelude
            #(#loads)*
            #store
        }
    })
}

fn entry_args(inputs: &[String], rust: &str, rank: &str) -> Result<Vec<TokenStream>> {
    let rust_ty = ty(rust)?;
    let out_shape = tokens(shape(rank)?.rust)?;
    let mut args = vec![quote!(out: &mut Tensor<#rust_ty, #out_shape>)];
    match rank {
        "1d" => {
            args.extend(inputs.iter().map(|input| {
                let input = ident(input);
                if input == format_ident!("condition") {
                    quote!(#input: &Tensor<u8, { [-1] }>)
                } else {
                    quote!(#input: &Tensor<#rust_ty, { [-1] }>)
                }
            }));
        }
        "2d" => {
            args.extend(inputs.iter().map(|input| {
                let input = ident(input);
                if input == format_ident!("condition") {
                    quote!(#input: &Tensor<u8, { [-1, -1] }>)
                } else {
                    quote!(#input: &Tensor<#rust_ty, { [-1, -1] }>)
                }
            }));
        }
        "2d_bias" => {
            if inputs.len() != 2 {
                bail!("2d_bias kernels require exactly two inputs");
            }
            let first = ident(&inputs[0]);
            let second = ident(&inputs[1]);
            args.push(quote!(#first: &Tensor<#rust_ty, { [-1, -1] }>));
            args.push(quote!(#second: &Tensor<#rust_ty, { [-1] }>));
        }
        "2d_affine" | "2d_columns2" => {
            let Some((first, rest)) = inputs.split_first() else {
                bail!("{rank} kernels require at least one input");
            };
            let first = ident(first);
            args.push(quote!(#first: &Tensor<#rust_ty, { [-1, -1] }>));
            args.extend(rest.iter().map(|input| {
                let input = ident(input);
                quote!(#input: &Tensor<#rust_ty, { [-1] }>)
            }));
        }
        _ => bail!("unsupported rank: {rank}"),
    }
    Ok(args)
}

fn entry_prelude(rank: &str) -> Result<TokenStream> {
    match rank {
        "1d" => Ok(quote! {
            let shape = out.shape();
        }),
        "2d" | "2d_bias" | "2d_affine" | "2d_columns2" => Ok(quote! {
            let pid: (i32, i32, i32) = get_tile_block_id();
            let row = pid.0;
            let col = pid.1;
            let shape = out.shape();
        }),
        _ => bail!("unsupported rank: {rank}"),
    }
}

fn load_input(name: &str, cfg: DtypeConfig, shape: Shape, rank: &str) -> Result<TokenStream> {
    let is_condition = name == "condition";
    let is_bias = name == "bias";
    let is_x = name == "x";
    let name = ident(name);
    let raw = format_ident!("{name}_raw");
    let part = format_ident!("{name}_part");
    let zero = format_ident!("{name}_zero");
    let rust_ty = ty(cfg.rust)?;
    let compute_ty = ty(cfg.compute)?;
    let shape = tokens(shape.rust)?;

    if is_condition {
        let source = match rank {
            "1d" => quote! {
                let #raw: Tile<u8, #shape> = load_tile_like(#name, out);
            },
            "2d" => quote! {
                let #part: Partition<u8, #shape> = #name.partition(const_shape![1, B]);
                let #raw: Tile<u8, #shape> = #part.load([row, col]);
            },
            _ => bail!("unsupported condition rank: {rank}"),
        };
        return Ok(quote! {
            #source
            let #zero: Tile<u8, #shape> = constant(0u8, shape);
            let #name: Tile<bool, #shape> = cmpi(#raw, #zero, predicate::NotEqual);
        });
    }

    let source = match rank {
        "1d" => quote! {
            let #raw: Tile<#rust_ty, #shape> = load_tile_like(#name, out);
        },
        "2d" | "2d_bias" if rank == "2d" || !is_bias => quote! {
            let #part: Partition<#rust_ty, #shape> = #name.partition(const_shape![1, B]);
            let #raw: Tile<#rust_ty, #shape> = #part.load([row, col]);
        },
        "2d_bias" => quote! {
            let #part: Partition<#rust_ty, { [B] }> = #name.partition(const_shape![B]);
            let #raw: Tile<#rust_ty, { [B] }> = #part.load([col]);
            let #raw: Tile<#rust_ty, #shape> = #raw.reshape(const_shape![1, B]);
        },
        "2d_affine" | "2d_columns2" if is_x => quote! {
            let #part: Partition<#rust_ty, #shape> = #name.partition(const_shape![1, B]);
            let #raw: Tile<#rust_ty, #shape> = #part.load([row, col]);
        },
        "2d_affine" | "2d_columns2" => quote! {
            let #part: Partition<#rust_ty, { [B] }> = #name.partition(const_shape![B]);
            let #raw: Tile<#rust_ty, { [B] }> = #part.load([col]);
            let #raw: Tile<#rust_ty, #shape> = #raw.reshape(const_shape![1, B]);
        },
        _ => bail!("unsupported rank: {rank}"),
    };

    if cfg.rust == cfg.compute {
        Ok(quote! {
            #source
            let #name: Tile<#compute_ty, #shape> = #raw;
        })
    } else {
        Ok(quote! {
            #source
            let #name: Tile<#compute_ty, #shape> = convert_tile(#raw);
        })
    }
}

fn parse_expr(expr: &str, inputs: &[String]) -> Result<Expr> {
    let expr = expr.replace("where(", "where_(");
    let parsed = syn::parse_str::<Expr>(&expr)
        .with_context(|| format!("failed to parse fused expression `{expr}`"))?;
    let inputs = inputs.iter().map(String::as_str).collect::<BTreeSet<_>>();
    validate_expr(&parsed, &inputs)?;
    Ok(parsed)
}

fn validate_expr(expr: &Expr, inputs: &BTreeSet<&str>) -> Result<()> {
    match expr {
        Expr::Path(path) => {
            let name = path_ident(path)?;
            if !inputs.contains(name.as_str()) {
                bail!("unknown input in fused expression: {name}");
            }
        }
        Expr::Binary(binary) => {
            if !matches!(
                binary.op,
                BinOp::Add(_) | BinOp::Sub(_) | BinOp::Mul(_) | BinOp::Div(_)
            ) {
                bail!("unsupported binary op in fused expression");
            }
            validate_expr(&binary.left, inputs)?;
            validate_expr(&binary.right, inputs)?;
        }
        Expr::Unary(unary) => {
            if !matches!(unary.op, UnOp::Neg(_)) {
                bail!("unsupported unary op in fused expression");
            }
            validate_expr(&unary.expr, inputs)?;
        }
        Expr::Call(call) => {
            let name = call_ident(call)?;
            match name.as_str() {
                "where_" => {
                    if call.args.len() != 3 {
                        bail!("where expects three arguments");
                    }
                }
                "min" | "max" => {
                    if call.args.len() != 2 {
                        bail!("{name} expects two arguments");
                    }
                }
                _ if is_unary_op(&name) => {
                    if call.args.len() != 1 {
                        bail!("fused op expects one argument: {name}");
                    }
                }
                _ => bail!("unsupported fused op: {name}"),
            }
            for arg in &call.args {
                validate_expr(arg, inputs)?;
            }
        }
        Expr::Paren(paren) => validate_expr(&paren.expr, inputs)?,
        _ => bail!("unsupported fused expression node"),
    }
    Ok(())
}

fn emit_expr(expr: &Expr, cfg: DtypeConfig, shape: Shape) -> Result<TokenStream> {
    match expr {
        Expr::Path(path) => {
            let ident = ident(&path_ident(path)?);
            Ok(quote!(#ident))
        }
        Expr::Paren(paren) => emit_expr(&paren.expr, cfg, shape),
        Expr::Binary(binary) => emit_binary_expr(binary, cfg, shape),
        Expr::Unary(unary) => {
            if !matches!(unary.op, UnOp::Neg(_)) {
                bail!("unsupported unary op in fused expression");
            }
            let arg = emit_expr(&unary.expr, cfg, shape)?;
            let zero = constant(cfg.zero, cfg, shape)?;
            Ok(quote!((#zero - #arg)))
        }
        Expr::Call(call) => emit_call_expr(call, cfg, shape),
        _ => bail!("unsupported fused expression node"),
    }
}

fn emit_binary_expr(binary: &ExprBinary, cfg: DtypeConfig, shape: Shape) -> Result<TokenStream> {
    let left = emit_expr(&binary.left, cfg, shape)?;
    let right = emit_expr(&binary.right, cfg, shape)?;
    match binary.op {
        BinOp::Add(_) => Ok(quote!((#left + #right))),
        BinOp::Sub(_) => Ok(quote!((#left - #right))),
        BinOp::Mul(_) => Ok(quote!((#left * #right))),
        BinOp::Div(_) => Ok(quote!((#left / #right))),
        _ => bail!("unsupported binary op in fused expression"),
    }
}

fn emit_call_expr(call: &ExprCall, cfg: DtypeConfig, shape: Shape) -> Result<TokenStream> {
    let name = call_ident(call)?;
    if name == "where_" {
        let condition = emit_expr(&call.args[0], cfg, shape)?;
        let true_value = emit_expr(&call.args[1], cfg, shape)?;
        let false_value = emit_expr(&call.args[2], cfg, shape)?;
        return Ok(quote!(select(#condition, #true_value, #false_value)));
    }
    if matches!(name.as_str(), "min" | "max") {
        let left = emit_expr(&call.args[0], cfg, shape)?;
        let right = emit_expr(&call.args[1], cfg, shape)?;
        let predicate = if name == "min" {
            format_ident!("LessThan")
        } else {
            format_ident!("GreaterThan")
        };
        let mask = quote!(cmpf(#left, #right, predicate::#predicate, cmp_ordering::Ordered));
        return Ok(quote!(select(#mask, #left, #right)));
    }

    let arg = emit_expr(&call.args[0], cfg, shape)?;
    let zero = constant(cfg.zero, cfg, shape)?;
    let one = constant(cfg.one, cfg, shape)?;
    let half = constant(cfg.half, cfg, shape)?;
    let third = constant(cfg.third, cfg, shape)?;
    let three = constant(cfg.three, cfg, shape)?;
    let six = constant(cfg.six, cfg, shape)?;
    let expression = match name.as_str() {
        "neg" => quote!((#zero - #arg)),
        "abs" => quote!(absf(#arg)),
        "relu" => {
            let mask = quote!(cmpf(#arg, #zero, predicate::GreaterThan, cmp_ordering::Ordered));
            quote!(select(#mask, #arg, #zero))
        }
        "relu6" => {
            let positive_mask =
                quote!(cmpf(#arg, #zero, predicate::GreaterThan, cmp_ordering::Ordered));
            let relu = quote!(select(#positive_mask, #arg, #zero));
            let six_mask = quote!(cmpf(#relu, #six, predicate::LessThan, cmp_ordering::Ordered));
            quote!(select(#six_mask, #relu, #six))
        }
        "hard_sigmoid" => quote!(min_tile(max_tile((#arg + #three) / #six, #zero), #one)),
        "hard_swish" => {
            let hard_sigmoid = quote!(min_tile(max_tile((#arg + #three) / #six, #zero), #one));
            quote!((#arg * #hard_sigmoid))
        }
        "sigmoid" => quote!((#one / (#one + exp(#zero - #arg)))),
        "silu" => quote!((#arg * (#one / (#one + exp(#zero - #arg))))),
        "gelu" => {
            let sqrt_2_over_pi = constant(cfg.sqrt_2_over_pi, cfg, shape)?;
            let cubic_coeff = constant(cfg.cubic_coeff, cfg, shape)?;
            quote!((#half
                * #arg
                * (#one + tanh(#sqrt_2_over_pi * (#arg + #cubic_coeff * #arg * #arg * #arg)))))
        }
        "mish" => {
            let softplus = quote!((max_tile(#arg, #zero) + log(#one + exp(#zero - absf(#arg)))));
            quote!((#arg * tanh(#softplus)))
        }
        "selu" => {
            let selu_alpha = constant(cfg.selu_alpha, cfg, shape)?;
            let selu_scale = constant(cfg.selu_scale, cfg, shape)?;
            let positive =
                quote!(cmpf(#arg, #zero, predicate::GreaterThanOrEqual, cmp_ordering::Ordered));
            quote!((#selu_scale * select(#positive, #arg, #selu_alpha * (exp(#arg) - #one))))
        }
        "reciprocal" => quote!((#one / #arg)),
        "square" => quote!((#arg * #arg)),
        "ceil" => quote!(ceil(#arg)),
        "floor" => quote!(floor(#arg)),
        "trunc" => {
            let positive =
                quote!(cmpf(#arg, #zero, predicate::GreaterThanOrEqual, cmp_ordering::Ordered));
            quote!(select(#positive, floor(#arg), ceil(#arg)))
        }
        "frac" => {
            let positive =
                quote!(cmpf(#arg, #zero, predicate::GreaterThanOrEqual, cmp_ordering::Ordered));
            let truncated = quote!(select(#positive, floor(#arg), ceil(#arg)));
            quote!((#arg - #truncated))
        }
        "deg2rad" => {
            let pi = constant(cfg.pi, cfg, shape)?;
            let one_eighty = constant(cfg.one_eighty, cfg, shape)?;
            quote!((#arg * #pi / #one_eighty))
        }
        "rad2deg" => {
            let one_eighty = constant(cfg.one_eighty, cfg, shape)?;
            let pi = constant(cfg.pi, cfg, shape)?;
            quote!((#arg * #one_eighty / #pi))
        }
        "sin" => quote!(sin(#arg)),
        "cos" => quote!(cos(#arg)),
        "tan" => quote!(tan(#arg)),
        "asin" => {
            quote!(atan2(
                #arg,
                sqrt(#one - #arg * #arg, rounding::NearestEven, ftz::Disabled)
            ))
        }
        "acos" => {
            quote!(atan2(
                sqrt(#one - #arg * #arg, rounding::NearestEven, ftz::Disabled),
                #arg
            ))
        }
        "atan" => quote!(atan2(#arg, #one)),
        "sinh" => quote!(sinh(#arg)),
        "cosh" => quote!(cosh(#arg)),
        "asinh" => {
            quote!(log(
                #arg + sqrt(#arg * #arg + #one, rounding::NearestEven, ftz::Disabled)
            ))
        }
        "acosh" => {
            quote!(log(
                #arg + sqrt(#arg * #arg - #one, rounding::NearestEven, ftz::Disabled)
            ))
        }
        "atanh" => quote!((#half * log((#one + #arg) / (#one - #arg)))),
        "sqrt" => quote!(sqrt(#arg, rounding::NearestEven, ftz::Disabled)),
        "rsqrt" => quote!(rsqrt(#arg, ftz::Disabled)),
        "cbrt" => {
            let root = quote!(pow(absf(#arg), #third));
            let negative = quote!(cmpf(#arg, #zero, predicate::LessThan, cmp_ordering::Ordered));
            quote!(select(#negative, #zero - #root, #root))
        }
        "exp" => quote!(exp(#arg)),
        "exp2" => quote!(exp2(#arg, ftz::Disabled)),
        "expm1" => quote!((exp(#arg) - #one)),
        "log" => quote!(log(#arg)),
        "log2" => quote!(log2(#arg)),
        "log10" => {
            let ln_10 = constant(cfg.ln_10, cfg, shape)?;
            quote!((log(#arg) / #ln_10))
        }
        "log1p" => quote!(log(#one + #arg)),
        "softplus" => {
            quote!((max_tile(#arg, #zero) + log(#one + exp(#zero - absf(#arg)))))
        }
        "softsign" => quote!((#arg / (#one + absf(#arg)))),
        "tanh" => quote!(tanh(#arg)),
        "tanhshrink" => quote!((#arg - tanh(#arg))),
        "log_sigmoid" => {
            let neg = quote!((#zero - #arg));
            let softplus_neg =
                quote!((max_tile(#neg, #zero) + log(#one + exp(#zero - absf(#neg)))));
            quote!((#zero - #softplus_neg))
        }
        _ => bail!("unsupported fused op: {name}"),
    };
    Ok(expression)
}

fn path_ident(path: &ExprPath) -> Result<String> {
    path.path
        .get_ident()
        .map(|ident| ident.to_string())
        .ok_or_else(|| anyhow::anyhow!("only direct fused expression paths are supported"))
}

fn call_ident(call: &ExprCall) -> Result<String> {
    let Expr::Path(path) = call.func.as_ref() else {
        bail!("only direct fused expression calls are supported");
    };
    path_ident(path)
}

fn ident(name: &str) -> Ident {
    format_ident!("{name}")
}

fn ty(value: &str) -> Result<syn::Type> {
    syn::parse_str(value).with_context(|| format!("failed to parse fused type `{value}`"))
}

fn tokens(value: &str) -> Result<TokenStream> {
    value
        .parse()
        .map_err(|error| anyhow::anyhow!("failed to parse fused tokens `{value}`: {error}"))
}

fn constant(value: &str, cfg: DtypeConfig, shape: Shape) -> Result<TokenStream> {
    let value = syn::parse_str::<Expr>(value)
        .with_context(|| format!("failed to parse fused constant `{value}`"))?;
    let compute_ty = ty(cfg.compute)?;
    let shape = tokens(shape.rust)?;
    Ok(quote!({
        let value: Tile<#compute_ty, #shape> = constant(#value, shape);
        value
    }))
}

fn is_unary_op(name: &str) -> bool {
    matches!(
        name,
        "neg"
            | "abs"
            | "relu"
            | "relu6"
            | "hard_sigmoid"
            | "hard_swish"
            | "sigmoid"
            | "silu"
            | "gelu"
            | "mish"
            | "selu"
            | "reciprocal"
            | "square"
            | "ceil"
            | "floor"
            | "trunc"
            | "frac"
            | "deg2rad"
            | "rad2deg"
            | "sin"
            | "cos"
            | "tan"
            | "asin"
            | "acos"
            | "atan"
            | "sinh"
            | "cosh"
            | "asinh"
            | "acosh"
            | "atanh"
            | "sqrt"
            | "rsqrt"
            | "cbrt"
            | "exp"
            | "exp2"
            | "expm1"
            | "log"
            | "log2"
            | "log10"
            | "log1p"
            | "softplus"
            | "softsign"
            | "tanh"
            | "tanhshrink"
            | "log_sigmoid"
    )
}

fn dtype_config(dtype: &str) -> Result<DtypeConfig> {
    match dtype {
        "bf16" => Ok(DtypeConfig {
            rust: "bf16",
            compute: "f32",
            zero: "0.0f32",
            one: "1.0f32",
            half: "0.5f32",
            third: "0.33333334f32",
            three: "3.0f32",
            six: "6.0f32",
            ln_10: "std::f32::consts::LN_10",
            pi: "std::f32::consts::PI",
            one_eighty: "180.0f32",
            sqrt_2_over_pi: "0.797_884_6f32",
            cubic_coeff: "0.044715f32",
            selu_alpha: "1.6732632f32",
            selu_scale: "1.050701f32",
        }),
        "f16" => Ok(DtypeConfig {
            rust: "f16",
            compute: "f32",
            zero: "0.0f32",
            one: "1.0f32",
            half: "0.5f32",
            third: "0.33333334f32",
            three: "3.0f32",
            six: "6.0f32",
            ln_10: "std::f32::consts::LN_10",
            pi: "std::f32::consts::PI",
            one_eighty: "180.0f32",
            sqrt_2_over_pi: "0.797_884_6f32",
            cubic_coeff: "0.044715f32",
            selu_alpha: "1.6732632f32",
            selu_scale: "1.050701f32",
        }),
        "f32" => Ok(DtypeConfig {
            rust: "f32",
            compute: "f32",
            zero: "0.0f32",
            one: "1.0f32",
            half: "0.5f32",
            third: "0.33333334f32",
            three: "3.0f32",
            six: "6.0f32",
            ln_10: "std::f32::consts::LN_10",
            pi: "std::f32::consts::PI",
            one_eighty: "180.0f32",
            sqrt_2_over_pi: "0.797_884_6f32",
            cubic_coeff: "0.044715f32",
            selu_alpha: "1.6732632f32",
            selu_scale: "1.050701f32",
        }),
        "f64" => Ok(DtypeConfig {
            rust: "f64",
            compute: "f64",
            zero: "0.0f64",
            one: "1.0f64",
            half: "0.5f64",
            third: "0.3333333333333333f64",
            three: "3.0f64",
            six: "6.0f64",
            ln_10: "std::f64::consts::LN_10",
            pi: "std::f64::consts::PI",
            one_eighty: "180.0f64",
            sqrt_2_over_pi: "0.7978845608028654f64",
            cubic_coeff: "0.044715f64",
            selu_alpha: "1.6732632423543772f64",
            selu_scale: "1.0507009873554805f64",
        }),
        _ => bail!("unsupported dtype: {dtype}"),
    }
}

fn shape(rank: &str) -> Result<Shape> {
    match rank {
        "1d" => Ok(Shape { rust: "{ [B] }" }),
        "2d" | "2d_bias" | "2d_affine" | "2d_columns2" => Ok(Shape { rust: "{ [1, B] }" }),
        _ => bail!("unsupported rank: {rank}"),
    }
}
