use std::{collections::HashSet, fs, path::Path};

use anyhow::Result;
use proc_macro2::{Ident, TokenStream};
use quote::{format_ident, quote};
use syn::{Expr, Item, ItemMod, Type};

use crate::utility::{workspace_root, write_generated_file};

pub fn generate_cutile_dtype_kernels() -> Result<()> {
    let root = workspace_root()?;
    for &dtype in DTYPES {
        let dir = root.join(format!("singe-kernel/src/-generated/cutile/{}", dtype.name));
        update_dtype_files(&dir, dtype)?;
    }
    Ok(())
}

#[derive(Clone, Copy)]
struct Dtype {
    name: &'static str,
    zero: &'static str,
    one: &'static str,
    low_i8: &'static str,
    high_i8: &'static str,
    low_u8: &'static str,
    high_u8: &'static str,
    quantize_ties_to_even: bool,
}

const DTYPES: &[Dtype] = &[
    Dtype {
        name: "f16",
        zero: "f16::from_f32(0.0)",
        one: "f16::from_f32(1.0)",
        low_i8: "f16::from_f32(-128.0)",
        high_i8: "f16::from_f32(127.0)",
        low_u8: "f16::from_f32(0.0)",
        high_u8: "f16::from_f32(255.0)",
        quantize_ties_to_even: false,
    },
    Dtype {
        name: "f32",
        zero: "0.0f32",
        one: "1.0f32",
        low_i8: "-128.0f32",
        high_i8: "127.0f32",
        low_u8: "0.0f32",
        high_u8: "255.0f32",
        quantize_ties_to_even: true,
    },
    Dtype {
        name: "f64",
        zero: "0.0f64",
        one: "1.0f64",
        low_i8: "-128.0f64",
        high_i8: "127.0f64",
        low_u8: "0.0f64",
        high_u8: "255.0f64",
        quantize_ties_to_even: false,
    },
];

fn update_dtype_files(dir: &Path, dtype: Dtype) -> Result<()> {
    let mut elementwise = render_elementwise_entries(dtype);
    elementwise.push_str(&render_selection_entries(dtype));
    let mut reduction = render_reduction_entries(dtype);
    reduction.push_str(&render_arg_reduction_entries(dtype));
    write_generated_file(
        &dir.join("elementwise.rs"),
        render_kernel_file(
            dtype,
            elementwise,
            &["binary_store", "cmp_store", "cmp_bool_store"],
            &[],
        )?,
    )?;
    write_generated_file(
        &dir.join("cast.rs"),
        render_kernel_file(dtype, render_cast_entries(dtype), &[], &[])?,
    )?;
    write_generated_file(
        &dir.join("quantization.rs"),
        render_kernel_file(
            dtype,
            render_quantization_entries(dtype),
            &[],
            quantization_utility_exports(dtype),
        )?,
    )?;
    write_generated_file(
        &dir.join("activation.rs"),
        render_kernel_file(
            dtype,
            render_activation_entries(dtype),
            &["activation_unary_store"],
            &[],
        )?,
    )?;
    write_generated_file(
        &dir.join("unary.rs"),
        render_kernel_file(
            dtype,
            render_unary_entries(dtype),
            &["unary_store", "nan_to_num_store", "unary_bool_store"],
            &[],
        )?,
    )?;
    write_generated_file(
        &dir.join("scalar.rs"),
        render_kernel_file(
            dtype,
            render_scalar_entries(dtype),
            &["scalar_store", "scalar_cmp_bool_store"],
            &[],
        )?,
    )?;
    write_generated_file(
        &dir.join("softmax.rs"),
        render_kernel_file(
            dtype,
            render_softmax_entries(dtype),
            &["softmax_impl"],
            softmax_utility_exports(dtype),
        )?,
    )?;
    write_generated_file(
        &dir.join("reduction.rs"),
        render_kernel_file(dtype, reduction, &["reduce_impl", "arg_reduce_impl"], &[])?,
    )?;
    Ok(())
}

fn render_kernel_file(
    dtype: Dtype,
    entries: String,
    utility_helpers: &[&str],
    utility_exports: &[&str],
) -> Result<String> {
    let utility_path = syn::parse_str::<syn::Path>(&format!(
        "crate::cuda::cutile::kernel::{}::utility",
        dtype.name
    ))
    .expect("generated utility path must parse");
    let entry_items = syn::parse_file(&entries)
        .expect("generated cutile dtype entries must parse")
        .items;
    let mut module_items: Vec<Item> = Vec::new();
    module_items.push(syn::parse_quote!(
        use cutile::core::*;
    ));
    module_items.extend(extract_utility_helpers(dtype, utility_helpers)?);
    module_items.extend(entry_items);
    let utility_exports = utility_exports.iter().map(|export| {
        let export = format_ident!("{export}");
        quote!(pub use #utility_path::#export;)
    });
    let file = syn::parse2::<syn::File>(quote! {
        #[cutile::module]
        mod kernels {
            #(#module_items)*
        }

        pub use kernels::*;
        #(#utility_exports)*
    })
    .expect("generated cutile dtype file must parse");
    Ok(format!(
        "// @generated by cargo xtask gen-cutile-dtype-kernels\n\
         // Do not edit generated entries by hand.\n\n\
         {}",
        prettyplease::unparse(&file)
    ))
}

// We need this because cutile needs helper alongside kernels.
fn extract_utility_helpers(dtype: Dtype, helper_names: &[&str]) -> Result<Vec<Item>> {
    if helper_names.is_empty() {
        return Ok(Vec::new());
    }

    let root = workspace_root()?;
    let path = root.join(format!(
        "singe-kernel/src/cuda/cutile/kernel/{}/utility.rs",
        dtype.name
    ));
    let source = fs::read_to_string(&path)?;
    let file = syn::parse_file(&source)?;
    let names: HashSet<&str> = helper_names.iter().copied().collect();
    let module = file
        .items
        .into_iter()
        .find_map(|item| match item {
            Item::Mod(module) if module.ident == "kernels" => Some(module),
            _ => None,
        })
        .expect("cutile dtype utility file must contain kernels module");
    let items = module_items(module)
        .into_iter()
        .filter(|item| match item {
            Item::Fn(function) => names.contains(function.sig.ident.to_string().as_str()),
            _ => false,
        })
        .collect::<Vec<_>>();
    assert_eq!(
        items.len(),
        names.len(),
        "cutile dtype utility file is missing requested helpers"
    );
    Ok(items)
}

fn module_items(module: ItemMod) -> Vec<Item> {
    module
        .content
        .expect("cutile dtype utility kernels module must be inline")
        .1
}

fn quantization_utility_exports(dtype: Dtype) -> &'static [&'static str] {
    match dtype.name {
        "f16" => &["dequantize_u8_f16", "dequantize_i8_f16"],
        "f32" => &[
            "dequantize_u8_f32",
            "dequantize_i8_f32",
            "dequantize_u8_f32_grouped",
            "dequantize_i8_f32_grouped",
            "per_token_group_quant_i8_f32",
            "per_token_group_quant_i8_f32_column_major_scales",
            "per_token_group_quant_i8_f32_column_major_ue8m0_scales",
            "per_token_group_quant_f8e4m3_f32",
            "per_token_group_quant_f8e4m3_f32_column_major_scales",
            "per_token_group_quant_f8e4m3_f32_column_major_ue8m0_scales",
            "rope_quantize_f8e4m3_f32_interleaved",
            "qk_rope_quantize_f8e4m3_f32_interleaved_single_kernel",
            "qk_rope_quantize_f8e4m3_f32_interleaved_rope_only",
            "quantize_f32_f8e4m3_scaled",
            "matmul_i8_i8_f32",
            "matmul_f32_i8_dequantize_f32",
            "matmul_f8e4m3_f8e4m3_block_scaled_f32",
            "matmul_f8e4m3_f8e4m3_block_scaled_f16",
            "matmul_f8e4m3_f8e4m3_block_scaled_bf16",
            "quantize_f32_f8e4m3_block",
            "dequantize_f8e4m3_f32_block",
        ],
        "f64" => &["dequantize_u8_f64", "dequantize_i8_f64"],
        _ => unreachable!("unknown dtype {}", dtype.name),
    }
}

fn softmax_utility_exports(dtype: Dtype) -> &'static [&'static str] {
    match dtype.name {
        "f16" => &["softmax_lse_f16"],
        "f32" => &["softmax_lse_f32"],
        "f64" => &["softmax_lse_f64"],
        _ => unreachable!("unknown dtype {}", dtype.name),
    }
}

fn render_items(tokens: TokenStream) -> String {
    let file = syn::parse2::<syn::File>(tokens).expect("generated cutile dtype items must parse");
    prettyplease::unparse(&file)
        .lines()
        .map(|line| format!("    {line}\n"))
        .collect()
}

fn ty(value: &str) -> Type {
    syn::parse_str(value).expect("generated type must parse")
}

fn expr(value: &str) -> Expr {
    syn::parse_str(value).expect("generated expression must parse")
}

fn helper(name: &str) -> Ident {
    format_ident!("{name}")
}

fn render_elementwise_entries(dtype: Dtype) -> String {
    let mut out = String::new();
    for (name, op) in [("add", 0), ("sub", 1), ("mul", 2), ("div", 3), ("pow", 8)] {
        push_binary_entry(&mut out, dtype, name, "binary_store", op);
    }
    push_fma_entry(&mut out, dtype);
    for (name, op) in [
        ("maximum", 4),
        ("minimum", 5),
        ("atan2", 6),
        ("modulo", 7),
        ("hypot", 9),
        ("squared_difference", 10),
        ("logaddexp", 11),
        ("xlogy", 12),
    ] {
        push_binary_entry(&mut out, dtype, name, "binary_store", op);
    }
    for (name, op) in [
        ("equal", 0),
        ("not_equal", 1),
        ("less", 2),
        ("less_equal", 3),
        ("greater", 4),
        ("greater_equal", 5),
    ] {
        push_binary_entry(&mut out, dtype, name, "cmp_store", op);
    }
    for (name, op) in [
        ("equal_bool", 0),
        ("not_equal_bool", 1),
        ("less_bool", 2),
        ("less_equal_bool", 3),
        ("greater_bool", 4),
        ("greater_equal_bool", 5),
    ] {
        push_binary_bool_entry(&mut out, dtype, name, op);
    }
    out
}

fn render_cast_entries(dtype: Dtype) -> String {
    let mut out = String::new();
    if dtype.name == "f16" {
        push_bf16_to_f32_cast_entry(&mut out);
    }
    for target in ["f16", "f32", "f64"] {
        if target != dtype.name {
            push_float_cast_entry(&mut out, dtype, target);
        }
    }
    if dtype.name == "f32" {
        push_f32_to_bf16_cast_entry(&mut out);
    }
    for target in ["u32", "u8", "i8", "i32", "u64", "i64"] {
        push_float_to_int_cast_entry(&mut out, dtype, target);
    }
    push_bool_cast_entry(&mut out, dtype);
    for source in ["u32", "i32", "u64", "i64", "u8", "i8"] {
        push_int_to_float_cast_entry(&mut out, dtype, source);
    }
    push_float_to_bool_cast_entry(&mut out, dtype);
    out
}

fn render_quantization_entries(dtype: Dtype) -> String {
    let mut out = String::new();
    push_quantize_entry(&mut out, dtype, "u8", dtype.low_u8, dtype.high_u8);
    push_quantize_entry(&mut out, dtype, "i8", dtype.low_i8, dtype.high_i8);
    out
}

fn render_activation_entries(dtype: Dtype) -> String {
    let mut out = String::new();
    push_swiglu_entry(&mut out, dtype);
    for (name, op) in [
        ("relu", 23),
        ("relu6", 43),
        ("sigmoid", 24),
        ("silu", 25),
        ("gelu", 26),
        ("softplus", 34),
        ("hard_sigmoid", 35),
        ("hard_swish", 36),
        ("mish", 37),
        ("selu", 38),
        ("softsign", 39),
        ("tanhshrink", 44),
        ("log_sigmoid", 45),
    ] {
        push_unary_entry(&mut out, dtype, name, "activation_unary_store", op);
    }
    for name in ["leaky_relu", "elu", "celu", "hardshrink", "softshrink"] {
        push_unary_param_entry(&mut out, dtype, name, "alpha", false);
    }
    push_threshold_entry(&mut out, dtype);
    push_hardtanh_entry(&mut out, dtype);
    out
}

fn render_unary_entries(dtype: Dtype) -> String {
    let mut out = String::new();
    for (name, op) in [
        ("neg", 0),
        ("abs", 1),
        ("sqrt", 2),
        ("exp", 3),
        ("exp2", 30),
        ("log", 4),
        ("log2", 31),
        ("log10", 32),
        ("sin", 5),
        ("cos", 6),
        ("tan", 7),
        ("sinh", 8),
        ("cosh", 9),
        ("tanh", 10),
        ("asin", 11),
        ("acos", 12),
        ("atan", 13),
        ("ceil", 14),
        ("floor", 15),
        ("trunc", 16),
        ("frac", 42),
        ("reciprocal", 17),
        ("square", 18),
        ("rsqrt", 19),
        ("cbrt", 33),
        ("asinh", 20),
        ("acosh", 21),
        ("atanh", 22),
    ] {
        push_unary_entry(&mut out, dtype, name, "unary_store", op);
    }
    push_unary_entry(&mut out, dtype, "sign", "unary_store", 27);
    push_nan_to_num_entry(&mut out, dtype);
    for (name, op) in [
        ("log1p", 28),
        ("expm1", 29),
        ("deg2rad", 40),
        ("rad2deg", 41),
    ] {
        push_unary_entry(&mut out, dtype, name, "unary_store", op);
    }
    for (name, op) in [
        ("is_nan_bool", 0),
        ("is_inf_bool", 1),
        ("is_pos_inf_bool", 2),
        ("is_neg_inf_bool", 3),
        ("is_finite_bool", 4),
        ("is_normal_bool", 5),
        ("is_subnormal_bool", 10),
        ("is_zero_bool", 6),
        ("is_nonzero_bool", 9),
        ("is_positive_bool", 7),
        ("is_negative_bool", 8),
    ] {
        push_unary_bool_entry(&mut out, dtype, name, op);
    }
    out
}

fn render_scalar_entries(dtype: Dtype) -> String {
    let mut out = String::new();
    for (name, op) in [
        ("add_scalar", 0),
        ("sub_scalar", 1),
        ("rsub_scalar", 2),
        ("scale", 3),
        ("div_scalar", 4),
        ("rdiv_scalar", 5),
        ("modulo_scalar", 10),
        ("rmodulo_scalar", 11),
        ("atan2_scalar", 12),
        ("ratan2_scalar", 13),
        ("pow_scalar", 6),
        ("rpow_scalar", 7),
        ("hypot_scalar", 14),
        ("squared_difference_scalar", 15),
        ("logaddexp_scalar", 16),
        ("xlogy_scalar", 17),
        ("rxlogy_scalar", 18),
        ("min_scalar", 8),
        ("max_scalar", 9),
    ] {
        push_scalar_entry(&mut out, dtype, name, "scalar_store", op);
    }
    for (name, op) in [
        ("equal_scalar_bool", 0),
        ("not_equal_scalar_bool", 1),
        ("less_scalar_bool", 2),
        ("less_equal_scalar_bool", 3),
        ("greater_scalar_bool", 4),
        ("greater_equal_scalar_bool", 5),
    ] {
        push_scalar_bool_entry(&mut out, dtype, name, op);
    }
    out
}

fn render_selection_entries(dtype: Dtype) -> String {
    let ty = ty(dtype.name);
    let zero = expr(dtype.zero);
    let clamp = format_ident!("clamp_{}", dtype.name);
    let lerp = format_ident!("lerp_{}", dtype.name);
    let where_name = format_ident!("where_{}", dtype.name);
    let where_bool = format_ident!("where_bool_{}", dtype.name);
    let masked_fill = format_ident!("masked_fill_{}", dtype.name);
    render_items(quote! {
        #[cutile::entry()]
        pub fn #clamp<const B: i32>(
            out: &mut Tensor<#ty, { [B] }>,
            input: &Tensor<#ty, { [-1] }>,
            min_value: #ty,
            max_value: #ty,
        ) {
            let x: Tile<#ty, { [B] }> = load_tile_like(input, out);
            let min_value = broadcast_scalar(min_value, out.shape());
            let max_value = broadcast_scalar(max_value, out.shape());
            out.store(min_tile(max_tile(x, min_value), max_value));
        }

        #[cutile::entry()]
        pub fn #lerp<const B: i32>(
            out: &mut Tensor<#ty, { [B] }>,
            lhs: &Tensor<#ty, { [-1] }>,
            rhs: &Tensor<#ty, { [-1] }>,
            scalar: #ty,
        ) {
            let lhs_tile: Tile<#ty, { [B] }> = load_tile_like(lhs, out);
            let rhs_tile: Tile<#ty, { [B] }> = load_tile_like(rhs, out);
            let scalar = broadcast_scalar(scalar, out.shape());
            out.store(lhs_tile + scalar * (rhs_tile - lhs_tile));
        }

        #[cutile::entry()]
        pub fn #where_name<const B: i32>(
            out: &mut Tensor<#ty, { [B] }>,
            condition: &Tensor<#ty, { [-1] }>,
            x: &Tensor<#ty, { [-1] }>,
            y: &Tensor<#ty, { [-1] }>,
        ) {
            let condition_tile: Tile<#ty, { [B] }> = load_tile_like(condition, out);
            let x_tile: Tile<#ty, { [B] }> = load_tile_like(x, out);
            let y_tile: Tile<#ty, { [B] }> = load_tile_like(y, out);
            let zero = constant(#zero, out.shape());
            let mask = cmpf(
                condition_tile,
                zero,
                predicate::NotEqual,
                cmp_ordering::Ordered,
            );
            out.store(select(mask, x_tile, y_tile));
        }

        #[cutile::entry()]
        pub fn #where_bool<const B: i32>(
            out: &mut Tensor<#ty, { [B] }>,
            condition: &Tensor<u8, { [-1] }>,
            x: &Tensor<#ty, { [-1] }>,
            y: &Tensor<#ty, { [-1] }>,
        ) {
            let condition_tile: Tile<u8, { [B] }> = load_tile_like(condition, out);
            let x_tile: Tile<#ty, { [B] }> = load_tile_like(x, out);
            let y_tile: Tile<#ty, { [B] }> = load_tile_like(y, out);
            let zero = constant(0u8, out.shape());
            let mask = cmpi(condition_tile, zero, predicate::NotEqual);
            out.store(select(mask, x_tile, y_tile));
        }

        #[cutile::entry()]
        pub fn #masked_fill<const B: i32>(
            out: &mut Tensor<#ty, { [B] }>,
            input: &Tensor<#ty, { [-1] }>,
            mask: &Tensor<u8, { [-1] }>,
            value: #ty,
        ) {
            let input_tile: Tile<#ty, { [B] }> = load_tile_like(input, out);
            let mask_tile: Tile<u8, { [B] }> = load_tile_like(mask, out);
            let zero = constant(0u8, out.shape());
            let mask = cmpi(mask_tile, zero, predicate::NotEqual);
            let value = broadcast_scalar(value, out.shape());
            out.store(select(mask, value, input_tile));
        }
    })
}

fn render_softmax_entries(dtype: Dtype) -> String {
    let ty = ty(dtype.name);
    let softmax = format_ident!("softmax_{}", dtype.name);
    let log_softmax = format_ident!("log_softmax_{}", dtype.name);
    let softmin = format_ident!("softmin_{}", dtype.name);
    render_items(quote! {
        #[cutile::entry()]
        pub fn #softmax<const BM: i32, const BN: i32>(
            out: &mut Tensor<#ty, { [BM, BN] }>,
            input: &Tensor<#ty, { [-1, -1] }>,
        ) {
            softmax_impl::<BM, BN, false, false>(out, input);
        }

        #[cutile::entry()]
        pub fn #log_softmax<const BM: i32, const BN: i32>(
            out: &mut Tensor<#ty, { [BM, BN] }>,
            input: &Tensor<#ty, { [-1, -1] }>,
        ) {
            softmax_impl::<BM, BN, true, false>(out, input);
        }

        #[cutile::entry()]
        pub fn #softmin<const BM: i32, const BN: i32>(
            out: &mut Tensor<#ty, { [BM, BN] }>,
            input: &Tensor<#ty, { [-1, -1] }>,
        ) {
            softmax_impl::<BM, BN, false, true>(out, input);
        }
    })
}

fn render_reduction_entries(dtype: Dtype) -> String {
    let mut out = String::new();
    for (name, op, has_divisor) in [
        ("sum", 0, false),
        ("mean", 1, true),
        ("max", 2, false),
        ("min", 3, false),
        ("product", 4, false),
    ] {
        for bn in [1, 8, 32, 64, 128, 256, 512, 1024] {
            push_reduce_entry(&mut out, dtype, name, op, bn, has_divisor);
        }
        out.push('\n');
    }
    for (name, op) in [("variance", 5), ("std", 6)] {
        let name = format_ident!("reduce_{name}_{}", dtype.name);
        let ty = ty(dtype.name);
        out.push_str(&render_items(quote! {
            #[cutile::entry()]
            pub fn #name<const BN: i32>(
                out: &mut Tensor<#ty, { [1, 1] }>,
                input: &Tensor<#ty, { [-1, -1] }>,
                divisor: #ty,
            ) {
                reduce_impl::<#op, BN>(out, input, divisor);
            }
        }));
    }
    out
}

fn render_arg_reduction_entries(dtype: Dtype) -> String {
    let mut out = String::new();
    for (name, op) in [("argmax", 0), ("argmin", 1)] {
        for bn in [1, 8, 128, 256, 512, 1024] {
            let name = format_ident!("reduce_{name}_{}_{bn}", dtype.name);
            let ty = ty(dtype.name);
            out.push_str(&render_items(quote! {
                #[cutile::entry()]
                pub fn #name(
                    out: &mut Tensor<i32, { [1, 2] }>,
                    input: &Tensor<#ty, { [-1, -1] }>,
                ) {
                    arg_reduce_impl::<#op, #bn>(out, input);
                }
            }));
        }
        out.push('\n');
    }
    out
}

fn push_binary_entry(out: &mut String, dtype: Dtype, name: &str, helper_name: &str, op: i32) {
    let name = format_ident!("{name}_{}", dtype.name);
    let helper = helper(helper_name);
    let ty = ty(dtype.name);
    out.push_str(&render_items(quote! {
        #[cutile::entry()]
        pub fn #name<const B: i32>(
            out: &mut Tensor<#ty, { [B] }>,
            lhs: &Tensor<#ty, { [-1] }>,
            rhs: &Tensor<#ty, { [-1] }>,
        ) {
            #helper::<#op, B>(out, lhs, rhs);
        }
    }));
}

fn push_binary_bool_entry(out: &mut String, dtype: Dtype, name: &str, op: i32) {
    let name = format_ident!("{name}_{}", dtype.name);
    let ty = ty(dtype.name);
    out.push_str(&render_items(quote! {
        #[cutile::entry()]
        pub fn #name<const B: i32>(
            out: &mut Tensor<u8, { [B] }>,
            lhs: &Tensor<#ty, { [-1] }>,
            rhs: &Tensor<#ty, { [-1] }>,
        ) {
            cmp_bool_store::<#op, B>(out, lhs, rhs);
        }
    }));
}

fn push_fma_entry(out: &mut String, dtype: Dtype) {
    let name = format_ident!("fma_{}", dtype.name);
    let ty = ty(dtype.name);
    out.push_str(&render_items(quote! {
        #[cutile::entry()]
        pub fn #name<const B: i32>(
            out: &mut Tensor<#ty, { [B] }>,
            lhs: &Tensor<#ty, { [-1] }>,
            rhs: &Tensor<#ty, { [-1] }>,
            acc: &Tensor<#ty, { [-1] }>,
        ) {
            let lhs_tile: Tile<#ty, { [B] }> = load_tile_like(lhs, out);
            let rhs_tile: Tile<#ty, { [B] }> = load_tile_like(rhs, out);
            let acc_tile: Tile<#ty, { [B] }> = load_tile_like(acc, out);
            out.store(fma(
                lhs_tile,
                rhs_tile,
                acc_tile,
                rounding::NearestEven,
                ftz::Disabled,
            ));
        }
    }));
}

fn push_float_cast_entry(out: &mut String, dtype: Dtype, target: &str) {
    let name = format_ident!("cast_{}_{}", dtype.name, target);
    let dtype_ty = ty(dtype.name);
    let target = ty(target);
    out.push_str(&render_items(quote! {
        #[cutile::entry()]
        pub fn #name<const B: i32>(
            out: &mut Tensor<#target, { [B] }>,
            input: &Tensor<#dtype_ty, { [-1] }>,
        ) {
            let values: Tile<#dtype_ty, { [B] }> = load_tile_like(input, out);
            let values: Tile<#target, { [B] }> = convert_tile(values);
            out.store(values);
        }
    }));
}

fn push_bf16_to_f32_cast_entry(out: &mut String) {
    out.push_str(&render_items(quote! {
        #[cfg(feature = "dtype-bf16")]
        #[cutile::entry()]
        pub fn cast_bf16_f32<const B: i32>(
            out: &mut Tensor<f32, { [B] }>,
            input: &Tensor<bf16, { [-1] }>,
        ) {
            let values: Tile<bf16, { [B] }> = load_tile_like(input, out);
            let values: Tile<f32, { [B] }> = convert_tile(values);
            out.store(values);
        }
    }));
}

fn push_f32_to_bf16_cast_entry(out: &mut String) {
    out.push_str(&render_items(quote! {
        #[cfg(feature = "dtype-bf16")]
        #[cutile::entry()]
        pub fn cast_f32_bf16<const B: i32>(
            out: &mut Tensor<bf16, { [B] }>,
            input: &Tensor<f32, { [-1] }>,
        ) {
            let values: Tile<f32, { [B] }> = load_tile_like(input, out);
            let values: Tile<bf16, { [B] }> = convert_tile(values);
            out.store(values);
        }
    }));
}

fn push_float_to_int_cast_entry(out: &mut String, dtype: Dtype, target: &str) {
    let name = format_ident!("cast_{}_{}", dtype.name, target);
    let dtype_ty = ty(dtype.name);
    let target = ty(target);
    out.push_str(&render_items(quote! {
        #[cutile::entry()]
        pub fn #name<const B: i32>(
            out: &mut Tensor<#target, { [B] }>,
            input: &Tensor<#dtype_ty, { [-1] }>,
        ) {
            let values: Tile<#dtype_ty, { [B] }> = load_tile_like(input, out);
            out.store(ftoi(values, rounding::Zero));
        }
    }));
}

fn push_bool_cast_entry(out: &mut String, dtype: Dtype) {
    let name = format_ident!("cast_bool_{}", dtype.name);
    let ty = ty(dtype.name);
    let one = expr(dtype.one);
    let zero = expr(dtype.zero);
    out.push_str(&render_items(quote! {
        #[cutile::entry()]
        pub fn #name<const B: i32>(
            out: &mut Tensor<#ty, { [B] }>,
            input: &Tensor<u8, { [-1] }>,
        ) {
            let values: Tile<u8, { [B] }> = load_tile_like(input, out);
            let zero_u8: Tile<u8, { [B] }> = constant(0u8, out.shape());
            let mask = cmpi(values, zero_u8, predicate::NotEqual);
            let one: Tile<#ty, { [B] }> = constant(#one, out.shape());
            let zero: Tile<#ty, { [B] }> = constant(#zero, out.shape());
            out.store(select(mask, one, zero));
        }
    }));
}

fn push_int_to_float_cast_entry(out: &mut String, dtype: Dtype, source: &str) {
    let name = format_ident!("cast_{}_{}", source, dtype.name);
    let source = ty(source);
    let ty = ty(dtype.name);
    out.push_str(&render_items(quote! {
        #[cutile::entry()]
        pub fn #name<const B: i32>(
            out: &mut Tensor<#ty, { [B] }>,
            input: &Tensor<#source, { [-1] }>,
        ) {
            let values: Tile<#source, { [B] }> = load_tile_like(input, out);
            let values: Tile<#ty, { [B] }> = convert_tile(values);
            out.store(values);
        }
    }));
}

fn push_float_to_bool_cast_entry(out: &mut String, dtype: Dtype) {
    let name = format_ident!("cast_{}_bool", dtype.name);
    let ty = ty(dtype.name);
    let zero = expr(dtype.zero);
    out.push_str(&render_items(quote! {
        #[cutile::entry()]
        pub unsafe fn #name(out: *mut u8, input: *mut #ty, len: i32) {
            let pid: (i32, i32, i32) = get_tile_block_id();
            let tile_shape = const_shape![128];
            let offsets: Tile<i32, { [128] }> =
                iota(tile_shape) + broadcast_scalar(pid.0 * 128i32, tile_shape);
            let len_tile = broadcast_scalar(len, tile_shape);
            let mask = cmpi(offsets, len_tile, predicate::LessThan);
            let zero_offsets: Tile<i32, { [128] }> = constant(0i32, tile_shape);
            let safe_offsets = select(mask, offsets, zero_offsets);

            let input_base: PointerTile<*mut #ty, { [] }> = pointer_to_tile(input);
            let input_base: PointerTile<*mut #ty, { [1] }> =
                input_base.reshape(const_shape![1]);
            let input_ptrs: PointerTile<*mut #ty, { [128] }> =
                input_base.broadcast(tile_shape);
            let input_ptrs: PointerTile<*mut #ty, { [128] }> =
                input_ptrs.offset_tile(safe_offsets);
            let input_result: (Tile<#ty, { [128] }>, Token) = load_ptr_tko(
                input_ptrs,
                ordering::Weak,
                None::<scope::TileBlock>,
                Some(mask),
                Some(#zero),
                None,
                Latency::<0>,
            );
            let zero = constant(#zero, tile_shape);
            let nonzero = cmpf(
                input_result.0,
                zero,
                predicate::NotEqual,
                cmp_ordering::Unordered,
            );
            let true_value: Tile<u8, { [128] }> = constant(1u8, tile_shape);
            let false_value: Tile<u8, { [128] }> = constant(0u8, tile_shape);
            let values = select(nonzero, true_value, false_value);

            let out_base: PointerTile<*mut u8, { [] }> = pointer_to_tile(out);
            let out_base: PointerTile<*mut u8, { [1] }> = out_base.reshape(const_shape![1]);
            let out_ptrs: PointerTile<*mut u8, { [128] }> = out_base.broadcast(tile_shape);
            let out_ptrs: PointerTile<*mut u8, { [128] }> = out_ptrs.offset_tile(offsets);
            store_ptr_tko(
                out_ptrs,
                values,
                ordering::Weak,
                None::<scope::TileBlock>,
                Some(mask),
                None,
                Latency::<0>,
            );
        }
    }));
}

fn push_quantize_entry(out: &mut String, dtype: Dtype, target: &str, low: &str, high: &str) {
    let name = format_ident!("quantize_{}_{}", dtype.name, target);
    let dtype_ty = ty(dtype.name);
    let target = ty(target);
    let low = expr(low);
    let high = expr(high);
    if dtype.quantize_ties_to_even {
        out.push_str(&render_items(quote! {
            #[cutile::entry()]
            pub fn #name<const B: i32>(
                out: &mut Tensor<#target, { [B] }>,
                input: &Tensor<#dtype_ty, { [-1] }>,
                scale: #dtype_ty,
                zero_point: #dtype_ty,
            ) {
                let values: Tile<#dtype_ty, { [B] }> = load_tile_like(input, out);
                let raw =
                    values / broadcast_scalar(scale, out.shape())
                        + broadcast_scalar(zero_point, out.shape());
                let low = constant(#low, out.shape());
                let high = constant(#high, out.shape());
                let clamped = min_tile(max_tile(raw, low), high);
                let floored = floor(clamped);
                let fraction = clamped - floored;
                let half = constant(0.5f32, out.shape());
                let one = constant(1.0f32, out.shape());
                let two = constant(2.0f32, out.shape());
                let floor_half = floor(floored / two);
                let floor_is_odd = cmpf(
                    floor_half * two,
                    floored,
                    predicate::NotEqual,
                    cmp_ordering::Ordered,
                );
                let above_half = cmpf(
                    fraction,
                    half,
                    predicate::GreaterThan,
                    cmp_ordering::Ordered,
                );
                let tie = cmpf(fraction, half, predicate::Equal, cmp_ordering::Ordered);
                let rounded_up = floored + one;
                let rounded = select(above_half | (tie & floor_is_odd), rounded_up, floored);
                let quantized: Tile<#target, { [B] }> = convert_tile(rounded);
                out.store(quantized);
            }
        }));
    } else {
        out.push_str(&render_items(quote! {
            #[cutile::entry()]
            pub fn #name<const B: i32>(
                out: &mut Tensor<#target, { [B] }>,
                input: &Tensor<#dtype_ty, { [-1] }>,
                scale: #dtype_ty,
                zero_point: #dtype_ty,
            ) {
                let values: Tile<#dtype_ty, { [B] }> = load_tile_like(input, out);
                let raw =
                    values / broadcast_scalar(scale, out.shape())
                        + broadcast_scalar(zero_point, out.shape());
                let low = constant(#low, out.shape());
                let high = constant(#high, out.shape());
                out.store(ftoi(min_tile(max_tile(raw, low), high), rounding::NearestEven));
            }
        }));
    }
}

fn push_swiglu_entry(out: &mut String, dtype: Dtype) {
    let name = format_ident!("swiglu_{}", dtype.name);
    let ty = ty(dtype.name);
    if dtype.name == "f16" {
        out.push_str(&render_items(quote! {
            #[cutile::entry()]
            pub fn #name<const B: i32>(
                out: &mut Tensor<f16, { [B] }>,
                input: &Tensor<f16, { [-1] }>,
                gate: &Tensor<f16, { [-1] }>,
            ) {
                let input_tile: Tile<f16, { [B] }> = load_tile_like(input, out);
                let gate_tile: Tile<f16, { [B] }> = load_tile_like(gate, out);
                let input_tile: Tile<f32, { [B] }> = convert_tile(input_tile);
                let gate_tile: Tile<f32, { [B] }> = convert_tile(gate_tile);
                let one = constant(1.0f32, out.shape());
                let zero = constant(0.0f32, out.shape());
                let value = input_tile * gate_tile / (one + exp(zero - gate_tile));
                out.store(convert_tile(value));
            }
        }));
    } else {
        let one = expr(dtype.one);
        let zero = expr(dtype.zero);
        out.push_str(&render_items(quote! {
            #[cutile::entry()]
            pub fn #name<const B: i32>(
                out: &mut Tensor<#ty, { [B] }>,
                input: &Tensor<#ty, { [-1] }>,
                gate: &Tensor<#ty, { [-1] }>,
            ) {
                let input_tile: Tile<#ty, { [B] }> = load_tile_like(input, out);
                let gate_tile: Tile<#ty, { [B] }> = load_tile_like(gate, out);
                let one = constant(#one, out.shape());
                let zero = constant(#zero, out.shape());
                out.store(input_tile * gate_tile / (one + exp(zero - gate_tile)));
            }
        }));
    }
}

fn push_unary_entry(out: &mut String, dtype: Dtype, name: &str, helper_name: &str, op: i32) {
    let name = format_ident!("{name}_{}", dtype.name);
    let helper = helper(helper_name);
    let ty = ty(dtype.name);
    out.push_str(&render_items(quote! {
        #[cutile::entry()]
        pub fn #name<const B: i32>(
            out: &mut Tensor<#ty, { [B] }>,
            input: &Tensor<#ty, { [-1] }>,
        ) {
            #helper::<#op, B>(out, input);
        }
    }));
}

fn push_unary_param_entry(out: &mut String, dtype: Dtype, name: &str, param: &str, _unused: bool) {
    let ty = ty(dtype.name);
    let zero = expr(dtype.zero);
    let one = expr(dtype.one);
    let body = match name {
        "leaky_relu" => quote! {
            let x: Tile<#ty, { [B] }> = load_tile_like(input, out);
            let zero = constant(#zero, out.shape());
            let positive = cmpf(
                x,
                zero,
                predicate::GreaterThanOrEqual,
                cmp_ordering::Ordered,
            );
            out.store(select(
                positive,
                x,
                x * broadcast_scalar(negative_slope, out.shape()),
            ));
        },
        "elu" => quote! {
            let x: Tile<#ty, { [B] }> = load_tile_like(input, out);
            let zero = constant(#zero, out.shape());
            let one = constant(#one, out.shape());
            let positive = cmpf(
                x,
                zero,
                predicate::GreaterThanOrEqual,
                cmp_ordering::Ordered,
            );
            out.store(select(
                positive,
                x,
                broadcast_scalar(alpha, out.shape()) * (exp(x) - one),
            ));
        },
        "celu" => quote! {
            let x: Tile<#ty, { [B] }> = load_tile_like(input, out);
            let zero = constant(#zero, out.shape());
            let one = constant(#one, out.shape());
            let alpha = broadcast_scalar(alpha, out.shape());
            let positive = cmpf(
                x,
                zero,
                predicate::GreaterThanOrEqual,
                cmp_ordering::Ordered,
            );
            out.store(select(positive, x, alpha * (exp(x / alpha) - one)));
        },
        "hardshrink" => quote! {
            let x: Tile<#ty, { [B] }> = load_tile_like(input, out);
            let zero = constant(#zero, out.shape());
            let lambda = broadcast_scalar(lambda, out.shape());
            let keep_positive = cmpf(x, lambda, predicate::GreaterThan, cmp_ordering::Ordered);
            let keep_negative = cmpf(x, zero - lambda, predicate::LessThan, cmp_ordering::Ordered);
            out.store(select(keep_positive | keep_negative, x, zero));
        },
        "softshrink" => quote! {
            let x: Tile<#ty, { [B] }> = load_tile_like(input, out);
            let zero = constant(#zero, out.shape());
            let lambda = broadcast_scalar(lambda, out.shape());
            let positive = cmpf(x, lambda, predicate::GreaterThan, cmp_ordering::Ordered);
            let negative = cmpf(x, zero - lambda, predicate::LessThan, cmp_ordering::Ordered);
            out.store(select(
                positive,
                x - lambda,
                select(negative, x + lambda, zero),
            ));
        },
        _ => unreachable!(),
    };
    let param = if name == "leaky_relu" {
        "negative_slope"
    } else if matches!(name, "hardshrink" | "softshrink") {
        "lambda"
    } else {
        param
    };
    let name = format_ident!("{name}_{}", dtype.name);
    let param = format_ident!("{param}");
    out.push_str(&render_items(quote! {
        #[cutile::entry()]
        pub fn #name<const B: i32>(
            out: &mut Tensor<#ty, { [B] }>,
            input: &Tensor<#ty, { [-1] }>,
            #param: #ty,
        ) {
            #body
        }
    }));
}

fn push_threshold_entry(out: &mut String, dtype: Dtype) {
    let name = format_ident!("threshold_{}", dtype.name);
    let ty = ty(dtype.name);
    out.push_str(&render_items(quote! {
        #[cutile::entry()]
        pub fn #name<const B: i32>(
            out: &mut Tensor<#ty, { [B] }>,
            input: &Tensor<#ty, { [-1] }>,
            threshold: #ty,
            value: #ty,
        ) {
            let x: Tile<#ty, { [B] }> = load_tile_like(input, out);
            let keep = cmpf(
                x,
                broadcast_scalar(threshold, out.shape()),
                predicate::GreaterThan,
                cmp_ordering::Ordered,
            );
            out.store(select(keep, x, broadcast_scalar(value, out.shape())));
        }
    }));
}

fn push_hardtanh_entry(out: &mut String, dtype: Dtype) {
    let name = format_ident!("hardtanh_{}", dtype.name);
    let ty = ty(dtype.name);
    out.push_str(&render_items(quote! {
        #[cutile::entry()]
        pub fn #name<const B: i32>(
            out: &mut Tensor<#ty, { [B] }>,
            input: &Tensor<#ty, { [-1] }>,
            min_value: #ty,
            max_value: #ty,
        ) {
            let x: Tile<#ty, { [B] }> = load_tile_like(input, out);
            let min_value = broadcast_scalar(min_value, out.shape());
            let max_value = broadcast_scalar(max_value, out.shape());
            out.store(min_tile(max_tile(x, min_value), max_value));
        }
    }));
}

fn push_nan_to_num_entry(out: &mut String, dtype: Dtype) {
    let name = format_ident!("nan_to_num_{}", dtype.name);
    let ty = ty(dtype.name);
    out.push_str(&render_items(quote! {
        #[cutile::entry()]
        pub fn #name<const B: i32>(
            out: &mut Tensor<#ty, { [B] }>,
            input: &Tensor<#ty, { [-1] }>,
            nan: #ty,
            posinf: #ty,
            neginf: #ty,
        ) {
            nan_to_num_store(out, input, nan, posinf, neginf);
        }
    }));
}

fn push_unary_bool_entry(out: &mut String, dtype: Dtype, name: &str, op: i32) {
    let name = format_ident!("{name}_{}", dtype.name);
    let ty = ty(dtype.name);
    out.push_str(&render_items(quote! {
        #[cutile::entry()]
        pub fn #name<const B: i32>(
            out: &mut Tensor<u8, { [B] }>,
            input: &Tensor<#ty, { [-1] }>,
        ) {
            unary_bool_store::<#op, B>(out, input);
        }
    }));
}

fn push_scalar_entry(out: &mut String, dtype: Dtype, name: &str, helper_name: &str, op: i32) {
    let name = format_ident!("{name}_{}", dtype.name);
    let helper = helper(helper_name);
    let ty = ty(dtype.name);
    out.push_str(&render_items(quote! {
        #[cutile::entry()]
        pub fn #name<const B: i32>(
            out: &mut Tensor<#ty, { [B] }>,
            input: &Tensor<#ty, { [-1] }>,
            scalar: #ty,
        ) {
            #helper::<#op, B>(out, input, scalar);
        }
    }));
}

fn push_scalar_bool_entry(out: &mut String, dtype: Dtype, name: &str, op: i32) {
    let name = format_ident!("{name}_{}", dtype.name);
    let ty = ty(dtype.name);
    out.push_str(&render_items(quote! {
        #[cutile::entry()]
        pub fn #name<const B: i32>(
            out: &mut Tensor<u8, { [B] }>,
            input: &Tensor<#ty, { [-1] }>,
            scalar: #ty,
        ) {
            scalar_cmp_bool_store::<#op, B>(out, input, scalar);
        }
    }));
}

fn push_reduce_entry(
    out: &mut String,
    dtype: Dtype,
    name: &str,
    op: i32,
    bn: i32,
    has_divisor: bool,
) {
    let ty = ty(dtype.name);
    let name = format_ident!("reduce_{name}_{}_{bn}", dtype.name);
    let divisor = expr(if has_divisor { "divisor" } else { dtype.one });
    let args = if has_divisor {
        quote! { divisor: #ty, }
    } else {
        quote! {}
    };
    out.push_str(&render_items(quote! {
        #[cutile::entry()]
        pub fn #name(
            out: &mut Tensor<#ty, { [1, 1] }>,
            input: &Tensor<#ty, { [-1, -1] }>,
            #args
        ) {
            reduce_impl::<#op, #bn>(out, input, #divisor);
        }
    }));
}
