/* automatically generated by rust-bindgen 0.72.1 */

pub type size_t = ::core::ffi::c_ulong;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct cublasXtContext {
    _unused: [u8; 0],
}
/// The [`cublasXtHandle_t`] type is a pointer type to an opaque structure holding the cuBLASXt API context. The cuBLASXt API context must be initialized using [`cublasXtCreate`] and the returned handle must be passed to all subsequent cuBLASXt API function calls. The context should be destroyed at the end using [`cublasXtDestroy`].
pub type cublasXtHandle_t = *mut cublasXtContext;
unsafe extern "C" {
    /// This function initializes the cuBLASXt API and creates a handle to an opaque structure holding the cuBLASXt API context. It allocates hardware resources on the host and device and must be called prior to making any other cuBLASXt API calls.
    ///
    /// # Return value
    ///
    /// - [`cublasStatus_t::CUBLAS_STATUS_ALLOC_FAILED`]: the resources could not be allocated.
    /// - [`cublasStatus_t::CUBLAS_STATUS_NOT_SUPPORTED`]: cuBLASXt API is only supported on 64-bit platform.
    /// - [`cublasStatus_t::CUBLAS_STATUS_SUCCESS`]: the initialization succeeded.
    pub fn cublasXtCreate(handle: *mut cublasXtHandle_t) -> cublasStatus_t;
}
unsafe extern "C" {
    /// This function releases hardware resources used by the cuBLASXt API context. The release of GPU resources may be deferred until the application exits. This function is usually the last call with a particular handle to the cuBLASXt API.
    ///
    /// # Return value
    ///
    /// - [`cublasStatus_t::CUBLAS_STATUS_NOT_INITIALIZED`]: the library was not initialized.
    /// - [`cublasStatus_t::CUBLAS_STATUS_SUCCESS`]: the shut down succeeded.
    pub fn cublasXtDestroy(handle: cublasXtHandle_t) -> cublasStatus_t;
}
unsafe extern "C" {
    pub fn cublasXtGetNumBoards(
        nbDevices: ::core::ffi::c_int,
        deviceId: *mut ::core::ffi::c_int,
        nbBoards: *mut ::core::ffi::c_int,
    ) -> cublasStatus_t;
}
unsafe extern "C" {
    pub fn cublasXtMaxBoards(nbGpuBoards: *mut ::core::ffi::c_int) -> cublasStatus_t;
}
unsafe extern "C" {
    /// This function allows the user to provide the number of GPU devices and their respective Ids that will participate to the subsequent cuBLASXt API Math function calls. This function will create a cuBLAS context for every GPU provided in that list. Currently the device configuration is static and cannot be changed between Math function calls. In that regard, this function should be called only once after [`cublasXtCreate`]. To be able to run multiple configurations, multiple cuBLASXt API contexts should be created.
    ///
    /// # Return value
    ///
    /// - [`cublasStatus_t::CUBLAS_STATUS_ALLOC_FAILED`]: Some resources could not be allocated.
    /// - [`cublasStatus_t::CUBLAS_STATUS_INVALID_VALUE`]: Access to at least one of the device could not be done or a cuBLAS context could not be created on at least one of the device.
    /// - [`cublasStatus_t::CUBLAS_STATUS_SUCCESS`]: User call was successful.
    pub fn cublasXtDeviceSelect(
        handle: cublasXtHandle_t,
        nbDevices: ::core::ffi::c_int,
        deviceId: *mut ::core::ffi::c_int,
    ) -> cublasStatus_t;
}
unsafe extern "C" {
    /// This function allows the user to set the block dimension used for the tiling of the matrices for the subsequent Math function calls. Matrices are split in square tiles of blockDim x blockDim dimension. This function can be called anytime and will take effect for the following Math function calls. The block dimension should be chosen in a way to optimize the math operation and to make sure that the PCI transfers are well overlapped with the computation.
    ///
    /// # Return value
    ///
    /// - [`cublasStatus_t::CUBLAS_STATUS_INVALID_VALUE`]: blockDim &lt;= 0.
    /// - [`cublasStatus_t::CUBLAS_STATUS_SUCCESS`]: the call has been successful.
    pub fn cublasXtSetBlockDim(
        handle: cublasXtHandle_t,
        blockDim: ::core::ffi::c_int,
    ) -> cublasStatus_t;
}
unsafe extern "C" {
    /// This function allows the user to query the block dimension used for the tiling of the matrices.
    ///
    /// # Return value
    ///
    /// - [`cublasStatus_t::CUBLAS_STATUS_SUCCESS`]: the call has been successful.
    pub fn cublasXtGetBlockDim(
        handle: cublasXtHandle_t,
        blockDim: *mut ::core::ffi::c_int,
    ) -> cublasStatus_t;
}
#[repr(u32)]
#[derive(
    Debug,
    Copy,
    Clone,
    Hash,
    PartialOrd,
    Ord,
    PartialEq,
    Eq,
    TryFromPrimitive,
    IntoPrimitive,
)]
pub enum cublasXtPinnedMemMode_t {
    CUBLASXT_PINNING_DISABLED = 0,
    CUBLASXT_PINNING_ENABLED = 1,
}
unsafe extern "C" {
    /// This function allows the user to query the Pinning Memory mode. By default, the Pinning Memory mode is disabled.
    ///
    /// # Return value
    ///
    /// - [`cublasStatus_t::CUBLAS_STATUS_SUCCESS`]: the call has been successful.
    pub fn cublasXtGetPinningMemMode(
        handle: cublasXtHandle_t,
        mode: *mut cublasXtPinnedMemMode_t,
    ) -> cublasStatus_t;
}
unsafe extern "C" {
    /// This function allows the user to enable or disable the Pinning Memory mode. When enabled, the matrices passed in subsequent cuBLASXt API calls will be pinned/unpinned using the CUDART routine `cudaHostRegister()` and `cudaHostUnregister()` respectively if the matrices are not already pinned. If a matrix happened to be pinned partially, it will also not be pinned. Pinning the memory improve PCI transfer performance and allows to overlap PCI memory transfer with computation. However pinning/unpinning the memory take some time which might not be amortized. It is advised that the user pins the memory on its own using `cudaMallocHost()` or `cudaHostRegister()` and unpin it when the computation sequence is completed. By default, the Pinning Memory mode is disabled.
    ///
    /// # Return value
    ///
    /// - [`cublasStatus_t::CUBLAS_STATUS_INVALID_VALUE`]: the mode value is different from [`CUBLASXT_PINNING_DISABLED`] and [`CUBLASXT_PINNING_ENABLED`].
    /// - [`cublasStatus_t::CUBLAS_STATUS_SUCCESS`]: the call has been successful.
    pub fn cublasXtSetPinningMemMode(
        handle: cublasXtHandle_t,
        mode: cublasXtPinnedMemMode_t,
    ) -> cublasStatus_t;
}
/// The `cublasOpType_t` enumerates the four possible types supported by BLAS routines. This enum is used as parameters of the routines [`cublasXtSetCpuRoutine`] and [`cublasXtSetCpuRatio`] to setup the hybrid configuration.
#[repr(u32)]
#[derive(
    Debug,
    Copy,
    Clone,
    Hash,
    PartialOrd,
    Ord,
    PartialEq,
    Eq,
    TryFromPrimitive,
    IntoPrimitive,
)]
pub enum cublasXtOpType_t {
    /// float or single precision type.
    CUBLASXT_FLOAT = 0,
    /// double precision type.
    CUBLASXT_DOUBLE = 1,
    /// single precision complex.
    CUBLASXT_COMPLEX = 2,
    /// double precision complex.
    CUBLASXT_DOUBLECOMPLEX = 3,
}
/// The [`cublasXtBlasOp_t`] type enumerates the BLAS3 or BLAS-like routine supported by cuBLASXt API. This enum is used as parameters of the routines [`cublasXtSetCpuRoutine`] and [`cublasXtSetCpuRatio`] to setup the hybrid configuration.
#[repr(u32)]
#[derive(
    Debug,
    Copy,
    Clone,
    Hash,
    PartialOrd,
    Ord,
    PartialEq,
    Eq,
    TryFromPrimitive,
    IntoPrimitive,
)]
pub enum cublasXtBlasOp_t {
    /// GEMM routine.
    CUBLASXT_GEMM = 0,
    /// SYRK routine.
    CUBLASXT_SYRK = 1,
    /// HERK routine.
    CUBLASXT_HERK = 2,
    /// SYMM routine.
    CUBLASXT_SYMM = 3,
    /// HEMM routine.
    CUBLASXT_HEMM = 4,
    /// TRSM routine.
    CUBLASXT_TRSM = 5,
    /// SYR2K routine.
    CUBLASXT_SYR2K = 6,
    /// HER2K routine.
    CUBLASXT_HER2K = 7,
    /// SPMM routine.
    CUBLASXT_SPMM = 8,
    /// SYRKX routine.
    CUBLASXT_SYRKX = 9,
    /// HERKX routine.
    CUBLASXT_HERKX = 10,
    CUBLASXT_TRMM = 11,
    CUBLASXT_ROUTINE_MAX = 12,
}
unsafe extern "C" {
    /// This function allows the user to provide a CPU implementation of the corresponding BLAS routine. This function can be used with the function [`cublasXtSetCpuRatio`] to define an hybrid computation between the CPU and the GPUs. Currently the hybrid feature is only supported for the xGEMM routines.
    ///
    /// # Return value
    ///
    /// - [`cublasStatus_t::CUBLAS_STATUS_INVALID_VALUE`]: blasOp or type define an invalid combination.
    /// - [`cublasStatus_t::CUBLAS_STATUS_NOT_SUPPORTED`]: CPU-GPU Hybridization for that routine is not supported.
    /// - [`cublasStatus_t::CUBLAS_STATUS_SUCCESS`]: the call has been successful.
    pub fn cublasXtSetCpuRoutine(
        handle: cublasXtHandle_t,
        blasOp: cublasXtBlasOp_t,
        type_: cublasXtOpType_t,
        blasFunctor: *mut ::core::ffi::c_void,
    ) -> cublasStatus_t;
}
unsafe extern "C" {
    /// This function allows the user to define the percentage of workload that should be done on a CPU in the context of an hybrid computation. This function can be used with the function [`cublasXtSetCpuRoutine`] to define an hybrid computation between the CPU and the GPUs. Currently the hybrid feature is only supported for the xGEMM routines.
    ///
    /// # Return value
    ///
    /// - [`cublasStatus_t::CUBLAS_STATUS_INVALID_VALUE`]: blasOp or type define an invalid combination.
    /// - [`cublasStatus_t::CUBLAS_STATUS_NOT_SUPPORTED`]: CPU-GPU Hybridization for that routine is not supported.
    /// - [`cublasStatus_t::CUBLAS_STATUS_SUCCESS`]: the call has been successful.
    pub fn cublasXtSetCpuRatio(
        handle: cublasXtHandle_t,
        blasOp: cublasXtBlasOp_t,
        type_: cublasXtOpType_t,
        ratio: f32,
    ) -> cublasStatus_t;
}
unsafe extern "C" {
    /// This function supports the 64-bit Integer Interface.
    ///
    /// This function performs the matrix-matrix multiplication:
    /// $$
    /// C = \alpha\text{op}(A)\text{op}(B) + \beta C
    /// $$
    ///
    /// where $\alpha$ and $\beta$ are scalars, and $A$, $B$ and $C$ are matrices stored in column-major format with dimensions $\text{op}(A)$ $m \times k$, $\text{op}(B)$ $k \times n$ and $C$ $m \times n$, respectively. Also, for matrix $A$:
    /// $$
    /// \text{op}(A) = \left\\{ \begin{matrix}
    /// A & {\text{if }\textsf{transa == $\mathrm{CUBLAS_OP_N}$}} \\\\
    /// A^{T} & {\text{if }\textsf{transa == $\mathrm{CUBLAS_OP_T}$}} \\\\
    /// A^{H} & {\text{if }\textsf{transa == $\mathrm{CUBLAS_OP_C}$}} \\\\
    /// \end{matrix} \right.
    /// $$
    ///
    /// and $\text{op}(B)$ is defined similarly for matrix $B$.
    ///
    /// For references please refer to NETLIB documentation:
    ///
    /// [sgemm()](http://www.netlib.org/blas/sgemm.f), [dgemm()](http://www.netlib.org/blas/dgemm.f), [cgemm()](http://www.netlib.org/blas/cgemm.f), [zgemm()](http://www.netlib.org/blas/zgemm.f).
    pub fn cublasXtSgemm(
        handle: cublasXtHandle_t,
        transa: cublasOperation_t,
        transb: cublasOperation_t,
        m: size_t,
        n: size_t,
        k: size_t,
        alpha: *const f32,
        A: *const f32,
        lda: size_t,
        B: *const f32,
        ldb: size_t,
        beta: *const f32,
        C: *mut f32,
        ldc: size_t,
    ) -> cublasStatus_t;
}
unsafe extern "C" {
    /// This function supports the 64-bit Integer Interface.
    ///
    /// This function performs the matrix-matrix multiplication:
    /// $$
    /// C = \alpha\text{op}(A)\text{op}(B) + \beta C
    /// $$
    ///
    /// where $\alpha$ and $\beta$ are scalars, and $A$, $B$ and $C$ are matrices stored in column-major format with dimensions $\text{op}(A)$ $m \times k$, $\text{op}(B)$ $k \times n$ and $C$ $m \times n$, respectively. Also, for matrix $A$:
    /// $$
    /// \text{op}(A) = \left\\{ \begin{matrix}
    /// A & {\text{if }\textsf{transa == $\mathrm{CUBLAS_OP_N}$}} \\\\
    /// A^{T} & {\text{if }\textsf{transa == $\mathrm{CUBLAS_OP_T}$}} \\\\
    /// A^{H} & {\text{if }\textsf{transa == $\mathrm{CUBLAS_OP_C}$}} \\\\
    /// \end{matrix} \right.
    /// $$
    ///
    /// and $\text{op}(B)$ is defined similarly for matrix $B$.
    ///
    /// For references please refer to NETLIB documentation:
    ///
    /// [sgemm()](http://www.netlib.org/blas/sgemm.f), [dgemm()](http://www.netlib.org/blas/dgemm.f), [cgemm()](http://www.netlib.org/blas/cgemm.f), [zgemm()](http://www.netlib.org/blas/zgemm.f).
    pub fn cublasXtDgemm(
        handle: cublasXtHandle_t,
        transa: cublasOperation_t,
        transb: cublasOperation_t,
        m: size_t,
        n: size_t,
        k: size_t,
        alpha: *const f64,
        A: *const f64,
        lda: size_t,
        B: *const f64,
        ldb: size_t,
        beta: *const f64,
        C: *mut f64,
        ldc: size_t,
    ) -> cublasStatus_t;
}
unsafe extern "C" {
    /// This function supports the 64-bit Integer Interface.
    ///
    /// This function performs the matrix-matrix multiplication:
    /// $$
    /// C = \alpha\text{op}(A)\text{op}(B) + \beta C
    /// $$
    ///
    /// where $\alpha$ and $\beta$ are scalars, and $A$, $B$ and $C$ are matrices stored in column-major format with dimensions $\text{op}(A)$ $m \times k$, $\text{op}(B)$ $k \times n$ and $C$ $m \times n$, respectively. Also, for matrix $A$:
    /// $$
    /// \text{op}(A) = \left\\{ \begin{matrix}
    /// A & {\text{if }\textsf{transa == $\mathrm{CUBLAS_OP_N}$}} \\\\
    /// A^{T} & {\text{if }\textsf{transa == $\mathrm{CUBLAS_OP_T}$}} \\\\
    /// A^{H} & {\text{if }\textsf{transa == $\mathrm{CUBLAS_OP_C}$}} \\\\
    /// \end{matrix} \right.
    /// $$
    ///
    /// and $\text{op}(B)$ is defined similarly for matrix $B$.
    ///
    /// For references please refer to NETLIB documentation:
    ///
    /// [sgemm()](http://www.netlib.org/blas/sgemm.f), [dgemm()](http://www.netlib.org/blas/dgemm.f), [cgemm()](http://www.netlib.org/blas/cgemm.f), [zgemm()](http://www.netlib.org/blas/zgemm.f).
    pub fn cublasXtCgemm(
        handle: cublasXtHandle_t,
        transa: cublasOperation_t,
        transb: cublasOperation_t,
        m: size_t,
        n: size_t,
        k: size_t,
        alpha: *const cuComplex,
        A: *const cuComplex,
        lda: size_t,
        B: *const cuComplex,
        ldb: size_t,
        beta: *const cuComplex,
        C: *mut cuComplex,
        ldc: size_t,
    ) -> cublasStatus_t;
}
unsafe extern "C" {
    /// This function supports the 64-bit Integer Interface.
    ///
    /// This function performs the matrix-matrix multiplication:
    /// $$
    /// C = \alpha\text{op}(A)\text{op}(B) + \beta C
    /// $$
    ///
    /// where $\alpha$ and $\beta$ are scalars, and $A$, $B$ and $C$ are matrices stored in column-major format with dimensions $\text{op}(A)$ $m \times k$, $\text{op}(B)$ $k \times n$ and $C$ $m \times n$, respectively. Also, for matrix $A$:
    /// $$
    /// \text{op}(A) = \left\\{ \begin{matrix}
    /// A & {\text{if }\textsf{transa == $\mathrm{CUBLAS_OP_N}$}} \\\\
    /// A^{T} & {\text{if }\textsf{transa == $\mathrm{CUBLAS_OP_T}$}} \\\\
    /// A^{H} & {\text{if }\textsf{transa == $\mathrm{CUBLAS_OP_C}$}} \\\\
    /// \end{matrix} \right.
    /// $$
    ///
    /// and $\text{op}(B)$ is defined similarly for matrix $B$.
    ///
    /// For references please refer to NETLIB documentation:
    ///
    /// [sgemm()](http://www.netlib.org/blas/sgemm.f), [dgemm()](http://www.netlib.org/blas/dgemm.f), [cgemm()](http://www.netlib.org/blas/cgemm.f), [zgemm()](http://www.netlib.org/blas/zgemm.f).
    pub fn cublasXtZgemm(
        handle: cublasXtHandle_t,
        transa: cublasOperation_t,
        transb: cublasOperation_t,
        m: size_t,
        n: size_t,
        k: size_t,
        alpha: *const cuDoubleComplex,
        A: *const cuDoubleComplex,
        lda: size_t,
        B: *const cuDoubleComplex,
        ldb: size_t,
        beta: *const cuDoubleComplex,
        C: *mut cuDoubleComplex,
        ldc: size_t,
    ) -> cublasStatus_t;
}
unsafe extern "C" {
    /// This function supports the 64-bit Integer Interface.
    ///
    /// This function performs the symmetric rank- $k$ update:
    /// $$
    /// C = \alpha\text{op}(A)\text{op}(A)^{T} + \beta C
    /// $$
    ///
    /// where $\alpha$ and $\beta$ are scalars, $C$ is a symmetric matrix stored in lower or upper mode, and $A$ is a matrix with dimensions $\text{op}(A)$ $n \times k$. Also, for matrix $A$:
    /// $$
    /// \text{op}(A) = \left\\{ \begin{matrix}
    /// A & {\text{if }\textsf{transa == $\mathrm{CUBLAS_OP_N}$}} \\\\
    /// A^{T} & {\text{if }\textsf{transa == $\mathrm{CUBLAS_OP_T}$}} \\\\
    /// \end{matrix} \right.
    /// $$
    ///
    /// For references please refer to NETLIB documentation:
    ///
    /// [ssyrk()](http://www.netlib.org/blas/ssyrk.f), [dsyrk()](http://www.netlib.org/blas/dsyrk.f), [csyrk()](http://www.netlib.org/blas/csyrk.f), [zsyrk()](http://www.netlib.org/blas/zsyrk.f).
    pub fn cublasXtSsyrk(
        handle: cublasXtHandle_t,
        uplo: cublasFillMode_t,
        trans: cublasOperation_t,
        n: size_t,
        k: size_t,
        alpha: *const f32,
        A: *const f32,
        lda: size_t,
        beta: *const f32,
        C: *mut f32,
        ldc: size_t,
    ) -> cublasStatus_t;
}
unsafe extern "C" {
    /// This function supports the 64-bit Integer Interface.
    ///
    /// This function performs the symmetric rank- $k$ update:
    /// $$
    /// C = \alpha\text{op}(A)\text{op}(A)^{T} + \beta C
    /// $$
    ///
    /// where $\alpha$ and $\beta$ are scalars, $C$ is a symmetric matrix stored in lower or upper mode, and $A$ is a matrix with dimensions $\text{op}(A)$ $n \times k$. Also, for matrix $A$:
    /// $$
    /// \text{op}(A) = \left\\{ \begin{matrix}
    /// A & {\text{if }\textsf{transa == $\mathrm{CUBLAS_OP_N}$}} \\\\
    /// A^{T} & {\text{if }\textsf{transa == $\mathrm{CUBLAS_OP_T}$}} \\\\
    /// \end{matrix} \right.
    /// $$
    ///
    /// For references please refer to NETLIB documentation:
    ///
    /// [ssyrk()](http://www.netlib.org/blas/ssyrk.f), [dsyrk()](http://www.netlib.org/blas/dsyrk.f), [csyrk()](http://www.netlib.org/blas/csyrk.f), [zsyrk()](http://www.netlib.org/blas/zsyrk.f).
    pub fn cublasXtDsyrk(
        handle: cublasXtHandle_t,
        uplo: cublasFillMode_t,
        trans: cublasOperation_t,
        n: size_t,
        k: size_t,
        alpha: *const f64,
        A: *const f64,
        lda: size_t,
        beta: *const f64,
        C: *mut f64,
        ldc: size_t,
    ) -> cublasStatus_t;
}
unsafe extern "C" {
    /// This function supports the 64-bit Integer Interface.
    ///
    /// This function performs the symmetric rank- $k$ update:
    /// $$
    /// C = \alpha\text{op}(A)\text{op}(A)^{T} + \beta C
    /// $$
    ///
    /// where $\alpha$ and $\beta$ are scalars, $C$ is a symmetric matrix stored in lower or upper mode, and $A$ is a matrix with dimensions $\text{op}(A)$ $n \times k$. Also, for matrix $A$:
    /// $$
    /// \text{op}(A) = \left\\{ \begin{matrix}
    /// A & {\text{if }\textsf{transa == $\mathrm{CUBLAS_OP_N}$}} \\\\
    /// A^{T} & {\text{if }\textsf{transa == $\mathrm{CUBLAS_OP_T}$}} \\\\
    /// \end{matrix} \right.
    /// $$
    ///
    /// For references please refer to NETLIB documentation:
    ///
    /// [ssyrk()](http://www.netlib.org/blas/ssyrk.f), [dsyrk()](http://www.netlib.org/blas/dsyrk.f), [csyrk()](http://www.netlib.org/blas/csyrk.f), [zsyrk()](http://www.netlib.org/blas/zsyrk.f).
    pub fn cublasXtCsyrk(
        handle: cublasXtHandle_t,
        uplo: cublasFillMode_t,
        trans: cublasOperation_t,
        n: size_t,
        k: size_t,
        alpha: *const cuComplex,
        A: *const cuComplex,
        lda: size_t,
        beta: *const cuComplex,
        C: *mut cuComplex,
        ldc: size_t,
    ) -> cublasStatus_t;
}
unsafe extern "C" {
    /// This function supports the 64-bit Integer Interface.
    ///
    /// This function performs the symmetric rank- $k$ update:
    /// $$
    /// C = \alpha\text{op}(A)\text{op}(A)^{T} + \beta C
    /// $$
    ///
    /// where $\alpha$ and $\beta$ are scalars, $C$ is a symmetric matrix stored in lower or upper mode, and $A$ is a matrix with dimensions $\text{op}(A)$ $n \times k$. Also, for matrix $A$:
    /// $$
    /// \text{op}(A) = \left\\{ \begin{matrix}
    /// A & {\text{if }\textsf{transa == $\mathrm{CUBLAS_OP_N}$}} \\\\
    /// A^{T} & {\text{if }\textsf{transa == $\mathrm{CUBLAS_OP_T}$}} \\\\
    /// \end{matrix} \right.
    /// $$
    ///
    /// For references please refer to NETLIB documentation:
    ///
    /// [ssyrk()](http://www.netlib.org/blas/ssyrk.f), [dsyrk()](http://www.netlib.org/blas/dsyrk.f), [csyrk()](http://www.netlib.org/blas/csyrk.f), [zsyrk()](http://www.netlib.org/blas/zsyrk.f).
    pub fn cublasXtZsyrk(
        handle: cublasXtHandle_t,
        uplo: cublasFillMode_t,
        trans: cublasOperation_t,
        n: size_t,
        k: size_t,
        alpha: *const cuDoubleComplex,
        A: *const cuDoubleComplex,
        lda: size_t,
        beta: *const cuDoubleComplex,
        C: *mut cuDoubleComplex,
        ldc: size_t,
    ) -> cublasStatus_t;
}
unsafe extern "C" {
    /// This function supports the 64-bit Integer Interface.
    ///
    /// This function performs the Hermitian rank- $k$ update:
    /// $$
    /// C = \alpha\text{op}(A)\text{op}(A)^{H} + \beta C
    /// $$
    ///
    /// where $\alpha$ and $\beta$ are scalars, $C$ is a Hermitian matrix stored in lower or upper mode, and $A$ is a matrix with dimensions $\text{op}(A)$ $n \times k$. Also, for matrix $A$:
    /// $$
    /// \text{op}(A) = \left\\{ \begin{matrix}
    /// A & {\text{if }\textsf{transa == $\mathrm{CUBLAS_OP_N}$}} \\\\
    /// A^{H} & {\text{if }\textsf{transa == $\mathrm{CUBLAS_OP_C}$}} \\\\
    /// \end{matrix} \right.
    /// $$
    ///
    /// For references please refer to NETLIB documentation:
    ///
    /// [cherk()](http://www.netlib.org/blas/cherk.f), [zherk()](http://www.netlib.org/blas/zherk.f).
    pub fn cublasXtCherk(
        handle: cublasXtHandle_t,
        uplo: cublasFillMode_t,
        trans: cublasOperation_t,
        n: size_t,
        k: size_t,
        alpha: *const f32,
        A: *const cuComplex,
        lda: size_t,
        beta: *const f32,
        C: *mut cuComplex,
        ldc: size_t,
    ) -> cublasStatus_t;
}
unsafe extern "C" {
    /// This function supports the 64-bit Integer Interface.
    ///
    /// This function performs the Hermitian rank- $k$ update:
    /// $$
    /// C = \alpha\text{op}(A)\text{op}(A)^{H} + \beta C
    /// $$
    ///
    /// where $\alpha$ and $\beta$ are scalars, $C$ is a Hermitian matrix stored in lower or upper mode, and $A$ is a matrix with dimensions $\text{op}(A)$ $n \times k$. Also, for matrix $A$:
    /// $$
    /// \text{op}(A) = \left\\{ \begin{matrix}
    /// A & {\text{if }\textsf{transa == $\mathrm{CUBLAS_OP_N}$}} \\\\
    /// A^{H} & {\text{if }\textsf{transa == $\mathrm{CUBLAS_OP_C}$}} \\\\
    /// \end{matrix} \right.
    /// $$
    ///
    /// For references please refer to NETLIB documentation:
    ///
    /// [cherk()](http://www.netlib.org/blas/cherk.f), [zherk()](http://www.netlib.org/blas/zherk.f).
    pub fn cublasXtZherk(
        handle: cublasXtHandle_t,
        uplo: cublasFillMode_t,
        trans: cublasOperation_t,
        n: size_t,
        k: size_t,
        alpha: *const f64,
        A: *const cuDoubleComplex,
        lda: size_t,
        beta: *const f64,
        C: *mut cuDoubleComplex,
        ldc: size_t,
    ) -> cublasStatus_t;
}
unsafe extern "C" {
    /// This function supports the 64-bit Integer Interface.
    ///
    /// This function performs the symmetric rank- $2k$ update:
    /// $$
    /// C = \alpha(\text{op}(A)\text{op}(B)^{T} + \text{op}(B)\text{op}(A)^{T}) + \beta C
    /// $$
    ///
    /// where $\alpha$ and $\beta$ are scalars, $C$ is a symmetric matrix stored in lower or upper mode, and $A$ and $B$ are matrices with dimensions $\text{op}(A)$ $n \times k$ and $\text{op}(B)$ $n \times k$, respectively. Also, for matrix $A$ and $B$:
    /// $$
    /// \text{op(}A\text{) and op(}B\text{)} = \left\\{ \begin{matrix}
    /// {A\text{ and }B} & {\text{if }\textsf{trans == $\mathrm{CUBLAS_OP_N}$}} \\\\
    /// {A^{T}\text{ and }B^{T}} & {\text{if }\textsf{trans == $\mathrm{CUBLAS_OP_T}$}} \\\\
    /// \end{matrix} \right.
    /// $$
    ///
    /// For references please refer to NETLIB documentation:
    ///
    /// [ssyr2k()](http://www.netlib.org/blas/ssyr2k.f), [dsyr2k()](http://www.netlib.org/blas/dsyr2k.f), [csyr2k()](http://www.netlib.org/blas/csyr2k.f), [zsyr2k()](http://www.netlib.org/blas/zsyr2k.f).
    pub fn cublasXtSsyr2k(
        handle: cublasXtHandle_t,
        uplo: cublasFillMode_t,
        trans: cublasOperation_t,
        n: size_t,
        k: size_t,
        alpha: *const f32,
        A: *const f32,
        lda: size_t,
        B: *const f32,
        ldb: size_t,
        beta: *const f32,
        C: *mut f32,
        ldc: size_t,
    ) -> cublasStatus_t;
}
unsafe extern "C" {
    /// This function supports the 64-bit Integer Interface.
    ///
    /// This function performs the symmetric rank- $2k$ update:
    /// $$
    /// C = \alpha(\text{op}(A)\text{op}(B)^{T} + \text{op}(B)\text{op}(A)^{T}) + \beta C
    /// $$
    ///
    /// where $\alpha$ and $\beta$ are scalars, $C$ is a symmetric matrix stored in lower or upper mode, and $A$ and $B$ are matrices with dimensions $\text{op}(A)$ $n \times k$ and $\text{op}(B)$ $n \times k$, respectively. Also, for matrix $A$ and $B$:
    /// $$
    /// \text{op(}A\text{) and op(}B\text{)} = \left\\{ \begin{matrix}
    /// {A\text{ and }B} & {\text{if }\textsf{trans == $\mathrm{CUBLAS_OP_N}$}} \\\\
    /// {A^{T}\text{ and }B^{T}} & {\text{if }\textsf{trans == $\mathrm{CUBLAS_OP_T}$}} \\\\
    /// \end{matrix} \right.
    /// $$
    ///
    /// For references please refer to NETLIB documentation:
    ///
    /// [ssyr2k()](http://www.netlib.org/blas/ssyr2k.f), [dsyr2k()](http://www.netlib.org/blas/dsyr2k.f), [csyr2k()](http://www.netlib.org/blas/csyr2k.f), [zsyr2k()](http://www.netlib.org/blas/zsyr2k.f).
    pub fn cublasXtDsyr2k(
        handle: cublasXtHandle_t,
        uplo: cublasFillMode_t,
        trans: cublasOperation_t,
        n: size_t,
        k: size_t,
        alpha: *const f64,
        A: *const f64,
        lda: size_t,
        B: *const f64,
        ldb: size_t,
        beta: *const f64,
        C: *mut f64,
        ldc: size_t,
    ) -> cublasStatus_t;
}
unsafe extern "C" {
    /// This function supports the 64-bit Integer Interface.
    ///
    /// This function performs the symmetric rank- $2k$ update:
    /// $$
    /// C = \alpha(\text{op}(A)\text{op}(B)^{T} + \text{op}(B)\text{op}(A)^{T}) + \beta C
    /// $$
    ///
    /// where $\alpha$ and $\beta$ are scalars, $C$ is a symmetric matrix stored in lower or upper mode, and $A$ and $B$ are matrices with dimensions $\text{op}(A)$ $n \times k$ and $\text{op}(B)$ $n \times k$, respectively. Also, for matrix $A$ and $B$:
    /// $$
    /// \text{op(}A\text{) and op(}B\text{)} = \left\\{ \begin{matrix}
    /// {A\text{ and }B} & {\text{if }\textsf{trans == $\mathrm{CUBLAS_OP_N}$}} \\\\
    /// {A^{T}\text{ and }B^{T}} & {\text{if }\textsf{trans == $\mathrm{CUBLAS_OP_T}$}} \\\\
    /// \end{matrix} \right.
    /// $$
    ///
    /// For references please refer to NETLIB documentation:
    ///
    /// [ssyr2k()](http://www.netlib.org/blas/ssyr2k.f), [dsyr2k()](http://www.netlib.org/blas/dsyr2k.f), [csyr2k()](http://www.netlib.org/blas/csyr2k.f), [zsyr2k()](http://www.netlib.org/blas/zsyr2k.f).
    pub fn cublasXtCsyr2k(
        handle: cublasXtHandle_t,
        uplo: cublasFillMode_t,
        trans: cublasOperation_t,
        n: size_t,
        k: size_t,
        alpha: *const cuComplex,
        A: *const cuComplex,
        lda: size_t,
        B: *const cuComplex,
        ldb: size_t,
        beta: *const cuComplex,
        C: *mut cuComplex,
        ldc: size_t,
    ) -> cublasStatus_t;
}
unsafe extern "C" {
    /// This function supports the 64-bit Integer Interface.
    ///
    /// This function performs the symmetric rank- $2k$ update:
    /// $$
    /// C = \alpha(\text{op}(A)\text{op}(B)^{T} + \text{op}(B)\text{op}(A)^{T}) + \beta C
    /// $$
    ///
    /// where $\alpha$ and $\beta$ are scalars, $C$ is a symmetric matrix stored in lower or upper mode, and $A$ and $B$ are matrices with dimensions $\text{op}(A)$ $n \times k$ and $\text{op}(B)$ $n \times k$, respectively. Also, for matrix $A$ and $B$:
    /// $$
    /// \text{op(}A\text{) and op(}B\text{)} = \left\\{ \begin{matrix}
    /// {A\text{ and }B} & {\text{if }\textsf{trans == $\mathrm{CUBLAS_OP_N}$}} \\\\
    /// {A^{T}\text{ and }B^{T}} & {\text{if }\textsf{trans == $\mathrm{CUBLAS_OP_T}$}} \\\\
    /// \end{matrix} \right.
    /// $$
    ///
    /// For references please refer to NETLIB documentation:
    ///
    /// [ssyr2k()](http://www.netlib.org/blas/ssyr2k.f), [dsyr2k()](http://www.netlib.org/blas/dsyr2k.f), [csyr2k()](http://www.netlib.org/blas/csyr2k.f), [zsyr2k()](http://www.netlib.org/blas/zsyr2k.f).
    pub fn cublasXtZsyr2k(
        handle: cublasXtHandle_t,
        uplo: cublasFillMode_t,
        trans: cublasOperation_t,
        n: size_t,
        k: size_t,
        alpha: *const cuDoubleComplex,
        A: *const cuDoubleComplex,
        lda: size_t,
        B: *const cuDoubleComplex,
        ldb: size_t,
        beta: *const cuDoubleComplex,
        C: *mut cuDoubleComplex,
        ldc: size_t,
    ) -> cublasStatus_t;
}
unsafe extern "C" {
    /// This function supports the 64-bit Integer Interface.
    ///
    /// This function performs a variation of the Hermitian rank- $k$ update:
    /// $$
    /// C = \alpha\text{op}(A)\text{op}(B)^{H} + \beta C
    /// $$
    ///
    /// where $\alpha$ and $\beta$ are scalars, $C$ is a Hermitian matrix stored in lower or upper mode, and $A$ and $B$ are matrices with dimensions $\text{op}(A)$ $n \times k$ and $\text{op}(B)$ $n \times k$, respectively. Also, for matrix $A$ and $B$:
    /// $$
    /// \text{op(}A\text{) and op(}B\text{)} = \left\\{ \begin{matrix}
    /// {A\text{ and }B} & {\text{if }\textsf{trans == $\mathrm{CUBLAS_OP_N}$}} \\\\
    /// {A^{H}\text{ and }B^{H}} & {\text{if }\textsf{trans == $\mathrm{CUBLAS_OP_C}$}} \\\\
    /// \end{matrix} \right.
    /// $$
    ///
    /// This routine can be used when the matrix B is in such way that the result is guaranteed to be hermitian. An usual example is when the matrix B is a scaled form of the matrix A: this is equivalent to B being the product of the matrix A and a diagonal matrix. For an efficient computation of the product of a regular matrix with a diagonal matrix, refer to the routine cublas&lt;t>dgmm().
    ///
    /// For references please refer to NETLIB documentation:
    ///
    /// [cherk()](http://www.netlib.org/blas/cherk.f), [zherk()](http://www.netlib.org/blas/zherk.f) and
    ///
    /// [cher2k()](http://www.netlib.org/blas/cher2k.f), [zher2k()](http://www.netlib.org/blas/zher2k.f).
    pub fn cublasXtCherkx(
        handle: cublasXtHandle_t,
        uplo: cublasFillMode_t,
        trans: cublasOperation_t,
        n: size_t,
        k: size_t,
        alpha: *const cuComplex,
        A: *const cuComplex,
        lda: size_t,
        B: *const cuComplex,
        ldb: size_t,
        beta: *const f32,
        C: *mut cuComplex,
        ldc: size_t,
    ) -> cublasStatus_t;
}
unsafe extern "C" {
    /// This function supports the 64-bit Integer Interface.
    ///
    /// This function performs a variation of the Hermitian rank- $k$ update:
    /// $$
    /// C = \alpha\text{op}(A)\text{op}(B)^{H} + \beta C
    /// $$
    ///
    /// where $\alpha$ and $\beta$ are scalars, $C$ is a Hermitian matrix stored in lower or upper mode, and $A$ and $B$ are matrices with dimensions $\text{op}(A)$ $n \times k$ and $\text{op}(B)$ $n \times k$, respectively. Also, for matrix $A$ and $B$:
    /// $$
    /// \text{op(}A\text{) and op(}B\text{)} = \left\\{ \begin{matrix}
    /// {A\text{ and }B} & {\text{if }\textsf{trans == $\mathrm{CUBLAS_OP_N}$}} \\\\
    /// {A^{H}\text{ and }B^{H}} & {\text{if }\textsf{trans == $\mathrm{CUBLAS_OP_C}$}} \\\\
    /// \end{matrix} \right.
    /// $$
    ///
    /// This routine can be used when the matrix B is in such way that the result is guaranteed to be hermitian. An usual example is when the matrix B is a scaled form of the matrix A: this is equivalent to B being the product of the matrix A and a diagonal matrix. For an efficient computation of the product of a regular matrix with a diagonal matrix, refer to the routine cublas&lt;t>dgmm().
    ///
    /// For references please refer to NETLIB documentation:
    ///
    /// [cherk()](http://www.netlib.org/blas/cherk.f), [zherk()](http://www.netlib.org/blas/zherk.f) and
    ///
    /// [cher2k()](http://www.netlib.org/blas/cher2k.f), [zher2k()](http://www.netlib.org/blas/zher2k.f).
    pub fn cublasXtZherkx(
        handle: cublasXtHandle_t,
        uplo: cublasFillMode_t,
        trans: cublasOperation_t,
        n: size_t,
        k: size_t,
        alpha: *const cuDoubleComplex,
        A: *const cuDoubleComplex,
        lda: size_t,
        B: *const cuDoubleComplex,
        ldb: size_t,
        beta: *const f64,
        C: *mut cuDoubleComplex,
        ldc: size_t,
    ) -> cublasStatus_t;
}
unsafe extern "C" {
    /// This function supports the 64-bit Integer Interface.
    ///
    /// This function solves the triangular linear system with multiple right-hand-sides:
    /// $$
    /// \left\\{ \begin{matrix}
    /// {\text{op}(A)X = \alpha B} & {\text{if }\textsf{side == $\mathrm{CUBLAS_SIDE_LEFT}$}} \\\\
    /// {X\text{op}(A) = \alpha B} & {\text{if }\textsf{side == $\mathrm{CUBLAS_SIDE_RIGHT}$}} \\\\
    /// \end{matrix} \right.
    /// $$
    ///
    /// where $A$ is a triangular matrix stored in lower or upper mode with or without the main diagonal, $X$ and $B$ are $m \times n$ matrices, and $\alpha$ is a scalar. Also, for matrix $A$:
    /// $$
    /// \text{op}(A) = \left\\{ \begin{matrix}
    /// A & {\text{if }\textsf{transa == $\mathrm{CUBLAS_OP_N}$}} \\\\
    /// A^{T} & {\text{if }\textsf{transa == $\mathrm{CUBLAS_OP_T}$}} \\\\
    /// A^{H} & {\text{if }\textsf{transa == $\mathrm{CUBLAS_OP_C}$}} \\\\
    /// \end{matrix} \right.
    /// $$
    ///
    /// The solution $X$ overwrites the right-hand-sides $B$ on exit.
    ///
    /// No test for singularity or near-singularity is included in this function.
    ///
    /// For references please refer to NETLIB documentation:
    ///
    /// [strsm()](http://www.netlib.org/blas/strsm.f), [dtrsm()](http://www.netlib.org/blas/dtrsm.f), [ctrsm()](http://www.netlib.org/blas/ctrsm.f), [ztrsm()](http://www.netlib.org/blas/ztrsm.f).
    pub fn cublasXtStrsm(
        handle: cublasXtHandle_t,
        side: cublasSideMode_t,
        uplo: cublasFillMode_t,
        trans: cublasOperation_t,
        diag: cublasDiagType_t,
        m: size_t,
        n: size_t,
        alpha: *const f32,
        A: *const f32,
        lda: size_t,
        B: *mut f32,
        ldb: size_t,
    ) -> cublasStatus_t;
}
unsafe extern "C" {
    /// This function supports the 64-bit Integer Interface.
    ///
    /// This function solves the triangular linear system with multiple right-hand-sides:
    /// $$
    /// \left\\{ \begin{matrix}
    /// {\text{op}(A)X = \alpha B} & {\text{if }\textsf{side == $\mathrm{CUBLAS_SIDE_LEFT}$}} \\\\
    /// {X\text{op}(A) = \alpha B} & {\text{if }\textsf{side == $\mathrm{CUBLAS_SIDE_RIGHT}$}} \\\\
    /// \end{matrix} \right.
    /// $$
    ///
    /// where $A$ is a triangular matrix stored in lower or upper mode with or without the main diagonal, $X$ and $B$ are $m \times n$ matrices, and $\alpha$ is a scalar. Also, for matrix $A$:
    /// $$
    /// \text{op}(A) = \left\\{ \begin{matrix}
    /// A & {\text{if }\textsf{transa == $\mathrm{CUBLAS_OP_N}$}} \\\\
    /// A^{T} & {\text{if }\textsf{transa == $\mathrm{CUBLAS_OP_T}$}} \\\\
    /// A^{H} & {\text{if }\textsf{transa == $\mathrm{CUBLAS_OP_C}$}} \\\\
    /// \end{matrix} \right.
    /// $$
    ///
    /// The solution $X$ overwrites the right-hand-sides $B$ on exit.
    ///
    /// No test for singularity or near-singularity is included in this function.
    ///
    /// For references please refer to NETLIB documentation:
    ///
    /// [strsm()](http://www.netlib.org/blas/strsm.f), [dtrsm()](http://www.netlib.org/blas/dtrsm.f), [ctrsm()](http://www.netlib.org/blas/ctrsm.f), [ztrsm()](http://www.netlib.org/blas/ztrsm.f).
    pub fn cublasXtDtrsm(
        handle: cublasXtHandle_t,
        side: cublasSideMode_t,
        uplo: cublasFillMode_t,
        trans: cublasOperation_t,
        diag: cublasDiagType_t,
        m: size_t,
        n: size_t,
        alpha: *const f64,
        A: *const f64,
        lda: size_t,
        B: *mut f64,
        ldb: size_t,
    ) -> cublasStatus_t;
}
unsafe extern "C" {
    /// This function supports the 64-bit Integer Interface.
    ///
    /// This function solves the triangular linear system with multiple right-hand-sides:
    /// $$
    /// \left\\{ \begin{matrix}
    /// {\text{op}(A)X = \alpha B} & {\text{if }\textsf{side == $\mathrm{CUBLAS_SIDE_LEFT}$}} \\\\
    /// {X\text{op}(A) = \alpha B} & {\text{if }\textsf{side == $\mathrm{CUBLAS_SIDE_RIGHT}$}} \\\\
    /// \end{matrix} \right.
    /// $$
    ///
    /// where $A$ is a triangular matrix stored in lower or upper mode with or without the main diagonal, $X$ and $B$ are $m \times n$ matrices, and $\alpha$ is a scalar. Also, for matrix $A$:
    /// $$
    /// \text{op}(A) = \left\\{ \begin{matrix}
    /// A & {\text{if }\textsf{transa == $\mathrm{CUBLAS_OP_N}$}} \\\\
    /// A^{T} & {\text{if }\textsf{transa == $\mathrm{CUBLAS_OP_T}$}} \\\\
    /// A^{H} & {\text{if }\textsf{transa == $\mathrm{CUBLAS_OP_C}$}} \\\\
    /// \end{matrix} \right.
    /// $$
    ///
    /// The solution $X$ overwrites the right-hand-sides $B$ on exit.
    ///
    /// No test for singularity or near-singularity is included in this function.
    ///
    /// For references please refer to NETLIB documentation:
    ///
    /// [strsm()](http://www.netlib.org/blas/strsm.f), [dtrsm()](http://www.netlib.org/blas/dtrsm.f), [ctrsm()](http://www.netlib.org/blas/ctrsm.f), [ztrsm()](http://www.netlib.org/blas/ztrsm.f).
    pub fn cublasXtCtrsm(
        handle: cublasXtHandle_t,
        side: cublasSideMode_t,
        uplo: cublasFillMode_t,
        trans: cublasOperation_t,
        diag: cublasDiagType_t,
        m: size_t,
        n: size_t,
        alpha: *const cuComplex,
        A: *const cuComplex,
        lda: size_t,
        B: *mut cuComplex,
        ldb: size_t,
    ) -> cublasStatus_t;
}
unsafe extern "C" {
    /// This function supports the 64-bit Integer Interface.
    ///
    /// This function solves the triangular linear system with multiple right-hand-sides:
    /// $$
    /// \left\\{ \begin{matrix}
    /// {\text{op}(A)X = \alpha B} & {\text{if }\textsf{side == $\mathrm{CUBLAS_SIDE_LEFT}$}} \\\\
    /// {X\text{op}(A) = \alpha B} & {\text{if }\textsf{side == $\mathrm{CUBLAS_SIDE_RIGHT}$}} \\\\
    /// \end{matrix} \right.
    /// $$
    ///
    /// where $A$ is a triangular matrix stored in lower or upper mode with or without the main diagonal, $X$ and $B$ are $m \times n$ matrices, and $\alpha$ is a scalar. Also, for matrix $A$:
    /// $$
    /// \text{op}(A) = \left\\{ \begin{matrix}
    /// A & {\text{if }\textsf{transa == $\mathrm{CUBLAS_OP_N}$}} \\\\
    /// A^{T} & {\text{if }\textsf{transa == $\mathrm{CUBLAS_OP_T}$}} \\\\
    /// A^{H} & {\text{if }\textsf{transa == $\mathrm{CUBLAS_OP_C}$}} \\\\
    /// \end{matrix} \right.
    /// $$
    ///
    /// The solution $X$ overwrites the right-hand-sides $B$ on exit.
    ///
    /// No test for singularity or near-singularity is included in this function.
    ///
    /// For references please refer to NETLIB documentation:
    ///
    /// [strsm()](http://www.netlib.org/blas/strsm.f), [dtrsm()](http://www.netlib.org/blas/dtrsm.f), [ctrsm()](http://www.netlib.org/blas/ctrsm.f), [ztrsm()](http://www.netlib.org/blas/ztrsm.f).
    pub fn cublasXtZtrsm(
        handle: cublasXtHandle_t,
        side: cublasSideMode_t,
        uplo: cublasFillMode_t,
        trans: cublasOperation_t,
        diag: cublasDiagType_t,
        m: size_t,
        n: size_t,
        alpha: *const cuDoubleComplex,
        A: *const cuDoubleComplex,
        lda: size_t,
        B: *mut cuDoubleComplex,
        ldb: size_t,
    ) -> cublasStatus_t;
}
unsafe extern "C" {
    /// This function supports the 64-bit Integer Interface.
    ///
    /// This function performs the symmetric matrix-matrix multiplication:
    /// $$
    /// C = \left\\{ \begin{matrix}
    /// {\alpha AB + \beta C} & {\text{if }\textsf{side == $\mathrm{CUBLAS_SIDE_LEFT}$}} \\\\
    /// {\alpha BA + \beta C} & {\text{if }\textsf{side == $\mathrm{CUBLAS_SIDE_RIGHT}$}} \\\\
    /// \end{matrix} \right.
    /// $$
    ///
    /// where $A$ is a symmetric matrix stored in lower or upper mode, $B$ and $C$ are $m \times n$ matrices, and $\alpha$ and $\beta$ are scalars.
    ///
    /// For references please refer to NETLIB documentation:
    ///
    /// [ssymm()](http://www.netlib.org/blas/ssymm.f), [dsymm()](http://www.netlib.org/blas/dsymm.f), [csymm()](http://www.netlib.org/blas/csymm.f), [zsymm()](http://www.netlib.org/blas/zsymm.f).
    pub fn cublasXtSsymm(
        handle: cublasXtHandle_t,
        side: cublasSideMode_t,
        uplo: cublasFillMode_t,
        m: size_t,
        n: size_t,
        alpha: *const f32,
        A: *const f32,
        lda: size_t,
        B: *const f32,
        ldb: size_t,
        beta: *const f32,
        C: *mut f32,
        ldc: size_t,
    ) -> cublasStatus_t;
}
unsafe extern "C" {
    /// This function supports the 64-bit Integer Interface.
    ///
    /// This function performs the symmetric matrix-matrix multiplication:
    /// $$
    /// C = \left\\{ \begin{matrix}
    /// {\alpha AB + \beta C} & {\text{if }\textsf{side == $\mathrm{CUBLAS_SIDE_LEFT}$}} \\\\
    /// {\alpha BA + \beta C} & {\text{if }\textsf{side == $\mathrm{CUBLAS_SIDE_RIGHT}$}} \\\\
    /// \end{matrix} \right.
    /// $$
    ///
    /// where $A$ is a symmetric matrix stored in lower or upper mode, $B$ and $C$ are $m \times n$ matrices, and $\alpha$ and $\beta$ are scalars.
    ///
    /// For references please refer to NETLIB documentation:
    ///
    /// [ssymm()](http://www.netlib.org/blas/ssymm.f), [dsymm()](http://www.netlib.org/blas/dsymm.f), [csymm()](http://www.netlib.org/blas/csymm.f), [zsymm()](http://www.netlib.org/blas/zsymm.f).
    pub fn cublasXtDsymm(
        handle: cublasXtHandle_t,
        side: cublasSideMode_t,
        uplo: cublasFillMode_t,
        m: size_t,
        n: size_t,
        alpha: *const f64,
        A: *const f64,
        lda: size_t,
        B: *const f64,
        ldb: size_t,
        beta: *const f64,
        C: *mut f64,
        ldc: size_t,
    ) -> cublasStatus_t;
}
unsafe extern "C" {
    /// This function supports the 64-bit Integer Interface.
    ///
    /// This function performs the symmetric matrix-matrix multiplication:
    /// $$
    /// C = \left\\{ \begin{matrix}
    /// {\alpha AB + \beta C} & {\text{if }\textsf{side == $\mathrm{CUBLAS_SIDE_LEFT}$}} \\\\
    /// {\alpha BA + \beta C} & {\text{if }\textsf{side == $\mathrm{CUBLAS_SIDE_RIGHT}$}} \\\\
    /// \end{matrix} \right.
    /// $$
    ///
    /// where $A$ is a symmetric matrix stored in lower or upper mode, $B$ and $C$ are $m \times n$ matrices, and $\alpha$ and $\beta$ are scalars.
    ///
    /// For references please refer to NETLIB documentation:
    ///
    /// [ssymm()](http://www.netlib.org/blas/ssymm.f), [dsymm()](http://www.netlib.org/blas/dsymm.f), [csymm()](http://www.netlib.org/blas/csymm.f), [zsymm()](http://www.netlib.org/blas/zsymm.f).
    pub fn cublasXtCsymm(
        handle: cublasXtHandle_t,
        side: cublasSideMode_t,
        uplo: cublasFillMode_t,
        m: size_t,
        n: size_t,
        alpha: *const cuComplex,
        A: *const cuComplex,
        lda: size_t,
        B: *const cuComplex,
        ldb: size_t,
        beta: *const cuComplex,
        C: *mut cuComplex,
        ldc: size_t,
    ) -> cublasStatus_t;
}
unsafe extern "C" {
    /// This function supports the 64-bit Integer Interface.
    ///
    /// This function performs the symmetric matrix-matrix multiplication:
    /// $$
    /// C = \left\\{ \begin{matrix}
    /// {\alpha AB + \beta C} & {\text{if }\textsf{side == $\mathrm{CUBLAS_SIDE_LEFT}$}} \\\\
    /// {\alpha BA + \beta C} & {\text{if }\textsf{side == $\mathrm{CUBLAS_SIDE_RIGHT}$}} \\\\
    /// \end{matrix} \right.
    /// $$
    ///
    /// where $A$ is a symmetric matrix stored in lower or upper mode, $B$ and $C$ are $m \times n$ matrices, and $\alpha$ and $\beta$ are scalars.
    ///
    /// For references please refer to NETLIB documentation:
    ///
    /// [ssymm()](http://www.netlib.org/blas/ssymm.f), [dsymm()](http://www.netlib.org/blas/dsymm.f), [csymm()](http://www.netlib.org/blas/csymm.f), [zsymm()](http://www.netlib.org/blas/zsymm.f).
    pub fn cublasXtZsymm(
        handle: cublasXtHandle_t,
        side: cublasSideMode_t,
        uplo: cublasFillMode_t,
        m: size_t,
        n: size_t,
        alpha: *const cuDoubleComplex,
        A: *const cuDoubleComplex,
        lda: size_t,
        B: *const cuDoubleComplex,
        ldb: size_t,
        beta: *const cuDoubleComplex,
        C: *mut cuDoubleComplex,
        ldc: size_t,
    ) -> cublasStatus_t;
}
unsafe extern "C" {
    /// This function supports the 64-bit Integer Interface.
    ///
    /// This function performs the Hermitian matrix-matrix multiplication:
    /// $$
    /// C = \left\\{ \begin{matrix}
    /// {\alpha AB + \beta C} & {\text{if }\textsf{side == $\mathrm{CUBLAS_SIDE_LEFT}$}} \\\\
    /// {\alpha BA + \beta C} & {\text{if }\textsf{side == $\mathrm{CUBLAS_SIDE_RIGHT}$}} \\\\
    /// \end{matrix} \right.
    /// $$
    ///
    /// where $A$ is a Hermitian matrix stored in lower or upper mode, $B$ and $C$ are $m \times n$ matrices, and $\alpha$ and $\beta$ are scalars.
    ///
    /// For references please refer to NETLIB documentation:
    ///
    /// [chemm()](http://www.netlib.org/blas/chemm.f), [zhemm()](http://www.netlib.org/blas/zhemm.f).
    pub fn cublasXtChemm(
        handle: cublasXtHandle_t,
        side: cublasSideMode_t,
        uplo: cublasFillMode_t,
        m: size_t,
        n: size_t,
        alpha: *const cuComplex,
        A: *const cuComplex,
        lda: size_t,
        B: *const cuComplex,
        ldb: size_t,
        beta: *const cuComplex,
        C: *mut cuComplex,
        ldc: size_t,
    ) -> cublasStatus_t;
}
unsafe extern "C" {
    /// This function supports the 64-bit Integer Interface.
    ///
    /// This function performs the Hermitian matrix-matrix multiplication:
    /// $$
    /// C = \left\\{ \begin{matrix}
    /// {\alpha AB + \beta C} & {\text{if }\textsf{side == $\mathrm{CUBLAS_SIDE_LEFT}$}} \\\\
    /// {\alpha BA + \beta C} & {\text{if }\textsf{side == $\mathrm{CUBLAS_SIDE_RIGHT}$}} \\\\
    /// \end{matrix} \right.
    /// $$
    ///
    /// where $A$ is a Hermitian matrix stored in lower or upper mode, $B$ and $C$ are $m \times n$ matrices, and $\alpha$ and $\beta$ are scalars.
    ///
    /// For references please refer to NETLIB documentation:
    ///
    /// [chemm()](http://www.netlib.org/blas/chemm.f), [zhemm()](http://www.netlib.org/blas/zhemm.f).
    pub fn cublasXtZhemm(
        handle: cublasXtHandle_t,
        side: cublasSideMode_t,
        uplo: cublasFillMode_t,
        m: size_t,
        n: size_t,
        alpha: *const cuDoubleComplex,
        A: *const cuDoubleComplex,
        lda: size_t,
        B: *const cuDoubleComplex,
        ldb: size_t,
        beta: *const cuDoubleComplex,
        C: *mut cuDoubleComplex,
        ldc: size_t,
    ) -> cublasStatus_t;
}
unsafe extern "C" {
    /// This function supports the 64-bit Integer Interface.
    ///
    /// This function performs a variation of the symmetric rank- $k$ update:
    /// $$
    /// C = \alpha\text{op}(A)\text{op}(B)^{T} + \beta C
    /// $$
    ///
    /// where $\alpha$ and $\beta$ are scalars, $C$ is a symmetric matrix stored in lower or upper mode, and $A$ and $B$ are matrices with dimensions $\text{op}(A)$ $n \times k$ and $\text{op}(B)$ $n \times k$, respectively. Also, for matrices $A$ and $B$:
    /// $$
    /// \text{op(}A\text{) and op(}B\text{)} = \left\\{ \begin{matrix}
    /// {A\text{ and }B} & {\text{if }\textsf{trans == $\mathrm{CUBLAS_OP_N}$}} \\\\
    /// {A^{T}\text{ and }B^{T}} & {\text{if }\textsf{trans == $\mathrm{CUBLAS_OP_T}$}} \\\\
    /// \end{matrix} \right.
    /// $$
    ///
    /// This routine can be used when B is in such way that the result is guaranteed to be symmetric. A usual example is when the matrix B is a scaled form of the matrix A: this is equivalent to B being the product of the matrix A and a diagonal matrix. For an efficient computation of the product of a regular matrix with a diagonal matrix, refer to the routine cublas&lt;t>dgmm().
    ///
    /// For references please refer to NETLIB documentation:
    ///
    /// [ssyrk()](http://www.netlib.org/blas/ssyrk.f), [dsyrk()](http://www.netlib.org/blas/dsyrk.f), [csyrk()](http://www.netlib.org/blas/csyrk.f), [zsyrk()](http://www.netlib.org/blas/zsyrk.f) and
    ///
    /// [ssyr2k()](http://www.netlib.org/blas/ssyr2k.f), [dsyr2k()](http://www.netlib.org/blas/dsyr2k.f), [csyr2k()](http://www.netlib.org/blas/csyr2k.f), [zsyr2k()](http://www.netlib.org/blas/zsyr2k.f).
    pub fn cublasXtSsyrkx(
        handle: cublasXtHandle_t,
        uplo: cublasFillMode_t,
        trans: cublasOperation_t,
        n: size_t,
        k: size_t,
        alpha: *const f32,
        A: *const f32,
        lda: size_t,
        B: *const f32,
        ldb: size_t,
        beta: *const f32,
        C: *mut f32,
        ldc: size_t,
    ) -> cublasStatus_t;
}
unsafe extern "C" {
    /// This function supports the 64-bit Integer Interface.
    ///
    /// This function performs a variation of the symmetric rank- $k$ update:
    /// $$
    /// C = \alpha\text{op}(A)\text{op}(B)^{T} + \beta C
    /// $$
    ///
    /// where $\alpha$ and $\beta$ are scalars, $C$ is a symmetric matrix stored in lower or upper mode, and $A$ and $B$ are matrices with dimensions $\text{op}(A)$ $n \times k$ and $\text{op}(B)$ $n \times k$, respectively. Also, for matrices $A$ and $B$:
    /// $$
    /// \text{op(}A\text{) and op(}B\text{)} = \left\\{ \begin{matrix}
    /// {A\text{ and }B} & {\text{if }\textsf{trans == $\mathrm{CUBLAS_OP_N}$}} \\\\
    /// {A^{T}\text{ and }B^{T}} & {\text{if }\textsf{trans == $\mathrm{CUBLAS_OP_T}$}} \\\\
    /// \end{matrix} \right.
    /// $$
    ///
    /// This routine can be used when B is in such way that the result is guaranteed to be symmetric. A usual example is when the matrix B is a scaled form of the matrix A: this is equivalent to B being the product of the matrix A and a diagonal matrix. For an efficient computation of the product of a regular matrix with a diagonal matrix, refer to the routine cublas&lt;t>dgmm().
    ///
    /// For references please refer to NETLIB documentation:
    ///
    /// [ssyrk()](http://www.netlib.org/blas/ssyrk.f), [dsyrk()](http://www.netlib.org/blas/dsyrk.f), [csyrk()](http://www.netlib.org/blas/csyrk.f), [zsyrk()](http://www.netlib.org/blas/zsyrk.f) and
    ///
    /// [ssyr2k()](http://www.netlib.org/blas/ssyr2k.f), [dsyr2k()](http://www.netlib.org/blas/dsyr2k.f), [csyr2k()](http://www.netlib.org/blas/csyr2k.f), [zsyr2k()](http://www.netlib.org/blas/zsyr2k.f).
    pub fn cublasXtDsyrkx(
        handle: cublasXtHandle_t,
        uplo: cublasFillMode_t,
        trans: cublasOperation_t,
        n: size_t,
        k: size_t,
        alpha: *const f64,
        A: *const f64,
        lda: size_t,
        B: *const f64,
        ldb: size_t,
        beta: *const f64,
        C: *mut f64,
        ldc: size_t,
    ) -> cublasStatus_t;
}
unsafe extern "C" {
    /// This function supports the 64-bit Integer Interface.
    ///
    /// This function performs a variation of the symmetric rank- $k$ update:
    /// $$
    /// C = \alpha\text{op}(A)\text{op}(B)^{T} + \beta C
    /// $$
    ///
    /// where $\alpha$ and $\beta$ are scalars, $C$ is a symmetric matrix stored in lower or upper mode, and $A$ and $B$ are matrices with dimensions $\text{op}(A)$ $n \times k$ and $\text{op}(B)$ $n \times k$, respectively. Also, for matrices $A$ and $B$:
    /// $$
    /// \text{op(}A\text{) and op(}B\text{)} = \left\\{ \begin{matrix}
    /// {A\text{ and }B} & {\text{if }\textsf{trans == $\mathrm{CUBLAS_OP_N}$}} \\\\
    /// {A^{T}\text{ and }B^{T}} & {\text{if }\textsf{trans == $\mathrm{CUBLAS_OP_T}$}} \\\\
    /// \end{matrix} \right.
    /// $$
    ///
    /// This routine can be used when B is in such way that the result is guaranteed to be symmetric. A usual example is when the matrix B is a scaled form of the matrix A: this is equivalent to B being the product of the matrix A and a diagonal matrix. For an efficient computation of the product of a regular matrix with a diagonal matrix, refer to the routine cublas&lt;t>dgmm().
    ///
    /// For references please refer to NETLIB documentation:
    ///
    /// [ssyrk()](http://www.netlib.org/blas/ssyrk.f), [dsyrk()](http://www.netlib.org/blas/dsyrk.f), [csyrk()](http://www.netlib.org/blas/csyrk.f), [zsyrk()](http://www.netlib.org/blas/zsyrk.f) and
    ///
    /// [ssyr2k()](http://www.netlib.org/blas/ssyr2k.f), [dsyr2k()](http://www.netlib.org/blas/dsyr2k.f), [csyr2k()](http://www.netlib.org/blas/csyr2k.f), [zsyr2k()](http://www.netlib.org/blas/zsyr2k.f).
    pub fn cublasXtCsyrkx(
        handle: cublasXtHandle_t,
        uplo: cublasFillMode_t,
        trans: cublasOperation_t,
        n: size_t,
        k: size_t,
        alpha: *const cuComplex,
        A: *const cuComplex,
        lda: size_t,
        B: *const cuComplex,
        ldb: size_t,
        beta: *const cuComplex,
        C: *mut cuComplex,
        ldc: size_t,
    ) -> cublasStatus_t;
}
unsafe extern "C" {
    /// This function supports the 64-bit Integer Interface.
    ///
    /// This function performs a variation of the symmetric rank- $k$ update:
    /// $$
    /// C = \alpha\text{op}(A)\text{op}(B)^{T} + \beta C
    /// $$
    ///
    /// where $\alpha$ and $\beta$ are scalars, $C$ is a symmetric matrix stored in lower or upper mode, and $A$ and $B$ are matrices with dimensions $\text{op}(A)$ $n \times k$ and $\text{op}(B)$ $n \times k$, respectively. Also, for matrices $A$ and $B$:
    /// $$
    /// \text{op(}A\text{) and op(}B\text{)} = \left\\{ \begin{matrix}
    /// {A\text{ and }B} & {\text{if }\textsf{trans == $\mathrm{CUBLAS_OP_N}$}} \\\\
    /// {A^{T}\text{ and }B^{T}} & {\text{if }\textsf{trans == $\mathrm{CUBLAS_OP_T}$}} \\\\
    /// \end{matrix} \right.
    /// $$
    ///
    /// This routine can be used when B is in such way that the result is guaranteed to be symmetric. A usual example is when the matrix B is a scaled form of the matrix A: this is equivalent to B being the product of the matrix A and a diagonal matrix. For an efficient computation of the product of a regular matrix with a diagonal matrix, refer to the routine cublas&lt;t>dgmm().
    ///
    /// For references please refer to NETLIB documentation:
    ///
    /// [ssyrk()](http://www.netlib.org/blas/ssyrk.f), [dsyrk()](http://www.netlib.org/blas/dsyrk.f), [csyrk()](http://www.netlib.org/blas/csyrk.f), [zsyrk()](http://www.netlib.org/blas/zsyrk.f) and
    ///
    /// [ssyr2k()](http://www.netlib.org/blas/ssyr2k.f), [dsyr2k()](http://www.netlib.org/blas/dsyr2k.f), [csyr2k()](http://www.netlib.org/blas/csyr2k.f), [zsyr2k()](http://www.netlib.org/blas/zsyr2k.f).
    pub fn cublasXtZsyrkx(
        handle: cublasXtHandle_t,
        uplo: cublasFillMode_t,
        trans: cublasOperation_t,
        n: size_t,
        k: size_t,
        alpha: *const cuDoubleComplex,
        A: *const cuDoubleComplex,
        lda: size_t,
        B: *const cuDoubleComplex,
        ldb: size_t,
        beta: *const cuDoubleComplex,
        C: *mut cuDoubleComplex,
        ldc: size_t,
    ) -> cublasStatus_t;
}
unsafe extern "C" {
    /// This function supports the 64-bit Integer Interface.
    ///
    /// This function performs the Hermitian rank- $2k$ update:
    /// $$
    /// C = \alpha\text{op}(A)\text{op}(B)^{H} + \overset{ˉ}{\alpha}\text{op}(B)\text{op}(A)^{H} + \beta C
    /// $$
    ///
    /// where $\alpha$ and $\beta$ are scalars, $C$ is a Hermitian matrix stored in lower or upper mode, and $A$ and $B$ are matrices with dimensions $\text{op}(A)$ $n \times k$ and $\text{op}(B)$ $n \times k$, respectively. Also, for matrix $A$ and $B$:
    /// $$
    /// \text{op(}A\text{) and op(}B\text{)} = \left\\{ \begin{matrix}
    /// {A\text{ and }B} & {\text{if }\textsf{trans == $\mathrm{CUBLAS_OP_N}$}} \\\\
    /// {A^{H}\text{ and }B^{H}} & {\text{if }\textsf{trans == $\mathrm{CUBLAS_OP_C}$}} \\\\
    /// \end{matrix} \right.
    /// $$
    ///
    /// For references please refer to NETLIB documentation:
    ///
    /// [cher2k()](http://www.netlib.org/blas/cher2k.f), [zher2k()](http://www.netlib.org/blas/zher2k.f).
    pub fn cublasXtCher2k(
        handle: cublasXtHandle_t,
        uplo: cublasFillMode_t,
        trans: cublasOperation_t,
        n: size_t,
        k: size_t,
        alpha: *const cuComplex,
        A: *const cuComplex,
        lda: size_t,
        B: *const cuComplex,
        ldb: size_t,
        beta: *const f32,
        C: *mut cuComplex,
        ldc: size_t,
    ) -> cublasStatus_t;
}
unsafe extern "C" {
    /// This function supports the 64-bit Integer Interface.
    ///
    /// This function performs the Hermitian rank- $2k$ update:
    /// $$
    /// C = \alpha\text{op}(A)\text{op}(B)^{H} + \overset{ˉ}{\alpha}\text{op}(B)\text{op}(A)^{H} + \beta C
    /// $$
    ///
    /// where $\alpha$ and $\beta$ are scalars, $C$ is a Hermitian matrix stored in lower or upper mode, and $A$ and $B$ are matrices with dimensions $\text{op}(A)$ $n \times k$ and $\text{op}(B)$ $n \times k$, respectively. Also, for matrix $A$ and $B$:
    /// $$
    /// \text{op(}A\text{) and op(}B\text{)} = \left\\{ \begin{matrix}
    /// {A\text{ and }B} & {\text{if }\textsf{trans == $\mathrm{CUBLAS_OP_N}$}} \\\\
    /// {A^{H}\text{ and }B^{H}} & {\text{if }\textsf{trans == $\mathrm{CUBLAS_OP_C}$}} \\\\
    /// \end{matrix} \right.
    /// $$
    ///
    /// For references please refer to NETLIB documentation:
    ///
    /// [cher2k()](http://www.netlib.org/blas/cher2k.f), [zher2k()](http://www.netlib.org/blas/zher2k.f).
    pub fn cublasXtZher2k(
        handle: cublasXtHandle_t,
        uplo: cublasFillMode_t,
        trans: cublasOperation_t,
        n: size_t,
        k: size_t,
        alpha: *const cuDoubleComplex,
        A: *const cuDoubleComplex,
        lda: size_t,
        B: *const cuDoubleComplex,
        ldb: size_t,
        beta: *const f64,
        C: *mut cuDoubleComplex,
        ldc: size_t,
    ) -> cublasStatus_t;
}
unsafe extern "C" {
    /// This function performs the symmetric packed matrix-matrix multiplication:
    /// $$
    /// C = \left\\{ \begin{matrix}
    /// {\alpha AB + \beta C} & {\text{if }\textsf{side == $\mathrm{CUBLAS_SIDE_LEFT}$}} \\\\
    /// {\alpha BA + \beta C} & {\text{if }\textsf{side == $\mathrm{CUBLAS_SIDE_RIGHT}$}} \\\\
    /// \end{matrix} \right.
    /// $$
    ///
    /// where $A$ is a $n \times n$ symmetric matrix stored in packed format, $B$ and $C$ are $m \times n$ matrices, and $\alpha$ and $\beta$ are scalars.
    ///
    /// If `uplo == CUBLAS_FILL_MODE_LOWER` then the elements in the lower triangular part of the symmetric matrix $A$ are packed together column by column without gaps, so that the element $A(i,j)$ is stored in the memory location `AP\[i+((2*n-j+1)*j)/2\]` for $j = 1,\ldots,n$ and $i \geq j$. Consequently, the packed format requires only $\frac{n(n + 1)}{2}$ elements for storage.
    ///
    /// If `uplo == CUBLAS_FILL_MODE_UPPER` then the elements in the upper triangular part of the symmetric matrix $A$ are packed together column by column without gaps, so that the element $A(i,j)$ is stored in the memory location `AP\[i+(j*(j+1))/2\]` for $j = 1,\ldots,n$ and $i \leq j$. Consequently, the packed format requires only $\frac{n(n + 1)}{2}$ elements for storage.
    ///
    /// For references please refer to NETLIB documentation:
    ///
    /// [ssymm()](http://www.netlib.org/blas/ssymm.f), [dsymm()](http://www.netlib.org/blas/dsymm.f), [csymm()](http://www.netlib.org/blas/csymm.f), [zsymm()](http://www.netlib.org/blas/zsymm.f).
    pub fn cublasXtSspmm(
        handle: cublasXtHandle_t,
        side: cublasSideMode_t,
        uplo: cublasFillMode_t,
        m: size_t,
        n: size_t,
        alpha: *const f32,
        AP: *const f32,
        B: *const f32,
        ldb: size_t,
        beta: *const f32,
        C: *mut f32,
        ldc: size_t,
    ) -> cublasStatus_t;
}
unsafe extern "C" {
    /// This function performs the symmetric packed matrix-matrix multiplication:
    /// $$
    /// C = \left\\{ \begin{matrix}
    /// {\alpha AB + \beta C} & {\text{if }\textsf{side == $\mathrm{CUBLAS_SIDE_LEFT}$}} \\\\
    /// {\alpha BA + \beta C} & {\text{if }\textsf{side == $\mathrm{CUBLAS_SIDE_RIGHT}$}} \\\\
    /// \end{matrix} \right.
    /// $$
    ///
    /// where $A$ is a $n \times n$ symmetric matrix stored in packed format, $B$ and $C$ are $m \times n$ matrices, and $\alpha$ and $\beta$ are scalars.
    ///
    /// If `uplo == CUBLAS_FILL_MODE_LOWER` then the elements in the lower triangular part of the symmetric matrix $A$ are packed together column by column without gaps, so that the element $A(i,j)$ is stored in the memory location `AP\[i+((2*n-j+1)*j)/2\]` for $j = 1,\ldots,n$ and $i \geq j$. Consequently, the packed format requires only $\frac{n(n + 1)}{2}$ elements for storage.
    ///
    /// If `uplo == CUBLAS_FILL_MODE_UPPER` then the elements in the upper triangular part of the symmetric matrix $A$ are packed together column by column without gaps, so that the element $A(i,j)$ is stored in the memory location `AP\[i+(j*(j+1))/2\]` for $j = 1,\ldots,n$ and $i \leq j$. Consequently, the packed format requires only $\frac{n(n + 1)}{2}$ elements for storage.
    ///
    /// For references please refer to NETLIB documentation:
    ///
    /// [ssymm()](http://www.netlib.org/blas/ssymm.f), [dsymm()](http://www.netlib.org/blas/dsymm.f), [csymm()](http://www.netlib.org/blas/csymm.f), [zsymm()](http://www.netlib.org/blas/zsymm.f).
    pub fn cublasXtDspmm(
        handle: cublasXtHandle_t,
        side: cublasSideMode_t,
        uplo: cublasFillMode_t,
        m: size_t,
        n: size_t,
        alpha: *const f64,
        AP: *const f64,
        B: *const f64,
        ldb: size_t,
        beta: *const f64,
        C: *mut f64,
        ldc: size_t,
    ) -> cublasStatus_t;
}
unsafe extern "C" {
    /// This function performs the symmetric packed matrix-matrix multiplication:
    /// $$
    /// C = \left\\{ \begin{matrix}
    /// {\alpha AB + \beta C} & {\text{if }\textsf{side == $\mathrm{CUBLAS_SIDE_LEFT}$}} \\\\
    /// {\alpha BA + \beta C} & {\text{if }\textsf{side == $\mathrm{CUBLAS_SIDE_RIGHT}$}} \\\\
    /// \end{matrix} \right.
    /// $$
    ///
    /// where $A$ is a $n \times n$ symmetric matrix stored in packed format, $B$ and $C$ are $m \times n$ matrices, and $\alpha$ and $\beta$ are scalars.
    ///
    /// If `uplo == CUBLAS_FILL_MODE_LOWER` then the elements in the lower triangular part of the symmetric matrix $A$ are packed together column by column without gaps, so that the element $A(i,j)$ is stored in the memory location `AP\[i+((2*n-j+1)*j)/2\]` for $j = 1,\ldots,n$ and $i \geq j$. Consequently, the packed format requires only $\frac{n(n + 1)}{2}$ elements for storage.
    ///
    /// If `uplo == CUBLAS_FILL_MODE_UPPER` then the elements in the upper triangular part of the symmetric matrix $A$ are packed together column by column without gaps, so that the element $A(i,j)$ is stored in the memory location `AP\[i+(j*(j+1))/2\]` for $j = 1,\ldots,n$ and $i \leq j$. Consequently, the packed format requires only $\frac{n(n + 1)}{2}$ elements for storage.
    ///
    /// For references please refer to NETLIB documentation:
    ///
    /// [ssymm()](http://www.netlib.org/blas/ssymm.f), [dsymm()](http://www.netlib.org/blas/dsymm.f), [csymm()](http://www.netlib.org/blas/csymm.f), [zsymm()](http://www.netlib.org/blas/zsymm.f).
    pub fn cublasXtCspmm(
        handle: cublasXtHandle_t,
        side: cublasSideMode_t,
        uplo: cublasFillMode_t,
        m: size_t,
        n: size_t,
        alpha: *const cuComplex,
        AP: *const cuComplex,
        B: *const cuComplex,
        ldb: size_t,
        beta: *const cuComplex,
        C: *mut cuComplex,
        ldc: size_t,
    ) -> cublasStatus_t;
}
unsafe extern "C" {
    /// This function performs the symmetric packed matrix-matrix multiplication:
    /// $$
    /// C = \left\\{ \begin{matrix}
    /// {\alpha AB + \beta C} & {\text{if }\textsf{side == $\mathrm{CUBLAS_SIDE_LEFT}$}} \\\\
    /// {\alpha BA + \beta C} & {\text{if }\textsf{side == $\mathrm{CUBLAS_SIDE_RIGHT}$}} \\\\
    /// \end{matrix} \right.
    /// $$
    ///
    /// where $A$ is a $n \times n$ symmetric matrix stored in packed format, $B$ and $C$ are $m \times n$ matrices, and $\alpha$ and $\beta$ are scalars.
    ///
    /// If `uplo == CUBLAS_FILL_MODE_LOWER` then the elements in the lower triangular part of the symmetric matrix $A$ are packed together column by column without gaps, so that the element $A(i,j)$ is stored in the memory location `AP\[i+((2*n-j+1)*j)/2\]` for $j = 1,\ldots,n$ and $i \geq j$. Consequently, the packed format requires only $\frac{n(n + 1)}{2}$ elements for storage.
    ///
    /// If `uplo == CUBLAS_FILL_MODE_UPPER` then the elements in the upper triangular part of the symmetric matrix $A$ are packed together column by column without gaps, so that the element $A(i,j)$ is stored in the memory location `AP\[i+(j*(j+1))/2\]` for $j = 1,\ldots,n$ and $i \leq j$. Consequently, the packed format requires only $\frac{n(n + 1)}{2}$ elements for storage.
    ///
    /// For references please refer to NETLIB documentation:
    ///
    /// [ssymm()](http://www.netlib.org/blas/ssymm.f), [dsymm()](http://www.netlib.org/blas/dsymm.f), [csymm()](http://www.netlib.org/blas/csymm.f), [zsymm()](http://www.netlib.org/blas/zsymm.f).
    pub fn cublasXtZspmm(
        handle: cublasXtHandle_t,
        side: cublasSideMode_t,
        uplo: cublasFillMode_t,
        m: size_t,
        n: size_t,
        alpha: *const cuDoubleComplex,
        AP: *const cuDoubleComplex,
        B: *const cuDoubleComplex,
        ldb: size_t,
        beta: *const cuDoubleComplex,
        C: *mut cuDoubleComplex,
        ldc: size_t,
    ) -> cublasStatus_t;
}
unsafe extern "C" {
    /// This function supports the 64-bit Integer Interface.
    ///
    /// This function performs the triangular matrix-matrix multiplication:
    /// $$
    /// C = \left\\{ \begin{matrix}
    /// {\alpha\text{op}(A)B} & {\text{if }\textsf{side == $\mathrm{CUBLAS_SIDE_LEFT}$}} \\\\
    /// {\alpha B\text{op}(A)} & {\text{if }\textsf{side == $\mathrm{CUBLAS_SIDE_RIGHT}$}} \\\\
    /// \end{matrix} \right.
    /// $$
    ///
    /// where $A$ is a triangular matrix stored in lower or upper mode with or without the main diagonal, $B$ and $C$ are $m \times n$ matrix, and $\alpha$ is a scalar. Also, for matrix $A$:
    /// $$
    /// \text{op}(A) = \left\\{ \begin{matrix}
    /// A & {\text{if }\textsf{transa == $\mathrm{CUBLAS_OP_N}$}} \\\\
    /// A^{T} & {\text{if }\textsf{transa == $\mathrm{CUBLAS_OP_T}$}} \\\\
    /// A^{H} & {\text{if }\textsf{transa == $\mathrm{CUBLAS_OP_C}$}} \\\\
    /// \end{matrix} \right.
    /// $$
    ///
    /// Notice that in order to achieve better parallelism cuBLAS differs from the BLAS API only for this routine. The BLAS API assumes an in-place implementation (with results written back to B), while the cuBLAS API assumes an out-of-place implementation (with results written into C). The application can obtain the in-place functionality of BLAS in the cuBLAS API by passing the address of the matrix B in place of the matrix C. No other overlapping in the input parameters is supported.
    ///
    /// For references please refer to NETLIB documentation:
    ///
    /// [strmm()](http://www.netlib.org/blas/strmm.f), [dtrmm()](http://www.netlib.org/blas/dtrmm.f), [ctrmm()](http://www.netlib.org/blas/ctrmm.f), [ztrmm()](http://www.netlib.org/blas/ztrmm.f).
    pub fn cublasXtStrmm(
        handle: cublasXtHandle_t,
        side: cublasSideMode_t,
        uplo: cublasFillMode_t,
        trans: cublasOperation_t,
        diag: cublasDiagType_t,
        m: size_t,
        n: size_t,
        alpha: *const f32,
        A: *const f32,
        lda: size_t,
        B: *const f32,
        ldb: size_t,
        C: *mut f32,
        ldc: size_t,
    ) -> cublasStatus_t;
}
unsafe extern "C" {
    /// This function supports the 64-bit Integer Interface.
    ///
    /// This function performs the triangular matrix-matrix multiplication:
    /// $$
    /// C = \left\\{ \begin{matrix}
    /// {\alpha\text{op}(A)B} & {\text{if }\textsf{side == $\mathrm{CUBLAS_SIDE_LEFT}$}} \\\\
    /// {\alpha B\text{op}(A)} & {\text{if }\textsf{side == $\mathrm{CUBLAS_SIDE_RIGHT}$}} \\\\
    /// \end{matrix} \right.
    /// $$
    ///
    /// where $A$ is a triangular matrix stored in lower or upper mode with or without the main diagonal, $B$ and $C$ are $m \times n$ matrix, and $\alpha$ is a scalar. Also, for matrix $A$:
    /// $$
    /// \text{op}(A) = \left\\{ \begin{matrix}
    /// A & {\text{if }\textsf{transa == $\mathrm{CUBLAS_OP_N}$}} \\\\
    /// A^{T} & {\text{if }\textsf{transa == $\mathrm{CUBLAS_OP_T}$}} \\\\
    /// A^{H} & {\text{if }\textsf{transa == $\mathrm{CUBLAS_OP_C}$}} \\\\
    /// \end{matrix} \right.
    /// $$
    ///
    /// Notice that in order to achieve better parallelism cuBLAS differs from the BLAS API only for this routine. The BLAS API assumes an in-place implementation (with results written back to B), while the cuBLAS API assumes an out-of-place implementation (with results written into C). The application can obtain the in-place functionality of BLAS in the cuBLAS API by passing the address of the matrix B in place of the matrix C. No other overlapping in the input parameters is supported.
    ///
    /// For references please refer to NETLIB documentation:
    ///
    /// [strmm()](http://www.netlib.org/blas/strmm.f), [dtrmm()](http://www.netlib.org/blas/dtrmm.f), [ctrmm()](http://www.netlib.org/blas/ctrmm.f), [ztrmm()](http://www.netlib.org/blas/ztrmm.f).
    pub fn cublasXtDtrmm(
        handle: cublasXtHandle_t,
        side: cublasSideMode_t,
        uplo: cublasFillMode_t,
        trans: cublasOperation_t,
        diag: cublasDiagType_t,
        m: size_t,
        n: size_t,
        alpha: *const f64,
        A: *const f64,
        lda: size_t,
        B: *const f64,
        ldb: size_t,
        C: *mut f64,
        ldc: size_t,
    ) -> cublasStatus_t;
}
unsafe extern "C" {
    /// This function supports the 64-bit Integer Interface.
    ///
    /// This function performs the triangular matrix-matrix multiplication:
    /// $$
    /// C = \left\\{ \begin{matrix}
    /// {\alpha\text{op}(A)B} & {\text{if }\textsf{side == $\mathrm{CUBLAS_SIDE_LEFT}$}} \\\\
    /// {\alpha B\text{op}(A)} & {\text{if }\textsf{side == $\mathrm{CUBLAS_SIDE_RIGHT}$}} \\\\
    /// \end{matrix} \right.
    /// $$
    ///
    /// where $A$ is a triangular matrix stored in lower or upper mode with or without the main diagonal, $B$ and $C$ are $m \times n$ matrix, and $\alpha$ is a scalar. Also, for matrix $A$:
    /// $$
    /// \text{op}(A) = \left\\{ \begin{matrix}
    /// A & {\text{if }\textsf{transa == $\mathrm{CUBLAS_OP_N}$}} \\\\
    /// A^{T} & {\text{if }\textsf{transa == $\mathrm{CUBLAS_OP_T}$}} \\\\
    /// A^{H} & {\text{if }\textsf{transa == $\mathrm{CUBLAS_OP_C}$}} \\\\
    /// \end{matrix} \right.
    /// $$
    ///
    /// Notice that in order to achieve better parallelism cuBLAS differs from the BLAS API only for this routine. The BLAS API assumes an in-place implementation (with results written back to B), while the cuBLAS API assumes an out-of-place implementation (with results written into C). The application can obtain the in-place functionality of BLAS in the cuBLAS API by passing the address of the matrix B in place of the matrix C. No other overlapping in the input parameters is supported.
    ///
    /// For references please refer to NETLIB documentation:
    ///
    /// [strmm()](http://www.netlib.org/blas/strmm.f), [dtrmm()](http://www.netlib.org/blas/dtrmm.f), [ctrmm()](http://www.netlib.org/blas/ctrmm.f), [ztrmm()](http://www.netlib.org/blas/ztrmm.f).
    pub fn cublasXtCtrmm(
        handle: cublasXtHandle_t,
        side: cublasSideMode_t,
        uplo: cublasFillMode_t,
        trans: cublasOperation_t,
        diag: cublasDiagType_t,
        m: size_t,
        n: size_t,
        alpha: *const cuComplex,
        A: *const cuComplex,
        lda: size_t,
        B: *const cuComplex,
        ldb: size_t,
        C: *mut cuComplex,
        ldc: size_t,
    ) -> cublasStatus_t;
}
unsafe extern "C" {
    /// This function supports the 64-bit Integer Interface.
    ///
    /// This function performs the triangular matrix-matrix multiplication:
    /// $$
    /// C = \left\\{ \begin{matrix}
    /// {\alpha\text{op}(A)B} & {\text{if }\textsf{side == $\mathrm{CUBLAS_SIDE_LEFT}$}} \\\\
    /// {\alpha B\text{op}(A)} & {\text{if }\textsf{side == $\mathrm{CUBLAS_SIDE_RIGHT}$}} \\\\
    /// \end{matrix} \right.
    /// $$
    ///
    /// where $A$ is a triangular matrix stored in lower or upper mode with or without the main diagonal, $B$ and $C$ are $m \times n$ matrix, and $\alpha$ is a scalar. Also, for matrix $A$:
    /// $$
    /// \text{op}(A) = \left\\{ \begin{matrix}
    /// A & {\text{if }\textsf{transa == $\mathrm{CUBLAS_OP_N}$}} \\\\
    /// A^{T} & {\text{if }\textsf{transa == $\mathrm{CUBLAS_OP_T}$}} \\\\
    /// A^{H} & {\text{if }\textsf{transa == $\mathrm{CUBLAS_OP_C}$}} \\\\
    /// \end{matrix} \right.
    /// $$
    ///
    /// Notice that in order to achieve better parallelism cuBLAS differs from the BLAS API only for this routine. The BLAS API assumes an in-place implementation (with results written back to B), while the cuBLAS API assumes an out-of-place implementation (with results written into C). The application can obtain the in-place functionality of BLAS in the cuBLAS API by passing the address of the matrix B in place of the matrix C. No other overlapping in the input parameters is supported.
    ///
    /// For references please refer to NETLIB documentation:
    ///
    /// [strmm()](http://www.netlib.org/blas/strmm.f), [dtrmm()](http://www.netlib.org/blas/dtrmm.f), [ctrmm()](http://www.netlib.org/blas/ctrmm.f), [ztrmm()](http://www.netlib.org/blas/ztrmm.f).
    pub fn cublasXtZtrmm(
        handle: cublasXtHandle_t,
        side: cublasSideMode_t,
        uplo: cublasFillMode_t,
        trans: cublasOperation_t,
        diag: cublasDiagType_t,
        m: size_t,
        n: size_t,
        alpha: *const cuDoubleComplex,
        A: *const cuDoubleComplex,
        lda: size_t,
        B: *const cuDoubleComplex,
        ldb: size_t,
        C: *mut cuDoubleComplex,
        ldc: size_t,
    ) -> cublasStatus_t;
}
