[package]
name = "singe-nccl-sys"
description = "Low-level FFI bindings for the NVIDIA Collective Communications Library (NCCL)."
version = "0.1.0-alpha.6"
edition.workspace = true
repository.workspace = true
license-file = "../LICENSE"
readme = "README.md"
keywords = ["cuda", "nvidia", "nccl", "bindings", "ffi"]
include.workspace = true

[package.metadata.docs.rs]
rustdoc-args = ["--html-in-header", "dist/katex_header.html"]

[features]
default = ["nccl_2_28"]

nccl_2_28 = ["singe-cuda-sys/runtime_13_3"]

[dependencies]
singe-cuda-sys.workspace = true
num_enum.workspace = true

[build-dependencies]
singe-cuda-find.workspace = true
anyhow.workspace = true
