/* automatically generated by rust-bindgen 0.72.1 */

pub const CURAND_VER_MAJOR: u32 = 10;
pub const CURAND_VER_MINOR: u32 = 4;
pub const CURAND_VER_PATCH: u32 = 2;
pub const CURAND_VER_BUILD: u32 = 55;
pub const CURAND_VERSION: u32 = 10402;
pub type size_t = ::core::ffi::c_ulong;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CUstream_st {
    _unused: [u8; 0],
}
/// CURAND function call status types.
#[repr(u32)]
#[derive(
    Debug,
    Copy,
    Clone,
    Hash,
    PartialOrd,
    Ord,
    PartialEq,
    Eq,
    TryFromPrimitive,
    IntoPrimitive,
)]
pub enum curandStatus {
    /// No errors.
    CURAND_STATUS_SUCCESS = 0,
    /// Header file and linked library version do not match.
    CURAND_STATUS_VERSION_MISMATCH = 100,
    /// Generator not initialized.
    CURAND_STATUS_NOT_INITIALIZED = 101,
    /// Memory allocation failed.
    CURAND_STATUS_ALLOCATION_FAILED = 102,
    /// Generator is wrong type.
    CURAND_STATUS_TYPE_ERROR = 103,
    /// Argument out of range.
    CURAND_STATUS_OUT_OF_RANGE = 104,
    /// Length requested is not a multple of dimension.
    CURAND_STATUS_LENGTH_NOT_MULTIPLE = 105,
    /// GPU does not have double precision required by MRG32k3a.
    CURAND_STATUS_DOUBLE_PRECISION_REQUIRED = 106,
    /// Kernel launch failure.
    CURAND_STATUS_LAUNCH_FAILURE = 201,
    /// Preexisting failure on library entry.
    CURAND_STATUS_PREEXISTING_FAILURE = 202,
    /// Initialization of CUDA failed.
    CURAND_STATUS_INITIALIZATION_FAILED = 203,
    /// Architecture mismatch, GPU does not support requested feature.
    CURAND_STATUS_ARCH_MISMATCH = 204,
    /// Internal library error.
    CURAND_STATUS_INTERNAL_ERROR = 999,
}
pub use self::curandStatus as curandStatus_t;
/// CURAND generator types.
#[repr(u32)]
#[derive(
    Debug,
    Copy,
    Clone,
    Hash,
    PartialOrd,
    Ord,
    PartialEq,
    Eq,
    TryFromPrimitive,
    IntoPrimitive,
)]
pub enum curandRngType {
    CURAND_RNG_TEST = 0,
    /// Default pseudorandom generator.
    CURAND_RNG_PSEUDO_DEFAULT = 100,
    /// XORWOW pseudorandom generator.
    CURAND_RNG_PSEUDO_XORWOW = 101,
    /// MRG32k3a pseudorandom generator.
    CURAND_RNG_PSEUDO_MRG32K3A = 121,
    /// Mersenne Twister MTGP32 pseudorandom generator.
    CURAND_RNG_PSEUDO_MTGP32 = 141,
    /// Mersenne Twister MT19937 pseudorandom generator.
    CURAND_RNG_PSEUDO_MT19937 = 142,
    /// PHILOX-4x32-10 pseudorandom generator.
    CURAND_RNG_PSEUDO_PHILOX4_32_10 = 161,
    /// Default quasirandom generator.
    CURAND_RNG_QUASI_DEFAULT = 200,
    /// Sobol32 quasirandom generator.
    CURAND_RNG_QUASI_SOBOL32 = 201,
    /// Scrambled Sobol32 quasirandom generator.
    CURAND_RNG_QUASI_SCRAMBLED_SOBOL32 = 202,
    /// Sobol64 quasirandom generator.
    CURAND_RNG_QUASI_SOBOL64 = 203,
    /// Scrambled Sobol64 quasirandom generator.
    CURAND_RNG_QUASI_SCRAMBLED_SOBOL64 = 204,
}
pub use self::curandRngType as curandRngType_t;
/// CURAND ordering of results in memory.
#[repr(u32)]
#[derive(
    Debug,
    Copy,
    Clone,
    Hash,
    PartialOrd,
    Ord,
    PartialEq,
    Eq,
    TryFromPrimitive,
    IntoPrimitive,
)]
pub enum curandOrdering {
    /// Best ordering for pseudorandom results.
    CURAND_ORDERING_PSEUDO_BEST = 100,
    /// Specific default thread sequence for pseudorandom results, same as [`curandOrdering::CURAND_ORDERING_PSEUDO_BEST`].
    CURAND_ORDERING_PSEUDO_DEFAULT = 101,
    /// Specific seeding pattern for fast lower quality pseudorandom results.
    CURAND_ORDERING_PSEUDO_SEEDED = 102,
    /// Specific legacy sequence for pseudorandom results, guaranteed to remain the same for all cuRAND release.
    CURAND_ORDERING_PSEUDO_LEGACY = 103,
    /// Specific ordering adjusted to the device it is being executed on, provides the best performance.
    CURAND_ORDERING_PSEUDO_DYNAMIC = 104,
    /// Specific n-dimensional ordering for quasirandom results.
    CURAND_ORDERING_QUASI_DEFAULT = 201,
}
pub use self::curandOrdering as curandOrdering_t;
/// CURAND choice of direction vector set.
#[repr(u32)]
#[derive(
    Debug,
    Copy,
    Clone,
    Hash,
    PartialOrd,
    Ord,
    PartialEq,
    Eq,
    TryFromPrimitive,
    IntoPrimitive,
)]
pub enum curandDirectionVectorSet {
    /// Specific set of 32-bit direction vectors generated from polynomials recommended by S. Joe and F. Y. Kuo, for up to 20,000 dimensions.
    CURAND_DIRECTION_VECTORS_32_JOEKUO6 = 101,
    /// Specific set of 32-bit direction vectors generated from polynomials recommended by S. Joe and F. Y. Kuo, for up to 20,000 dimensions, and scrambled.
    CURAND_SCRAMBLED_DIRECTION_VECTORS_32_JOEKUO6 = 102,
    /// Specific set of 64-bit direction vectors generated from polynomials recommended by S. Joe and F. Y. Kuo, for up to 20,000 dimensions.
    CURAND_DIRECTION_VECTORS_64_JOEKUO6 = 103,
    /// Specific set of 64-bit direction vectors generated from polynomials recommended by S. Joe and F. Y. Kuo, for up to 20,000 dimensions, and scrambled.
    CURAND_SCRAMBLED_DIRECTION_VECTORS_64_JOEKUO6 = 104,
}
pub use self::curandDirectionVectorSet as curandDirectionVectorSet_t;
pub type curandDirectionVectors32_t = [::core::ffi::c_uint; 32usize];
pub type curandDirectionVectors64_t = [::core::ffi::c_ulonglong; 64usize];
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct curandGenerator_st {
    _unused: [u8; 0],
}
pub type curandGenerator_t = *mut curandGenerator_st;
pub type curandDistribution_st = f64;
pub type curandDistribution_t = *mut curandDistribution_st;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct curandDistributionShift_st {
    _unused: [u8; 0],
}
pub type curandDistributionShift_t = *mut curandDistributionShift_st;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct curandDistributionM2Shift_st {
    _unused: [u8; 0],
}
pub type curandDistributionM2Shift_t = *mut curandDistributionM2Shift_st;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct curandHistogramM2_st {
    _unused: [u8; 0],
}
pub type curandHistogramM2_t = *mut curandHistogramM2_st;
pub type curandHistogramM2K_st = ::core::ffi::c_uint;
pub type curandHistogramM2K_t = *mut curandHistogramM2K_st;
pub type curandHistogramM2V_st = curandDistribution_st;
pub type curandHistogramM2V_t = *mut curandHistogramM2V_st;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct curandDiscreteDistribution_st {
    _unused: [u8; 0],
}
pub type curandDiscreteDistribution_t = *mut curandDiscreteDistribution_st;
#[repr(u32)]
#[derive(
    Debug,
    Copy,
    Clone,
    Hash,
    PartialOrd,
    Ord,
    PartialEq,
    Eq,
    TryFromPrimitive,
    IntoPrimitive,
)]
pub enum curandMethod {
    CURAND_CHOOSE_BEST = 0,
    CURAND_ITR = 1,
    CURAND_KNUTH = 2,
    CURAND_HITR = 3,
    CURAND_M1 = 4,
    CURAND_M2 = 5,
    CURAND_BINARY_SEARCH = 6,
    CURAND_DISCRETE_GAUSS = 7,
    CURAND_REJECTION = 8,
    CURAND_DEVICE_API = 9,
    CURAND_FAST_REJECTION = 10,
    CURAND_3RD = 11,
    CURAND_DEFINITION = 12,
    CURAND_POISSON = 13,
}
pub use self::curandMethod as curandMethod_t;
unsafe extern "C" {
    /// Create new random number generator.
    ///
    /// # Parameters
    ///
    /// - `generator`: Pointer to generator.
    /// - `rng_type`: Type of generator to create.
    ///
    /// # Return value
    ///
    /// - [`curandStatus::CURAND_STATUS_ALLOCATION_FAILED`]: if memory could not be allocated.
    /// - [`curandStatus::CURAND_STATUS_INITIALIZATION_FAILED`]: if there was a problem setting up the GPU.
    /// - [`curandStatus::CURAND_STATUS_SUCCESS`]: if generator was created successfully.
    /// - [`curandStatus::CURAND_STATUS_TYPE_ERROR`]: if the value for rng_type is invalid.
    /// - [`curandStatus::CURAND_STATUS_VERSION_MISMATCH`]: if the header file version does not match the dynamically linked library version.
    pub fn curandCreateGenerator(
        generator: *mut curandGenerator_t,
        rng_type: curandRngType_t,
    ) -> curandStatus_t;
}
unsafe extern "C" {
    /// Create new host CPU random number generator.
    ///
    /// # Parameters
    ///
    /// - `generator`: Pointer to generator.
    /// - `rng_type`: Type of generator to create.
    ///
    /// # Return value
    ///
    /// - [`curandStatus::CURAND_STATUS_ALLOCATION_FAILED`]: if memory could not be allocated.
    /// - [`curandStatus::CURAND_STATUS_INITIALIZATION_FAILED`]: if there was a problem setting up the GPU.
    /// - [`curandStatus::CURAND_STATUS_SUCCESS`]: if generator was created successfully.
    /// - [`curandStatus::CURAND_STATUS_TYPE_ERROR`]: if the value for rng_type is invalid.
    /// - [`curandStatus::CURAND_STATUS_VERSION_MISMATCH`]: if the header file version does not match the dynamically linked library version.
    pub fn curandCreateGeneratorHost(
        generator: *mut curandGenerator_t,
        rng_type: curandRngType_t,
    ) -> curandStatus_t;
}
unsafe extern "C" {
    /// Destroy an existing generator.
    ///
    /// # Parameters
    ///
    /// - `generator`: Generator to destroy.
    ///
    /// # Return value
    ///
    /// - [`curandStatus::CURAND_STATUS_NOT_INITIALIZED`]: if the generator was never created.
    /// - [`curandStatus::CURAND_STATUS_SUCCESS`]: if generator was destroyed successfully.
    pub fn curandDestroyGenerator(generator: curandGenerator_t) -> curandStatus_t;
}
unsafe extern "C" {
    /// Return the version number of the library.
    ///
    /// # Parameters
    ///
    /// - `version`: CURAND library version.
    ///
    /// # Return value
    ///
    /// - [`curandStatus::CURAND_STATUS_SUCCESS`]: if the version number was successfully returned.
    pub fn curandGetVersion(version: *mut ::core::ffi::c_int) -> curandStatus_t;
}
unsafe extern "C" {
    /// Return the value of the curand property.
    ///
    /// # Parameters
    ///
    /// - `value`: integer value for the requested property.
    ///
    /// # Return value
    ///
    /// - [`curandStatus::CURAND_STATUS_OUT_OF_RANGE`]: if the property type is not recognized.
    /// - [`curandStatus::CURAND_STATUS_SUCCESS`]: if the property value was successfully returned.
    pub fn curandGetProperty(
        type_: libraryPropertyType,
        value: *mut ::core::ffi::c_int,
    ) -> curandStatus_t;
}
unsafe extern "C" {
    /// Set the current stream for CURAND kernel launches.
    ///
    /// # Parameters
    ///
    /// - `generator`: Generator to modify.
    /// - `stream`: Stream to use or NULL for null stream.
    ///
    /// # Return value
    ///
    /// - [`curandStatus::CURAND_STATUS_NOT_INITIALIZED`]: if the generator was never created.
    /// - [`curandStatus::CURAND_STATUS_SUCCESS`]: if stream was set successfully.
    pub fn curandSetStream(
        generator: curandGenerator_t,
        stream: cudaStream_t,
    ) -> curandStatus_t;
}
unsafe extern "C" {
    /// Set the seed value of the pseudo-random number generator.
    ///
    /// # Parameters
    ///
    /// - `generator`: Generator to modify.
    /// - `seed`: Seed value.
    ///
    /// # Return value
    ///
    /// - [`curandStatus::CURAND_STATUS_NOT_INITIALIZED`]: if the generator was never created.
    /// - [`curandStatus::CURAND_STATUS_SUCCESS`]: if generator seed was set successfully.
    /// - [`curandStatus::CURAND_STATUS_TYPE_ERROR`]: if the generator is not a pseudorandom number generator.
    pub fn curandSetPseudoRandomGeneratorSeed(
        generator: curandGenerator_t,
        seed: ::core::ffi::c_ulonglong,
    ) -> curandStatus_t;
}
unsafe extern "C" {
    /// Set the absolute offset of the pseudo or quasirandom number generator.
    ///
    /// # Parameters
    ///
    /// - `generator`: Generator to modify.
    /// - `offset`: Absolute offset position.
    ///
    /// # Return value
    ///
    /// - [`curandStatus::CURAND_STATUS_NOT_INITIALIZED`]: if the generator was never created.
    /// - [`curandStatus::CURAND_STATUS_SUCCESS`]: if generator offset was set successfully.
    pub fn curandSetGeneratorOffset(
        generator: curandGenerator_t,
        offset: ::core::ffi::c_ulonglong,
    ) -> curandStatus_t;
}
unsafe extern "C" {
    /// Set the ordering of results of the pseudo or quasirandom number generator.
    ///
    /// # Parameters
    ///
    /// - `generator`: Generator to modify.
    /// - `order`: Ordering of results.
    ///
    /// # Return value
    ///
    /// - [`curandStatus::CURAND_STATUS_NOT_INITIALIZED`]: if the generator was never created.
    /// - [`curandStatus::CURAND_STATUS_OUT_OF_RANGE`]: if the ordering is not valid.
    /// - [`curandStatus::CURAND_STATUS_SUCCESS`]: if generator ordering was set successfully.
    pub fn curandSetGeneratorOrdering(
        generator: curandGenerator_t,
        order: curandOrdering_t,
    ) -> curandStatus_t;
}
unsafe extern "C" {
    /// Set the number of dimensions.
    ///
    /// # Parameters
    ///
    /// - `generator`: Generator to modify.
    /// - `num_dimensions`: Number of dimensions.
    ///
    /// # Return value
    ///
    /// - [`curandStatus::CURAND_STATUS_NOT_INITIALIZED`]: if the generator was never created.
    /// - [`curandStatus::CURAND_STATUS_OUT_OF_RANGE`]: if num_dimensions is not valid.
    /// - [`curandStatus::CURAND_STATUS_SUCCESS`]: if generator ordering was set successfully.
    /// - [`curandStatus::CURAND_STATUS_TYPE_ERROR`]: if the generator is not a quasirandom number generator.
    pub fn curandSetQuasiRandomGeneratorDimensions(
        generator: curandGenerator_t,
        num_dimensions: ::core::ffi::c_uint,
    ) -> curandStatus_t;
}
unsafe extern "C" {
    /// Generate 32-bit pseudo or quasirandom numbers.
    ///
    /// # Parameters
    ///
    /// - `generator`: Generator to use.
    /// - `outputPtr`: Pointer to device memory to store CUDA-generated results, or Pointer to host memory to store CPU-generated results.
    /// - `num`: Number of random 32-bit values to generate.
    ///
    /// # Return value
    ///
    /// - [`curandStatus::CURAND_STATUS_ALLOCATION_FAILED`]: if memory could not be allocated.
    /// - [`curandStatus::CURAND_STATUS_LAUNCH_FAILURE`]: if the kernel launch failed for any reason.
    /// - [`curandStatus::CURAND_STATUS_LENGTH_NOT_MULTIPLE`]: if the number of output samples is not a multiple of the quasirandom dimension.
    /// - [`curandStatus::CURAND_STATUS_NOT_INITIALIZED`]: if the generator was never created.
    /// - [`curandStatus::CURAND_STATUS_PREEXISTING_FAILURE`]: if there was an existing error from a previous kernel launch.
    /// - [`curandStatus::CURAND_STATUS_SUCCESS`]: if the results were generated successfully.
    /// - [`curandStatus::CURAND_STATUS_TYPE_ERROR`]: if the generator is a 64 bit quasirandom generator. (use curandGenerateLongLong() with 64 bit quasirandom generators).
    pub fn curandGenerate(
        generator: curandGenerator_t,
        outputPtr: *mut ::core::ffi::c_uint,
        num: size_t,
    ) -> curandStatus_t;
}
unsafe extern "C" {
    /// Generate 64-bit quasirandom numbers.
    ///
    /// # Parameters
    ///
    /// - `generator`: Generator to use.
    /// - `outputPtr`: Pointer to device memory to store CUDA-generated results, or Pointer to host memory to store CPU-generated results.
    /// - `num`: Number of random 64-bit values to generate.
    ///
    /// # Return value
    ///
    /// - [`curandStatus::CURAND_STATUS_LAUNCH_FAILURE`]: if the kernel launch failed for any reason.
    /// - [`curandStatus::CURAND_STATUS_LENGTH_NOT_MULTIPLE`]: if the number of output samples is not a multiple of the quasirandom dimension.
    /// - [`curandStatus::CURAND_STATUS_NOT_INITIALIZED`]: if the generator was never created.
    /// - [`curandStatus::CURAND_STATUS_PREEXISTING_FAILURE`]: if there was an existing error from a previous kernel launch.
    /// - [`curandStatus::CURAND_STATUS_SUCCESS`]: if the results were generated successfully.
    /// - [`curandStatus::CURAND_STATUS_TYPE_ERROR`]: if the generator is not a 64 bit quasirandom generator.
    pub fn curandGenerateLongLong(
        generator: curandGenerator_t,
        outputPtr: *mut ::core::ffi::c_ulonglong,
        num: size_t,
    ) -> curandStatus_t;
}
unsafe extern "C" {
    /// Generate uniformly distributed floats.
    ///
    /// # Parameters
    ///
    /// - `generator`: Generator to use.
    /// - `outputPtr`: Pointer to device memory to store CUDA-generated results, or Pointer to host memory to store CPU-generated results.
    /// - `num`: Number of floats to generate.
    ///
    /// # Return value
    ///
    /// - [`curandStatus::CURAND_STATUS_ALLOCATION_FAILED`]: if memory could not be allocated.
    /// - [`curandStatus::CURAND_STATUS_LAUNCH_FAILURE`]: if the kernel launch failed for any reason.
    /// - [`curandStatus::CURAND_STATUS_LENGTH_NOT_MULTIPLE`]: if the number of output samples is not a multiple of the quasirandom dimension.
    /// - [`curandStatus::CURAND_STATUS_NOT_INITIALIZED`]: if the generator was never created.
    /// - [`curandStatus::CURAND_STATUS_PREEXISTING_FAILURE`]: if there was an existing error from a previous kernel launch.
    /// - [`curandStatus::CURAND_STATUS_SUCCESS`]: if the results were generated successfully.
    pub fn curandGenerateUniform(
        generator: curandGenerator_t,
        outputPtr: *mut f32,
        num: size_t,
    ) -> curandStatus_t;
}
unsafe extern "C" {
    /// Generate uniformly distributed doubles.
    ///
    /// # Parameters
    ///
    /// - `generator`: Generator to use.
    /// - `outputPtr`: Pointer to device memory to store CUDA-generated results, or Pointer to host memory to store CPU-generated results.
    /// - `num`: Number of doubles to generate.
    ///
    /// # Return value
    ///
    /// - [`curandStatus::CURAND_STATUS_ALLOCATION_FAILED`]: if memory could not be allocated.
    /// - [`curandStatus::CURAND_STATUS_DOUBLE_PRECISION_REQUIRED`]: if the GPU does not support double precision.
    /// - [`curandStatus::CURAND_STATUS_LAUNCH_FAILURE`]: if the kernel launch failed for any reason.
    /// - [`curandStatus::CURAND_STATUS_LENGTH_NOT_MULTIPLE`]: if the number of output samples is not a multiple of the quasirandom dimension.
    /// - [`curandStatus::CURAND_STATUS_NOT_INITIALIZED`]: if the generator was never created.
    /// - [`curandStatus::CURAND_STATUS_PREEXISTING_FAILURE`]: if there was an existing error from a previous kernel launch.
    /// - [`curandStatus::CURAND_STATUS_SUCCESS`]: if the results were generated successfully.
    pub fn curandGenerateUniformDouble(
        generator: curandGenerator_t,
        outputPtr: *mut f64,
        num: size_t,
    ) -> curandStatus_t;
}
unsafe extern "C" {
    /// Generate normally distributed doubles.
    ///
    /// # Parameters
    ///
    /// - `generator`: Generator to use.
    /// - `outputPtr`: Pointer to device memory to store CUDA-generated results, or Pointer to host memory to store CPU-generated results.
    /// - `n`: Number of floats to generate.
    /// - `mean`: Mean of normal distribution.
    /// - `stddev`: Standard deviation of normal distribution.
    ///
    /// # Return value
    ///
    /// - [`curandStatus::CURAND_STATUS_ALLOCATION_FAILED`]: if memory could not be allocated.
    /// - [`curandStatus::CURAND_STATUS_LAUNCH_FAILURE`]: if the kernel launch failed for any reason.
    /// - [`curandStatus::CURAND_STATUS_LENGTH_NOT_MULTIPLE`]: if the number of output samples is not a multiple of the quasirandom dimension, or is not a multiple of two for pseudorandom generators.
    /// - [`curandStatus::CURAND_STATUS_NOT_INITIALIZED`]: if the generator was never created.
    /// - [`curandStatus::CURAND_STATUS_PREEXISTING_FAILURE`]: if there was an existing error from a previous kernel launch.
    /// - [`curandStatus::CURAND_STATUS_SUCCESS`]: if the results were generated successfully.
    pub fn curandGenerateNormal(
        generator: curandGenerator_t,
        outputPtr: *mut f32,
        n: size_t,
        mean: f32,
        stddev: f32,
    ) -> curandStatus_t;
}
unsafe extern "C" {
    /// Generate normally distributed doubles.
    ///
    /// # Parameters
    ///
    /// - `generator`: Generator to use.
    /// - `outputPtr`: Pointer to device memory to store CUDA-generated results, or Pointer to host memory to store CPU-generated results.
    /// - `n`: Number of doubles to generate.
    /// - `mean`: Mean of normal distribution.
    /// - `stddev`: Standard deviation of normal distribution.
    ///
    /// # Return value
    ///
    /// - [`curandStatus::CURAND_STATUS_ALLOCATION_FAILED`]: if memory could not be allocated.
    /// - [`curandStatus::CURAND_STATUS_DOUBLE_PRECISION_REQUIRED`]: if the GPU does not support double precision.
    /// - [`curandStatus::CURAND_STATUS_LAUNCH_FAILURE`]: if the kernel launch failed for any reason.
    /// - [`curandStatus::CURAND_STATUS_LENGTH_NOT_MULTIPLE`]: if the number of output samples is not a multiple of the quasirandom dimension, or is not a multiple of two for pseudorandom generators.
    /// - [`curandStatus::CURAND_STATUS_NOT_INITIALIZED`]: if the generator was never created.
    /// - [`curandStatus::CURAND_STATUS_PREEXISTING_FAILURE`]: if there was an existing error from a previous kernel launch.
    /// - [`curandStatus::CURAND_STATUS_SUCCESS`]: if the results were generated successfully.
    pub fn curandGenerateNormalDouble(
        generator: curandGenerator_t,
        outputPtr: *mut f64,
        n: size_t,
        mean: f64,
        stddev: f64,
    ) -> curandStatus_t;
}
unsafe extern "C" {
    /// Generate log-normally distributed floats.
    ///
    /// # Parameters
    ///
    /// - `generator`: Generator to use.
    /// - `outputPtr`: Pointer to device memory to store CUDA-generated results, or Pointer to host memory to store CPU-generated results.
    /// - `n`: Number of floats to generate.
    /// - `mean`: Mean of associated normal distribution.
    /// - `stddev`: Standard deviation of associated normal distribution.
    ///
    /// # Return value
    ///
    /// - [`curandStatus::CURAND_STATUS_ALLOCATION_FAILED`]: if memory could not be allocated.
    /// - [`curandStatus::CURAND_STATUS_LAUNCH_FAILURE`]: if the kernel launch failed for any reason.
    /// - [`curandStatus::CURAND_STATUS_LENGTH_NOT_MULTIPLE`]: if the number of output samples is not a multiple of the quasirandom dimension, or is not a multiple of two for pseudorandom generators.
    /// - [`curandStatus::CURAND_STATUS_NOT_INITIALIZED`]: if the generator was never created.
    /// - [`curandStatus::CURAND_STATUS_PREEXISTING_FAILURE`]: if there was an existing error from a previous kernel launch.
    /// - [`curandStatus::CURAND_STATUS_SUCCESS`]: if the results were generated successfully.
    pub fn curandGenerateLogNormal(
        generator: curandGenerator_t,
        outputPtr: *mut f32,
        n: size_t,
        mean: f32,
        stddev: f32,
    ) -> curandStatus_t;
}
unsafe extern "C" {
    /// Generate log-normally distributed doubles.
    ///
    /// # Parameters
    ///
    /// - `generator`: Generator to use.
    /// - `outputPtr`: Pointer to device memory to store CUDA-generated results, or Pointer to host memory to store CPU-generated results.
    /// - `n`: Number of doubles to generate.
    /// - `mean`: Mean of normal distribution.
    /// - `stddev`: Standard deviation of normal distribution.
    ///
    /// # Return value
    ///
    /// - [`curandStatus::CURAND_STATUS_ALLOCATION_FAILED`]: if memory could not be allocated.
    /// - [`curandStatus::CURAND_STATUS_DOUBLE_PRECISION_REQUIRED`]: if the GPU does not support double precision.
    /// - [`curandStatus::CURAND_STATUS_LAUNCH_FAILURE`]: if the kernel launch failed for any reason.
    /// - [`curandStatus::CURAND_STATUS_LENGTH_NOT_MULTIPLE`]: if the number of output samples is not a multiple of the quasirandom dimension, or is not a multiple of two for pseudorandom generators.
    /// - [`curandStatus::CURAND_STATUS_NOT_INITIALIZED`]: if the generator was never created.
    /// - [`curandStatus::CURAND_STATUS_PREEXISTING_FAILURE`]: if there was an existing error from a previous kernel launch.
    /// - [`curandStatus::CURAND_STATUS_SUCCESS`]: if the results were generated successfully.
    pub fn curandGenerateLogNormalDouble(
        generator: curandGenerator_t,
        outputPtr: *mut f64,
        n: size_t,
        mean: f64,
        stddev: f64,
    ) -> curandStatus_t;
}
unsafe extern "C" {
    /// Construct the histogram array for a Poisson distribution.
    ///
    /// # Parameters
    ///
    /// - `lambda`: lambda for the Poisson distribution.
    /// - `discrete_distribution`: pointer to the histogram in device memory.
    ///
    /// # Return value
    ///
    /// - [`curandStatus::CURAND_STATUS_ALLOCATION_FAILED`]: if memory could not be allocated.
    /// - [`curandStatus::CURAND_STATUS_DOUBLE_PRECISION_REQUIRED`]: if the GPU does not support double precision.
    /// - [`curandStatus::CURAND_STATUS_INITIALIZATION_FAILED`]: if there was a problem setting up the GPU.
    /// - [`curandStatus::CURAND_STATUS_NOT_INITIALIZED`]: if the distribution pointer was null.
    /// - [`curandStatus::CURAND_STATUS_OUT_OF_RANGE`]: if lambda is non-positive or greater than 400,000.
    /// - [`curandStatus::CURAND_STATUS_PREEXISTING_FAILURE`]: if there was an existing error from a previous kernel launch.
    /// - [`curandStatus::CURAND_STATUS_SUCCESS`]: if the histogram was generated successfully.
    pub fn curandCreatePoissonDistribution(
        lambda: f64,
        discrete_distribution: *mut curandDiscreteDistribution_t,
    ) -> curandStatus_t;
}
unsafe extern "C" {
    /// Destroy the histogram array for a discrete distribution (e.g. Poisson).
    ///
    /// # Parameters
    ///
    /// - `discrete_distribution`: pointer to device memory where the histogram is stored.
    ///
    /// # Return value
    ///
    /// - [`curandStatus::CURAND_STATUS_NOT_INITIALIZED`]: if the histogram was never created.
    /// - [`curandStatus::CURAND_STATUS_SUCCESS`]: if the histogram was destroyed successfully.
    pub fn curandDestroyDistribution(
        discrete_distribution: curandDiscreteDistribution_t,
    ) -> curandStatus_t;
}
unsafe extern "C" {
    /// Generate Poisson-distributed unsigned ints.
    ///
    /// # Parameters
    ///
    /// - `generator`: Generator to use.
    /// - `outputPtr`: Pointer to device memory to store CUDA-generated results, or Pointer to host memory to store CPU-generated results.
    /// - `n`: Number of unsigned ints to generate.
    /// - `lambda`: lambda for the Poisson distribution.
    ///
    /// # Return value
    ///
    /// - [`curandStatus::CURAND_STATUS_ALLOCATION_FAILED`]: if memory could not be allocated.
    /// - [`curandStatus::CURAND_STATUS_DOUBLE_PRECISION_REQUIRED`]: if the GPU or sm does not support double precision.
    /// - [`curandStatus::CURAND_STATUS_LAUNCH_FAILURE`]: if the kernel launch failed for any reason.
    /// - [`curandStatus::CURAND_STATUS_LENGTH_NOT_MULTIPLE`]: if the number of output samples is not a multiple of the quasirandom dimension.
    /// - [`curandStatus::CURAND_STATUS_NOT_INITIALIZED`]: if the generator was never created.
    /// - [`curandStatus::CURAND_STATUS_OUT_OF_RANGE`]: if lambda is non-positive or greater than 400,000.
    /// - [`curandStatus::CURAND_STATUS_PREEXISTING_FAILURE`]: if there was an existing error from a previous kernel launch.
    /// - [`curandStatus::CURAND_STATUS_SUCCESS`]: if the results were generated successfully.
    pub fn curandGeneratePoisson(
        generator: curandGenerator_t,
        outputPtr: *mut ::core::ffi::c_uint,
        n: size_t,
        lambda: f64,
    ) -> curandStatus_t;
}
unsafe extern "C" {
    pub fn curandGeneratePoissonMethod(
        generator: curandGenerator_t,
        outputPtr: *mut ::core::ffi::c_uint,
        n: size_t,
        lambda: f64,
        method: curandMethod_t,
    ) -> curandStatus_t;
}
unsafe extern "C" {
    pub fn curandGenerateBinomial(
        generator: curandGenerator_t,
        outputPtr: *mut ::core::ffi::c_uint,
        num: size_t,
        n: ::core::ffi::c_uint,
        p: f64,
    ) -> curandStatus_t;
}
unsafe extern "C" {
    pub fn curandGenerateBinomialMethod(
        generator: curandGenerator_t,
        outputPtr: *mut ::core::ffi::c_uint,
        num: size_t,
        n: ::core::ffi::c_uint,
        p: f64,
        method: curandMethod_t,
    ) -> curandStatus_t;
}
unsafe extern "C" {
    /// Setup starting states.
    ///
    /// # Parameters
    ///
    /// - `generator`: Generator to update.
    ///
    /// # Return value
    ///
    /// - [`curandStatus::CURAND_STATUS_ALLOCATION_FAILED`]: if memory could not be allocated.
    /// - [`curandStatus::CURAND_STATUS_LAUNCH_FAILURE`]: if the kernel launch failed for any reason.
    /// - [`curandStatus::CURAND_STATUS_NOT_INITIALIZED`]: if the generator was never created.
    /// - [`curandStatus::CURAND_STATUS_PREEXISTING_FAILURE`]: if there was an existing error from a previous kernel launch.
    /// - [`curandStatus::CURAND_STATUS_SUCCESS`]: if the seeds were generated successfully.
    pub fn curandGenerateSeeds(generator: curandGenerator_t) -> curandStatus_t;
}
unsafe extern "C" {
    /// Get direction vectors for 32-bit quasirandom number generation.
    ///
    /// # Parameters
    ///
    /// - `vectors`: Address of pointer in which to return direction vectors.
    /// - `set`: Which set of direction vectors to use.
    ///
    /// # Return value
    ///
    /// - [`curandStatus::CURAND_STATUS_OUT_OF_RANGE`]: if the choice of set is invalid.
    /// - [`curandStatus::CURAND_STATUS_SUCCESS`]: if the pointer was set successfully.
    pub fn curandGetDirectionVectors32(
        vectors: *mut *mut curandDirectionVectors32_t,
        set: curandDirectionVectorSet_t,
    ) -> curandStatus_t;
}
unsafe extern "C" {
    /// Get scramble constants for 32-bit scrambled Sobol' .
    ///
    /// # Parameters
    ///
    /// - `constants`: Address of pointer in which to return scramble constants.
    ///
    /// # Return value
    ///
    /// - [`curandStatus::CURAND_STATUS_SUCCESS`]: if the pointer was set successfully.
    pub fn curandGetScrambleConstants32(
        constants: *mut *mut ::core::ffi::c_uint,
    ) -> curandStatus_t;
}
unsafe extern "C" {
    /// Get direction vectors for 64-bit quasirandom number generation.
    ///
    /// # Parameters
    ///
    /// - `vectors`: Address of pointer in which to return direction vectors.
    /// - `set`: Which set of direction vectors to use.
    ///
    /// # Return value
    ///
    /// - [`curandStatus::CURAND_STATUS_OUT_OF_RANGE`]: if the choice of set is invalid.
    /// - [`curandStatus::CURAND_STATUS_SUCCESS`]: if the pointer was set successfully.
    pub fn curandGetDirectionVectors64(
        vectors: *mut *mut curandDirectionVectors64_t,
        set: curandDirectionVectorSet_t,
    ) -> curandStatus_t;
}
unsafe extern "C" {
    /// Get scramble constants for 64-bit scrambled Sobol' .
    ///
    /// # Parameters
    ///
    /// - `constants`: Address of pointer in which to return scramble constants.
    ///
    /// # Return value
    ///
    /// - [`curandStatus::CURAND_STATUS_SUCCESS`]: if the pointer was set successfully.
    pub fn curandGetScrambleConstants64(
        constants: *mut *mut ::core::ffi::c_ulonglong,
    ) -> curandStatus_t;
}
